{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.2.0.alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1.jar",
          "size": 181682,
          "sha512": "75ec2568655dd02a50cf47b98fdb12adc415529880e48f5d684436b8a290f44c4b9025190fe4e1b8f3bf1c4c536b59338cec4f29621a994708485947dbcefa4f",
          "sha256": "403e00de2be1e90eb86202a775fe9681350ec66c6badb7f2c887e81405cb15a1",
          "sha1": "56f379333efb5e9422aeb67dfb52dc7762b118b7",
          "md5": "207e4dfd3261135a1ee08302d4698d34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1.jar",
          "size": 181682,
          "sha512": "75ec2568655dd02a50cf47b98fdb12adc415529880e48f5d684436b8a290f44c4b9025190fe4e1b8f3bf1c4c536b59338cec4f29621a994708485947dbcefa4f",
          "sha256": "403e00de2be1e90eb86202a775fe9681350ec66c6badb7f2c887e81405cb15a1",
          "sha1": "56f379333efb5e9422aeb67dfb52dc7762b118b7",
          "md5": "207e4dfd3261135a1ee08302d4698d34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.2+1.21.1-sources.jar",
          "size": 75297,
          "sha512": "acb7e33c5ea07ab169c4b8550249e51c88bd23eae2d4322e113c18c757a7a1d333a823274c53351166a2acf74c0c2f676e5aadb4b2df26a4c28f81bfe7ac57ab",
          "sha256": "a9609d9ff6242ea8a3c7ac970b913a0c9217813dabca5389fcc4ad2760729e5d",
          "sha1": "8dc7833d79fa28c7f1e0b6ffcbc103de04974a80",
          "md5": "1b57b01ca29cee820ecb6750f1f14bbc"
        }
      ]
    }
  ]
}
