{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-common-api",
    "version": "3.8.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.8.0+1.21.1.jar",
          "url": "minecraft-cursor-common-api-3.8.0+1.21.1.jar",
          "size": 10435,
          "sha512": "dd9e35607b7601ae060591d6b15655790397df1e0182e1ddc7227fc814b4b80471c0402fb0148b8751902a5cfc29fd03b9e7a32a54e9d5dafaac51a27c4e1774",
          "sha256": "21090f098c5fcd2771217f1c3b871ee9c799a9db4b71eaad5d42505b8f5686a1",
          "sha1": "ad0f2a6d252b9d1d39ae422931f7c88f9883467d",
          "md5": "d79a041c3c85d6fef98afc3ac6c691bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.8.0+1.21.1.jar",
          "url": "minecraft-cursor-common-api-3.8.0+1.21.1.jar",
          "size": 10435,
          "sha512": "dd9e35607b7601ae060591d6b15655790397df1e0182e1ddc7227fc814b4b80471c0402fb0148b8751902a5cfc29fd03b9e7a32a54e9d5dafaac51a27c4e1774",
          "sha256": "21090f098c5fcd2771217f1c3b871ee9c799a9db4b71eaad5d42505b8f5686a1",
          "sha1": "ad0f2a6d252b9d1d39ae422931f7c88f9883467d",
          "md5": "d79a041c3c85d6fef98afc3ac6c691bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.8.0+1.21.1-sources.jar",
          "url": "minecraft-cursor-common-api-3.8.0+1.21.1-sources.jar",
          "size": 8744,
          "sha512": "107398cba43d6dcbb4cdc0a9997ff69ee4baeb1cc0f6b0607aa5851e8cf58de7a15f1d8c6c325ce9c276148274bcbe3927b817b9d5fc849a8bf74c8667af5578",
          "sha256": "65a32de1cec9b46ac8a13978a5e50a618a8ba2f101bf8ebe2db0fbe67ccfca1e",
          "sha1": "8f69b18012cbf4d781242982fc261be5bfc85de2",
          "md5": "84fb40e81d442a56ab9c854ac7b3dede"
        }
      ]
    }
  ]
}
