{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.9.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.9.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-fabric-3.9.0+1.21.4.jar",
          "size": 262290,
          "sha512": "38c8a0766058f79a1a4213d327cf51c7b4209d96ab004ca4d9624ce0aeac646d31fd07167dd51743885de13f96444bc42e781cd105e84d65a4e3b86aa82e2c68",
          "sha256": "1f1ec66f195a9a77c9c07801e78a180afbe3f692037b6922a2f5889d4c0f27bf",
          "sha1": "43434f3cb0001a56ea15ad5e689ce5b6fbc59625",
          "md5": "1e2eea1fe00024e9361c1fb762deef2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.9.0+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.0+1.21.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-fabric-3.9.0+1.21.4.jar",
          "size": 262290,
          "sha512": "38c8a0766058f79a1a4213d327cf51c7b4209d96ab004ca4d9624ce0aeac646d31fd07167dd51743885de13f96444bc42e781cd105e84d65a4e3b86aa82e2c68",
          "sha256": "1f1ec66f195a9a77c9c07801e78a180afbe3f692037b6922a2f5889d4c0f27bf",
          "sha1": "43434f3cb0001a56ea15ad5e689ce5b6fbc59625",
          "md5": "1e2eea1fe00024e9361c1fb762deef2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.9.0+1.21.4-sources.jar",
          "url": "minecraft-cursor-fabric-3.9.0+1.21.4-sources.jar",
          "size": 127991,
          "sha512": "8d00f8810dfff20ae0c0f0e84cf23af113be08ea4f2e9623acfdf24f29f2b9c254c238746db9751f8679f34ba4ba04e867dce63c14036a51a2cbf11b473c8168",
          "sha256": "f74814e6f806b3fd0205c7128e9a3c5b3585464e0fb8004a35d50ab65c559b35",
          "sha1": "cfc7dc6f038187a7ac11fb291f299b86491df335",
          "md5": "1d40616c7cf917729547f0f7b7a101ce"
        }
      ]
    }
  ]
}
