{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.5.2+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.2+1.21.11.jar",
          "url": "fidgetz-neoforge-0.5.2+1.21.11.jar",
          "size": 310288,
          "sha512": "f13d455c64916f34082cecf7519676d9f8dc2d5e15bb5f7bacec74b32417298bd8e51fb5010d2d1d1361c0e8e19458b12243e58afd1499f718718accb7dcafd1",
          "sha256": "26299c18fa920af890327126391b599e59775002278947d3350a42abf7119e86",
          "sha1": "2704253b0eef82d2de280925719169ddc7cf1830",
          "md5": "980efd917c9a7519f6c3cc4f19ba0530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.2+1.21.11.jar",
          "url": "fidgetz-neoforge-0.5.2+1.21.11.jar",
          "size": 310288,
          "sha512": "f13d455c64916f34082cecf7519676d9f8dc2d5e15bb5f7bacec74b32417298bd8e51fb5010d2d1d1361c0e8e19458b12243e58afd1499f718718accb7dcafd1",
          "sha256": "26299c18fa920af890327126391b599e59775002278947d3350a42abf7119e86",
          "sha1": "2704253b0eef82d2de280925719169ddc7cf1830",
          "md5": "980efd917c9a7519f6c3cc4f19ba0530"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.2+1.21.11-sources.jar",
          "url": "fidgetz-neoforge-0.5.2+1.21.11-sources.jar",
          "size": 119717,
          "sha512": "79ba21650060305f42c17889cdbd23aa01c9775339afd277fc61ba27de7fe34560cd328491279a4f069454312d0fb5ebaa1dd6afeef055b19b9f024abad4e7f5",
          "sha256": "11ac69bf1797cda6ec800576d9904b2155bbd28195e934c2c1b6b8a706f77ee9",
          "sha1": "c8d8528af8d707a3cb69230633b4cdaca42f465f",
          "md5": "cd3894dbd99b020e01bb9242f554763f"
        }
      ]
    }
  ]
}
