{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.2.0+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0+1.21.9.jar",
          "url": "fidgetz-common-0.2.0+1.21.9.jar",
          "size": 176370,
          "sha512": "aad42db6e07181231a1d36656950423cdb476baef4dda3f29c63fc2aa08f0740d9b6edc05b25a0363f3bcd030cfdb121eeb5ca9939becbb349882288ada0a4e6",
          "sha256": "32f2de980a935bd001ab6fab57832cbddde3885b2be4080ddef3d7048203b0b7",
          "sha1": "4fb0ff0038b165a186fc1db9bd7b038f7c2134c2",
          "md5": "6b721e29fb29272d682786d8a781bfa1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0+1.21.9.jar",
          "url": "fidgetz-common-0.2.0+1.21.9.jar",
          "size": 176370,
          "sha512": "aad42db6e07181231a1d36656950423cdb476baef4dda3f29c63fc2aa08f0740d9b6edc05b25a0363f3bcd030cfdb121eeb5ca9939becbb349882288ada0a4e6",
          "sha256": "32f2de980a935bd001ab6fab57832cbddde3885b2be4080ddef3d7048203b0b7",
          "sha1": "4fb0ff0038b165a186fc1db9bd7b038f7c2134c2",
          "md5": "6b721e29fb29272d682786d8a781bfa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0+1.21.9-sources.jar",
          "url": "fidgetz-common-0.2.0+1.21.9-sources.jar",
          "size": 72414,
          "sha512": "7f78415b1fe1e15a7e73d734bcaa58f85852fe6ecb1af989b0cd219bfb6cc29098ee16b4531fbd2e13e9496b83091a4e305a5eb66587f2b6c44bf76fa89ccaa4",
          "sha256": "b37f248c1fd168ef2d95a5578c70e28bd9f5aa63a5605050783bce94ec767ddb",
          "sha1": "740e49d6ec1452a230d0230bfb9ae8ae93efdd6e",
          "md5": "bea0478eba9da35fae3d4c2aa1650f3c"
        }
      ]
    }
  ]
}
