{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.10+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.10+1.21.1.jar",
          "size": 469356,
          "sha512": "5e4a2655e0966f093a0bfb7032db962921c580b95bedf17574886604f2c584e5c530baf5e350741b72ddc8e81e3ca0e52d8dbb8c038325cf96d4b021eedea3f9",
          "sha256": "03e0d3a424fd70fb4e1dcbb45f68f95a6da0768a21c9e24c2177bef4f9b61469",
          "sha1": "2bf1144ff7aec22fb71be777b5227f9fd5837459",
          "md5": "5df81e7590e06253422ff717cd4a59f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.10+1.21.1.jar",
          "size": 469356,
          "sha512": "5e4a2655e0966f093a0bfb7032db962921c580b95bedf17574886604f2c584e5c530baf5e350741b72ddc8e81e3ca0e52d8dbb8c038325cf96d4b021eedea3f9",
          "sha256": "03e0d3a424fd70fb4e1dcbb45f68f95a6da0768a21c9e24c2177bef4f9b61469",
          "sha1": "2bf1144ff7aec22fb71be777b5227f9fd5837459",
          "md5": "5df81e7590e06253422ff717cd4a59f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.10+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.10+1.21.1-sources.jar",
          "size": 176201,
          "sha512": "1a182585cf87295448d0807b6568b02b95f5ded300128c8a4cc0a3499fea0912b6012f0eb898a3951a544000c5ee984fe766ac33d3355ff4388c6bc6051398f6",
          "sha256": "17825240a9002d88feca095c920c327148876d22500aa02bb486aba4d39b0c07",
          "sha1": "ab49c8f8f8cf5710f2a17f3027148d6724f1ea0c",
          "md5": "b6a89b3b6c7d7c330601cfbce9998c6c"
        }
      ]
    }
  ]
}
