{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.2+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.2+26.2.jar",
          "url": "packed_packs_api-common-2.2.2+26.2.jar",
          "size": 31938,
          "sha512": "69f34e84e6c55b2cc033f6c9cfbaa7296d07b57d9fced130f800d9046d37ddd9c84dc724c5ca6c3d8cf4014030e0d62210defad0cb55d476f9872cec827df289",
          "sha256": "34f52a357d9b819b2442aca9f3e8905bac6f7f6b105dfceb42654d31a2d3a600",
          "sha1": "de416e00b64f0bb88b2e3470ed02b19c3d866a3e",
          "md5": "b5fa74f981631f37104101a786019c68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.2+26.2.jar",
          "url": "packed_packs_api-common-2.2.2+26.2.jar",
          "size": 31938,
          "sha512": "69f34e84e6c55b2cc033f6c9cfbaa7296d07b57d9fced130f800d9046d37ddd9c84dc724c5ca6c3d8cf4014030e0d62210defad0cb55d476f9872cec827df289",
          "sha256": "34f52a357d9b819b2442aca9f3e8905bac6f7f6b105dfceb42654d31a2d3a600",
          "sha1": "de416e00b64f0bb88b2e3470ed02b19c3d866a3e",
          "md5": "b5fa74f981631f37104101a786019c68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.2+26.2-sources.jar",
          "url": "packed_packs_api-common-2.2.2+26.2-sources.jar",
          "size": 19058,
          "sha512": "52cb8c2275cf1cc3ca906f7bf1ebed5a5b1ecee83b3d0aee8027995b2891349305c5b2698d84647dd3b0e94e57d9c3be10eda7c9bde0234b01e259e48195ad48",
          "sha256": "be884312cb5403cd6cbef89f7740c067bea72e753031cf162993267c180c03bd",
          "sha1": "250f9a9fa28b421b084f1b290331c7671cef057d",
          "md5": "f2ef4b32c8ec3418ab9f0e75b959b272"
        }
      ]
    }
  ]
}
