{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.2.4+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.4+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.6.2+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.4+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.4+1.21.11.jar",
          "size": 818721,
          "sha512": "84729e052b6d94485982ff163c6dc41eee7dd04987698f7965306d4a0c817ae1045578c3b844c70348f637515f1ec48e2ba664abccb78fefb5f7d8292efa8c0a",
          "sha256": "2cd9397d63cc7073387f739179a6f58c22f3d0ac655b551e419f259bdbe96d92",
          "sha1": "f8840e00f23506c0bd622496e01c6b9674748e3c",
          "md5": "c4c9ca67ee3f0cdecc83c26f609318ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.4+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.6.2+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.4+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.4+1.21.11.jar",
          "size": 818721,
          "sha512": "84729e052b6d94485982ff163c6dc41eee7dd04987698f7965306d4a0c817ae1045578c3b844c70348f637515f1ec48e2ba664abccb78fefb5f7d8292efa8c0a",
          "sha256": "2cd9397d63cc7073387f739179a6f58c22f3d0ac655b551e419f259bdbe96d92",
          "sha1": "f8840e00f23506c0bd622496e01c6b9674748e3c",
          "md5": "c4c9ca67ee3f0cdecc83c26f609318ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.2.4+1.21.11-sources.jar",
          "url": "packed_packs-fabric-2.2.4+1.21.11-sources.jar",
          "size": 190847,
          "sha512": "70639c65b1c40d68918653f459c31d3664c0e9bd1fdb151fa994b03966e0e4cac0a5410cfd316532dfc3dc65b011653373af18aeacd81a2f2ca874cfb37c63b2",
          "sha256": "92ff71d7077a3a2ed810536bc87f703fbcbc2df08fe45a3c5d60c2dcc05f94bb",
          "sha1": "f25e5ead8112380e92e37d2eecaf0efd40a354b9",
          "md5": "df51b2d5c584388fd48f9ac906c9345a"
        }
      ]
    }
  ]
}
