{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "size": 26801,
          "sha512": "9ecf276a4e4dda42292e2c349220cc128419f47482ede02218430b41b5f5c0336e07717c689e1f7dbf081cf5b6cd58695af63cc24d1b3da6a9027c1d5b46d333",
          "sha256": "b1b5c5a2e3dfce4f86473f0969bffa65f7674fb4725415fde5890a4270bf43df",
          "sha1": "529750ca3c4975df939de39ef27200730f957081",
          "md5": "32b993493e24d55edd70ecae8f81fc1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "size": 26801,
          "sha512": "9ecf276a4e4dda42292e2c349220cc128419f47482ede02218430b41b5f5c0336e07717c689e1f7dbf081cf5b6cd58695af63cc24d1b3da6a9027c1d5b46d333",
          "sha256": "b1b5c5a2e3dfce4f86473f0969bffa65f7674fb4725415fde5890a4270bf43df",
          "sha1": "529750ca3c4975df939de39ef27200730f957081",
          "md5": "32b993493e24d55edd70ecae8f81fc1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.4+1.21.1-sources.jar",
          "size": 15181,
          "sha512": "c35447c7a19e600df08ab08bf348cb90ca6026562ea2b8ece4ae5ff8e0906f759022fb95092f0caac63dfc549f77cde529a744a33ba59a928c1dacc9435acca6",
          "sha256": "a258f3c25f7c91675e6df9b02cd18f192732fcfbc5f90cd3f4e9008e126bd484",
          "sha1": "8534241b56b7d2c009d348fe69d92e7bd1f1e5d2",
          "md5": "1d2ed5d74c4dffcaaf5a60c298e761d9"
        }
      ]
    }
  ]
}
