{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1.jar",
          "size": 33317,
          "sha512": "2b3bd49510674ae51bd489eaf21581d421716751131a8da05d852551e5186f33f91366d2deb4375389098fcce421f4fd82cb9ff12aef9e1acc18ce492aaf1b90",
          "sha256": "03c7c5932ab3f5aa41bed61b7c531f78e3d44f4e929da53417dd85f9e17d4ab9",
          "sha1": "fc4daab2391368a51ff69deac6ef3f91b494efe1",
          "md5": "fae282d411e8f347f1eb8490f1102e2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1.jar",
          "size": 33317,
          "sha512": "2b3bd49510674ae51bd489eaf21581d421716751131a8da05d852551e5186f33f91366d2deb4375389098fcce421f4fd82cb9ff12aef9e1acc18ce492aaf1b90",
          "sha256": "03c7c5932ab3f5aa41bed61b7c531f78e3d44f4e929da53417dd85f9e17d4ab9",
          "sha1": "fc4daab2391368a51ff69deac6ef3f91b494efe1",
          "md5": "fae282d411e8f347f1eb8490f1102e2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+1.21.1-sources.jar",
          "size": 19902,
          "sha512": "faf4ce5590c470ff848c8e60ce620244da76368ce5b990fcf9b163029717c1d35d123e10cbcab06f87b30958cfbed5e7be8d9e7a39d293b87ba50bd9a08219ae",
          "sha256": "35a74b4e7151708f5542b77abe89fed276e6b66486075b3a421ee613b7e40082",
          "sha1": "ff30ea2fe27c2e07d4d781fc839883a3902be6e4",
          "md5": "ed796e9148bc977bf0b516010dc01e33"
        }
      ]
    }
  ]
}
