{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.8+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.8+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.8+1.21.1.jar",
          "size": 467343,
          "sha512": "a4cc1dfd796c97a538cf592950097d5e4345bee9c7018a1bd84b6834e70c043b7889381bdbdfa94b604a61686c4d2eedd9917d5b8fdd9ce44c2adae5c862e773",
          "sha256": "305b60d15e9367ed6445fbbf5ce086af25286a7a8256ddf7b0a681ec7fbb35c2",
          "sha1": "341ad02bbaa771b0f5a277ded638af891182043f",
          "md5": "b789f0687d87a8728c4d2d567da08c87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.8+1.21.1.jar",
          "size": 467343,
          "sha512": "a4cc1dfd796c97a538cf592950097d5e4345bee9c7018a1bd84b6834e70c043b7889381bdbdfa94b604a61686c4d2eedd9917d5b8fdd9ce44c2adae5c862e773",
          "sha256": "305b60d15e9367ed6445fbbf5ce086af25286a7a8256ddf7b0a681ec7fbb35c2",
          "sha1": "341ad02bbaa771b0f5a277ded638af891182043f",
          "md5": "b789f0687d87a8728c4d2d567da08c87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.8+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.8+1.21.1-sources.jar",
          "size": 175539,
          "sha512": "75f43bc41dc2b2355590aea6d80853c46ca5ab0d177be13a93c485cd4481595293ed80caf3e44debfea109adebc0ac58b4df0411547662331ef3980b9b3e7f0c",
          "sha256": "347e0fc1e22abeeead0b8b28bb2dda47187e13733fbbd15af070c89ac6557abb",
          "sha1": "d3151536b5c1d56727e967a41a3d6487d44dd1bf",
          "md5": "58570aab381b2a9de4c96a9057359302"
        }
      ]
    }
  ]
}
