{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1.jar",
          "size": 27188,
          "sha512": "af14b342896c844c9e90f6ca4124f30105d12b76ac76b66cfb3a9ca5e6cd05b3488d4c26d580f93e51e25b90f8289cc087db002a8c447cd458ca7c18647e29c8",
          "sha256": "df4a2c08d51252c1ada64b458d93cb6fa5b88e808294dcc46dde899b93efed74",
          "sha1": "56de4b72affc3e71ecc4b3a74cda0533db4698e4",
          "md5": "9e06a58fbc820edbf14b14c1b3955e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1.jar",
          "size": 27188,
          "sha512": "af14b342896c844c9e90f6ca4124f30105d12b76ac76b66cfb3a9ca5e6cd05b3488d4c26d580f93e51e25b90f8289cc087db002a8c447cd458ca7c18647e29c8",
          "sha256": "df4a2c08d51252c1ada64b458d93cb6fa5b88e808294dcc46dde899b93efed74",
          "sha1": "56de4b72affc3e71ecc4b3a74cda0533db4698e4",
          "md5": "9e06a58fbc820edbf14b14c1b3955e00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.10+1.21.1-sources.jar",
          "size": 17380,
          "sha512": "59478a348dda98497f4186f25199015b1a4fb669244432e9ad028f70a0d61bfd573682f6e239a5d6979752e6472d35bef19687a6ff601fa71d1cf588b1c7f2ad",
          "sha256": "f2fe5c1d13bfbba42139e90ffcc01d782632ac2164ac81290b73ac8f5c1e38f6",
          "sha1": "831ca7d973bb934b4461976be4887cac4ba91b06",
          "md5": "dbad910dea0fb6ef44a3d5fb8de298f8"
        }
      ]
    }
  ]
}
