{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.8+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.8+1.21.1.jar",
          "size": 26149,
          "sha512": "b8f6e0476f134744bda6d98a7510321efc1d5b6acdd1f7f15667ffd9d9fe759a238519fec668f2a2bc98b4f9ec02e37e701940f0303288e522ff47e7a554f2a2",
          "sha256": "64803703a082efe5cb3b857c2d20baa90ffb2e25dbf87eb941ed38ff82de3f03",
          "sha1": "3e88c719218c1980ab1fb12983165d7d6dd2b7f8",
          "md5": "ddb0aa79f49fa78e0615a3970c7b6b57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.8+1.21.1.jar",
          "size": 26149,
          "sha512": "b8f6e0476f134744bda6d98a7510321efc1d5b6acdd1f7f15667ffd9d9fe759a238519fec668f2a2bc98b4f9ec02e37e701940f0303288e522ff47e7a554f2a2",
          "sha256": "64803703a082efe5cb3b857c2d20baa90ffb2e25dbf87eb941ed38ff82de3f03",
          "sha1": "3e88c719218c1980ab1fb12983165d7d6dd2b7f8",
          "md5": "ddb0aa79f49fa78e0615a3970c7b6b57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.8+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.8+1.21.1-sources.jar",
          "size": 14822,
          "sha512": "0f0bdb2adbb655df459e40de58e52ab8e8217e286306517da062fd239d83ea27191770434c2e94f159f6731c1515b8e87c92e4feb4370318c0c0d429ca59d0c7",
          "sha256": "dbe5306f80b6e9697b83000d52744a701104695165ec558e72435a591932b02a",
          "sha1": "49a3963b6243126e5c2a359a428be8aab22188e8",
          "md5": "2883047e70749dabbbfbf5718251cf56"
        }
      ]
    }
  ]
}
