{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.1+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.1+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.1+26.3.jar",
          "size": 33238,
          "sha512": "8d052a3ab3853f519c4d0d1057040edcaf64bd58d1e72936e792cbcf0d0ac94e7f1346962f2db1c95dd2ce4c1136502b55ca84867dcf812bed37e9d57b0ab66a",
          "sha256": "1e9c158faeb9430f947b658238235be18dd0d434b3c4bc6e1480d46eb7634f27",
          "sha1": "bdb92f28287e71df7b1b14bd9865a59ac67a6eb0",
          "md5": "f352930dcdcdfede85d83a8871fc4058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.1+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.1+26.3.jar",
          "size": 33238,
          "sha512": "8d052a3ab3853f519c4d0d1057040edcaf64bd58d1e72936e792cbcf0d0ac94e7f1346962f2db1c95dd2ce4c1136502b55ca84867dcf812bed37e9d57b0ab66a",
          "sha256": "1e9c158faeb9430f947b658238235be18dd0d434b3c4bc6e1480d46eb7634f27",
          "sha1": "bdb92f28287e71df7b1b14bd9865a59ac67a6eb0",
          "md5": "f352930dcdcdfede85d83a8871fc4058"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.1+26.3-sources.jar",
          "url": "packed_packs_api-fabric-2.3.1+26.3-sources.jar",
          "size": 19405,
          "sha512": "25777826d7fb35726114dab59a06856c36ccc5e761c0b85750bad892c4261fb078a2b8f0347f92e93a79be2640e36bd008fcd816f98242d2646aa292e5da9fc1",
          "sha256": "d53be9e363e05ac84e0944362092ff28d8a7419ebe26b0215daf4d63098f84fc",
          "sha1": "7e3e0f9c98510c1bc85d0a91a63f72ef32d0f7b6",
          "md5": "c26a72ed9a0542d45a631a68c5cf6601"
        }
      ]
    }
  ]
}
