{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-common-api",
    "version": "3.11.3+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.11.3+1.21.6.jar",
          "url": "minecraft-cursor-common-api-3.11.3+1.21.6.jar",
          "size": 12725,
          "sha512": "9c3bab422faa89a737d07ea5c007f577f68579a35bb820166f8154b443df944029e84af4b1c210d59b398f8847a8dadb6ef9ccfaad6f11110bb8bfbac024110f",
          "sha256": "aa8ce8a868a9ea98a7325ce2b9ce4ee5c9693282340e9e4d71ef1747d9a978da",
          "sha1": "7ce2d265d40e4e5237bdaf6a8905ce41ac5c21ae",
          "md5": "a9a1b40a68f916470603c50e98d5de2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.11.3+1.21.6.jar",
          "url": "minecraft-cursor-common-api-3.11.3+1.21.6.jar",
          "size": 12725,
          "sha512": "9c3bab422faa89a737d07ea5c007f577f68579a35bb820166f8154b443df944029e84af4b1c210d59b398f8847a8dadb6ef9ccfaad6f11110bb8bfbac024110f",
          "sha256": "aa8ce8a868a9ea98a7325ce2b9ce4ee5c9693282340e9e4d71ef1747d9a978da",
          "sha1": "7ce2d265d40e4e5237bdaf6a8905ce41ac5c21ae",
          "md5": "a9a1b40a68f916470603c50e98d5de2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.11.3+1.21.6-sources.jar",
          "url": "minecraft-cursor-common-api-3.11.3+1.21.6-sources.jar",
          "size": 9055,
          "sha512": "28bdb75eb9da7488105cf5fb9ac1c6a8da5dc25061b8c1a5b22d3366b215a884f862275d8ab36d6eddd19e079202195c54e6a0b0f1a7418caeefe105680b263d",
          "sha256": "87960fedeff5167a2b04e42f2f05ccbfc1b04943b9dc2463db961c4926ac8c27",
          "sha1": "380291da363fa8aa736934d540c5d8c01b7504e3",
          "md5": "0da527e1c22761dfb3bba8d0d9eaeac4"
        }
      ]
    }
  ]
}
