{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.2+1.21.1.jar",
          "size": 675750,
          "sha512": "d65238417fc08892aae9c2ac0c96f4b5026bc897f5a783d79c07bc3903e02863a949486c7c9f56e79f932107972712ff736d653e189f3a4f8530e2ef24c36755",
          "sha256": "b19fb859da0a4d4e87d2a64161cef129ad1642874d4c05bf7a2127b9891cee53",
          "sha1": "b81ab9a7743e5d91e7d1971df73dae37db556c65",
          "md5": "c0b74737024df838afd1624f4f7bdada"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.2+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.2+1.21.1.jar",
          "size": 675750,
          "sha512": "d65238417fc08892aae9c2ac0c96f4b5026bc897f5a783d79c07bc3903e02863a949486c7c9f56e79f932107972712ff736d653e189f3a4f8530e2ef24c36755",
          "sha256": "b19fb859da0a4d4e87d2a64161cef129ad1642874d4c05bf7a2127b9891cee53",
          "sha1": "b81ab9a7743e5d91e7d1971df73dae37db556c65",
          "md5": "c0b74737024df838afd1624f4f7bdada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.2+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.2+1.21.1-sources.jar",
          "size": 202437,
          "sha512": "8dfd3a866413cc040d31a6cc32ea1616decd52a2fc2f0161d855ba6dafb65e8e0a569c766fdc13b44264da202782b89158af3af3973ea41e83888ece330a20c5",
          "sha256": "25c9eef0fde1ed291c4585e88bd501f37a826934bcc091204641cc1404fc15b2",
          "sha1": "4f90744a9e411026c603f88cc730b3917221ae87",
          "md5": "8fc2634c2c7ffc8064b9777107cd0d19"
        }
      ]
    }
  ]
}
