{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.2+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.2.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.2.jar",
          "size": 34238,
          "sha512": "30e4316d4657127929ceba47b72242e2c28bfb8bef3d2d88ec437e30a74d578457aa5651476de0f01fb3bcea36cf3f3d35321cc9dcb9bff8b01f9f6c99394729",
          "sha256": "c525d2cc94842ac46ea868856b0820a10777743011c55042068aaf7d4486a276",
          "sha1": "ce9f8fa6b2fe8cda0945fef5247ab51a6d50284c",
          "md5": "65f12cd32a84519109bd38e5a8d89f68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.2.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.2.jar",
          "size": 34238,
          "sha512": "30e4316d4657127929ceba47b72242e2c28bfb8bef3d2d88ec437e30a74d578457aa5651476de0f01fb3bcea36cf3f3d35321cc9dcb9bff8b01f9f6c99394729",
          "sha256": "c525d2cc94842ac46ea868856b0820a10777743011c55042068aaf7d4486a276",
          "sha1": "ce9f8fa6b2fe8cda0945fef5247ab51a6d50284c",
          "md5": "65f12cd32a84519109bd38e5a8d89f68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.2-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.2-sources.jar",
          "size": 19405,
          "sha512": "25777826d7fb35726114dab59a06856c36ccc5e761c0b85750bad892c4261fb078a2b8f0347f92e93a79be2640e36bd008fcd816f98242d2646aa292e5da9fc1",
          "sha256": "d53be9e363e05ac84e0944362092ff28d8a7419ebe26b0215daf4d63098f84fc",
          "sha1": "7e3e0f9c98510c1bc85d0a91a63f72ef32d0f7b6",
          "md5": "c26a72ed9a0542d45a631a68c5cf6601"
        }
      ]
    }
  ]
}
