{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.2.0.alpha.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.3+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.3+1.21.1.jar",
          "size": 178790,
          "sha512": "c8eac58863b6f1e2b0bbf9c09b2f3a02bf9dd3ab7e7f9217fbfae4827383546eefe2c0d194d2ec86e945c3d95fc782754d5fd4dbde623c6d06628f491f415650",
          "sha256": "f2696076d1aa860a6f6968867f2f956b08bf4ed6cdf81dbc54d2a22e217b2f5d",
          "sha1": "c26ecbcf3611cc052c75b086fd4efaa66ea15f23",
          "md5": "97a2f2952a67c4cdaca431491e271849"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.3+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.3+1.21.1.jar",
          "size": 178790,
          "sha512": "c8eac58863b6f1e2b0bbf9c09b2f3a02bf9dd3ab7e7f9217fbfae4827383546eefe2c0d194d2ec86e945c3d95fc782754d5fd4dbde623c6d06628f491f415650",
          "sha256": "f2696076d1aa860a6f6968867f2f956b08bf4ed6cdf81dbc54d2a22e217b2f5d",
          "sha1": "c26ecbcf3611cc052c75b086fd4efaa66ea15f23",
          "md5": "97a2f2952a67c4cdaca431491e271849"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.3+1.21.1-sources.jar",
          "url": "fidgetz-common-0.2.0.alpha.3+1.21.1-sources.jar",
          "size": 73099,
          "sha512": "cff283641a6b15952728a927bb3db2cb8d7e3094f618bae226c540663ed83999cca0d8bd803b279f64fc4ba18aa9e472cc810382808ca1b9394766fa29429a4a",
          "sha256": "d016370666469c5afc16760c2696c3772d4f45e74e85989de655042828f2363e",
          "sha1": "3a0e687d3d8badd5d49bfed268af04b0cab6a3c7",
          "md5": "79a3f886da1cc67615083198d90f5c42"
        }
      ]
    }
  ]
}
