{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.2+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.3.jar",
          "size": 33251,
          "sha512": "1acae98da18cb3a7cb974f48852a2ed48ecbccf34d4521034265e2b3d7e040605d64213237e0babc8f2b7cf93c9957194add00e01841beb136e7a550ea0212d3",
          "sha256": "beec2b9c0950cbed345f48b48b4c7b63ca9e40b0d2eb21985b25035aaf856fc5",
          "sha1": "d2b3abee7b3a1858e1f2cba20e984c45e8995b65",
          "md5": "c9a8c880519e5bfd797430e897e2ca42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.3.jar",
          "size": 33251,
          "sha512": "1acae98da18cb3a7cb974f48852a2ed48ecbccf34d4521034265e2b3d7e040605d64213237e0babc8f2b7cf93c9957194add00e01841beb136e7a550ea0212d3",
          "sha256": "beec2b9c0950cbed345f48b48b4c7b63ca9e40b0d2eb21985b25035aaf856fc5",
          "sha1": "d2b3abee7b3a1858e1f2cba20e984c45e8995b65",
          "md5": "c9a8c880519e5bfd797430e897e2ca42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+26.3-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+26.3-sources.jar",
          "size": 19405,
          "sha512": "25777826d7fb35726114dab59a06856c36ccc5e761c0b85750bad892c4261fb078a2b8f0347f92e93a79be2640e36bd008fcd816f98242d2646aa292e5da9fc1",
          "sha256": "d53be9e363e05ac84e0944362092ff28d8a7419ebe26b0215daf4d63098f84fc",
          "sha1": "7e3e0f9c98510c1bc85d0a91a63f72ef32d0f7b6",
          "md5": "c26a72ed9a0542d45a631a68c5cf6601"
        }
      ]
    }
  ]
}
