{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-common",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0+1.21.1.jar",
          "url": "packed_packs-common-2.1.0+1.21.1.jar",
          "size": 411665,
          "sha512": "01db06265db911fada13f904efe3ed26f3cee30bc09db79f6709b3108833d854086f55060990b7160df56c71f834da349d653eff9d82efb25b92cd0aad10f048",
          "sha256": "fc2ced3cc482e01dd94cd49c044b306fcbc856b01d991e290d1bcd5757945f0b",
          "sha1": "35afe15ec2da76e2497aea168e43f258af2df9fa",
          "md5": "dc154c8cc262f381cdb3130e4d159c04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0+1.21.1.jar",
          "url": "packed_packs-common-2.1.0+1.21.1.jar",
          "size": 411665,
          "sha512": "01db06265db911fada13f904efe3ed26f3cee30bc09db79f6709b3108833d854086f55060990b7160df56c71f834da349d653eff9d82efb25b92cd0aad10f048",
          "sha256": "fc2ced3cc482e01dd94cd49c044b306fcbc856b01d991e290d1bcd5757945f0b",
          "sha1": "35afe15ec2da76e2497aea168e43f258af2df9fa",
          "md5": "dc154c8cc262f381cdb3130e4d159c04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0+1.21.1-sources.jar",
          "size": 176202,
          "sha512": "71ceb7d0157d1acac6f41d396773ad565e3ce6349e94084adfbee488da0be688601e24dd6084c3efa0e523e896da98f883b54e19b7b10a8ca0677329f289366b",
          "sha256": "34d2feec691cef8efa19dc9b3dc61e8f488467e0e1faad857dc841e7040cbe61",
          "sha1": "64fb04178782296865184844613bc00891814535",
          "md5": "d2524415635fbe1df3f6aafcc4945d9e"
        }
      ]
    }
  ]
}
