{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.5.0-beta.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.5.0-beta.5+1.21.1.jar",
          "url": "fidgetz-fabric-0.5.0-beta.5+1.21.1.jar",
          "size": 318759,
          "sha512": "7864e8c1ce94d3d6096c28316d517ffff1a688332d4c27ea10cc07dc79b434e97809c4ef08e8d8982fe01252da7a74591fcf470e55d1ed5153c1e830e466a69e",
          "sha256": "70edca80cb9df57d8649318dd5271d67c3053df267c6f70f95ec45b11a3bc2eb",
          "sha1": "548ad8222f04e4200ac166ea4c3c8d692e0c2015",
          "md5": "637601e7e429e75a027ccaa22930f1e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.12+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.5.0-beta.5+1.21.1.jar",
          "url": "fidgetz-fabric-0.5.0-beta.5+1.21.1.jar",
          "size": 318759,
          "sha512": "7864e8c1ce94d3d6096c28316d517ffff1a688332d4c27ea10cc07dc79b434e97809c4ef08e8d8982fe01252da7a74591fcf470e55d1ed5153c1e830e466a69e",
          "sha256": "70edca80cb9df57d8649318dd5271d67c3053df267c6f70f95ec45b11a3bc2eb",
          "sha1": "548ad8222f04e4200ac166ea4c3c8d692e0c2015",
          "md5": "637601e7e429e75a027ccaa22930f1e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.5.0-beta.5+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.5.0-beta.5+1.21.1-sources.jar",
          "size": 122491,
          "sha512": "087fbfec6427f0fffdd2704b7d66883d4e21871e43473e425ca0490b530e9cb74bc6b199f7787adee30a6b689cfd6facb049c646c2785452e2c4465998839d48",
          "sha256": "5dd937f2044a7df135baf6417a953476a027b2f8772364f4d0cf0d0712f594ba",
          "sha1": "264806faac30c082b4099529be341d29b335650c",
          "md5": "5e2021d4daa08fa13340603d421af0ee"
        }
      ]
    }
  ]
}
