{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.0+1.21.11.jar",
          "size": 32019,
          "sha512": "570410a2a6e7bc43199aeb39821fec27678944f33c489d962d6f899d11c85e8c6fdf6cefbac435a79f0a794d554cdb1a2466bba106a1063142145f420a199cf9",
          "sha256": "766e8741f1ec768aa5a6e1d3bb58d179e0eedbb11525599aa13b57ca5f38f7cf",
          "sha1": "ff5207241e07cb3aae7e7b7e30c328cbb93781eb",
          "md5": "1129d54f500c0c898924372c34bd76f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.0+1.21.11.jar",
          "size": 32019,
          "sha512": "570410a2a6e7bc43199aeb39821fec27678944f33c489d962d6f899d11c85e8c6fdf6cefbac435a79f0a794d554cdb1a2466bba106a1063142145f420a199cf9",
          "sha256": "766e8741f1ec768aa5a6e1d3bb58d179e0eedbb11525599aa13b57ca5f38f7cf",
          "sha1": "ff5207241e07cb3aae7e7b7e30c328cbb93781eb",
          "md5": "1129d54f500c0c898924372c34bd76f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+1.21.11-sources.jar",
          "url": "packed_packs_api-common-2.3.0+1.21.11-sources.jar",
          "size": 19104,
          "sha512": "177b8f9b04e1f3305e71a8b6bbb419a37ac9f93c5d390616f5ddbac988a925333e62380bc12233e0bb0c29599eed92973733b1d373c6e01811dc5cd3d4252561",
          "sha256": "e614be08669613b42a4c6bd8e8cd1c865119a7d7253063aeb8d8367328eb028f",
          "sha1": "3e7fe8e7604c706722ea783de0c0ed1120e374ce",
          "md5": "2002aa8b573920cb5b7461e160c85338"
        }
      ]
    }
  ]
}
