{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.1+1.21.11.jar",
          "url": "packed_packs_api-neoforge-2.3.1+1.21.11.jar",
          "size": 32337,
          "sha512": "e0aa477bf2086c6e6cf3096c32c5b81d621f4ff6c905a16de8a7a8d8c36b184ddafeab8dac830994b529621f43fc466ae213b661339c9ccce17049f9d1b16341",
          "sha256": "9efdcafe36ade6d5e9eced12d452cfc87f7452372a5a374a0d60614eb0524eb0",
          "sha1": "026e9005900afc6d859c969019a059cd857cd7cd",
          "md5": "670b86c15b062df6c2daee4f69329bed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.1+1.21.11.jar",
          "url": "packed_packs_api-neoforge-2.3.1+1.21.11.jar",
          "size": 32337,
          "sha512": "e0aa477bf2086c6e6cf3096c32c5b81d621f4ff6c905a16de8a7a8d8c36b184ddafeab8dac830994b529621f43fc466ae213b661339c9ccce17049f9d1b16341",
          "sha256": "9efdcafe36ade6d5e9eced12d452cfc87f7452372a5a374a0d60614eb0524eb0",
          "sha1": "026e9005900afc6d859c969019a059cd857cd7cd",
          "md5": "670b86c15b062df6c2daee4f69329bed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.1+1.21.11-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.1+1.21.11-sources.jar",
          "size": 19415,
          "sha512": "a358f8ade3b46894dcfbf1efdaae5e75d5f6a3d98c06da739e5610d2724160b364220f35d02db4e49d4e367cb4a2eeeaa33509892da51f9e2b5337c61b51506b",
          "sha256": "ff217ac2acd259c10547d5046ab277c6461497cb23b7afe7c476c3c4a3473642",
          "sha1": "4482820cf97983954a741cda35885ee9883e2732",
          "md5": "2e3f1b97aa8b558dc4038d52ff0c7eb6"
        }
      ]
    }
  ]
}
