{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.3.0+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.0+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+26.2.jar",
          "url": "packed_packs-fabric-2.3.0+26.2.jar",
          "size": 1002703,
          "sha512": "438fbbdc3c575607d5c0ef5b2b740d7ad73a730f42cf5969c5cc2d6af80ecf16ee7344d9c6ed16d410d9492f617faee4f7d9bc3acf1fbdbf813446f4d6b2d26a",
          "sha256": "03d76e6c33057179e7e8b4c04dbcacd0b801a6278432380f80b1c321600453aa",
          "sha1": "e3be8b9a5d6963931dcae8fa9ace373528bd972e",
          "md5": "af3d693e85f0279ebdcbb02accdbb287"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.0+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+26.2.jar",
          "url": "packed_packs-fabric-2.3.0+26.2.jar",
          "size": 1002703,
          "sha512": "438fbbdc3c575607d5c0ef5b2b740d7ad73a730f42cf5969c5cc2d6af80ecf16ee7344d9c6ed16d410d9492f617faee4f7d9bc3acf1fbdbf813446f4d6b2d26a",
          "sha256": "03d76e6c33057179e7e8b4c04dbcacd0b801a6278432380f80b1c321600453aa",
          "sha1": "e3be8b9a5d6963931dcae8fa9ace373528bd972e",
          "md5": "af3d693e85f0279ebdcbb02accdbb287"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+26.2-sources.jar",
          "url": "packed_packs-fabric-2.3.0+26.2-sources.jar",
          "size": 204936,
          "sha512": "ec9706920ae457d6a8f420b4ca5c441707d524967d69843536127ffd2a6ed790b69fa3d7c2953fcfd184c34cf8b8c35278c2a677bebfc667045745d09cfaf7a5",
          "sha256": "4355c604ff33b858bc9233a8d4a954e4fb99f9013a38d12838cbbb5a8f7e878f",
          "sha1": "f108ab7e1550c0be6e14489114b2971f69272ee4",
          "md5": "e36c519c9bc3a1ddf0ac4849c7ded9a5"
        }
      ]
    }
  ]
}
