{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.11.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.11.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.1.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.1.jar",
          "size": 290141,
          "sha512": "ab790012ffc40ee0b8bb37b77568ed4c086c589414b1b80c9752e0a4edca5dd6f14f32b33a24808abd028958900b003adad5cb1f38f419e2927eb611b7c78ee4",
          "sha256": "e1fec098546773beea6dc6676ee29b2cc988649e57144042d30db84e03e924b8",
          "sha1": "e1fc741c578e26aaa7fafed3220f81066f0068bc",
          "md5": "e9ed8b451a81f901ee6f7f201e50a329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.11.2+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.1.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.1.jar",
          "size": 290141,
          "sha512": "ab790012ffc40ee0b8bb37b77568ed4c086c589414b1b80c9752e0a4edca5dd6f14f32b33a24808abd028958900b003adad5cb1f38f419e2927eb611b7c78ee4",
          "sha256": "e1fec098546773beea6dc6676ee29b2cc988649e57144042d30db84e03e924b8",
          "sha1": "e1fc741c578e26aaa7fafed3220f81066f0068bc",
          "md5": "e9ed8b451a81f901ee6f7f201e50a329"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.1-sources.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.1-sources.jar",
          "size": 147988,
          "sha512": "a10c002054a3193d1942834d6dc4f0b379ca072e273f2ac25c48122da10614ddb43b063dedfe0610429b9f9ca530fc374de3bbc321dd9634ba18e68cb8fb6277",
          "sha256": "ec553a74a6648df2fb5e70cdd33c3d78d7573bb5e50d0df0fab69a9125eb2284",
          "sha1": "9edeefeca49e32e6b39fee7cc10edb1f99533531",
          "md5": "43001ffd0b258b94ef6c59b781b1f3c8"
        }
      ]
    }
  ]
}
