{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.3+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.3+26.2.jar",
          "size": 34071,
          "sha512": "fc6f709bf243de49005a9518e6d851195769fa7d11076c83c4c5ecd51ab87380db0771efd1edfea31dd0061b894a0d6f3bd2ba04e05d9633af87069c7d5701ef",
          "sha256": "a390b3fe88a09ee5e7454a84b8c1562ca2d9358cf34aab16f40d3670189e02cc",
          "sha1": "0e237ea1ebd96a3c981980863223e572f1b9c831",
          "md5": "cd0c6068a1ce1873f53c30ac7ff0d291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.3+26.2.jar",
          "size": 34071,
          "sha512": "fc6f709bf243de49005a9518e6d851195769fa7d11076c83c4c5ecd51ab87380db0771efd1edfea31dd0061b894a0d6f3bd2ba04e05d9633af87069c7d5701ef",
          "sha256": "a390b3fe88a09ee5e7454a84b8c1562ca2d9358cf34aab16f40d3670189e02cc",
          "sha1": "0e237ea1ebd96a3c981980863223e572f1b9c831",
          "md5": "cd0c6068a1ce1873f53c30ac7ff0d291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+26.2-sources.jar",
          "url": "packed_packs_api-fabric-2.2.3+26.2-sources.jar",
          "size": 19307,
          "sha512": "16a919818866407db45f5baa140d7db7a462073ec695ec299490d3247f7aeb61f6759834ddf8ddc84dcb77f3d3aff7554fb26acf109517953ea5f02d09203098",
          "sha256": "26aa97b2b7790f7bfec290f76c6576c239e0ee0df8d9b3829313f8777faa7db7",
          "sha1": "0ef74ce15932b206f0dc88065857681050d2d8fd",
          "md5": "d3778e44064a4e0e9fe5b9fc0cd37c05"
        }
      ]
    }
  ]
}
