{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.9.0+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.2.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.2.jar",
          "size": 11193,
          "sha512": "fe8330f239ef85a753a0f2c319d485ab65eb4f57d9ec9a864f94cae263c33578886faf561382a51dea5b9454a78ff9d080b384c2359e8a90f0e38a5c9b9c4567",
          "sha256": "bfd082fbb548452b9e9775ec8754d086ebb714200d8e8122b39cb06f5a9eb071",
          "sha1": "6451a50110fb988854dac6cf6eea1ef9b9f1358e",
          "md5": "b50be4f965df01acf3c9ada55dd6003f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.2.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.2.jar",
          "size": 11193,
          "sha512": "fe8330f239ef85a753a0f2c319d485ab65eb4f57d9ec9a864f94cae263c33578886faf561382a51dea5b9454a78ff9d080b384c2359e8a90f0e38a5c9b9c4567",
          "sha256": "bfd082fbb548452b9e9775ec8754d086ebb714200d8e8122b39cb06f5a9eb071",
          "sha1": "6451a50110fb988854dac6cf6eea1ef9b9f1358e",
          "md5": "b50be4f965df01acf3c9ada55dd6003f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.2-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.2-sources.jar",
          "size": 10501,
          "sha512": "a6590e2bcd7e12f6cc04d97adeaa6576bacc97ccd860822f12c77ab94e52c7a877a5735ea09cc952ff2d4a9a6639e674603450144bb6c3f971c4d682d581aaec",
          "sha256": "1b0390b8996e77881c6b83b889d4295b96ee4c1b8870d9431175e2d66733683b",
          "sha1": "ac1355c5a4ebae786419990c2189f3908ed69659",
          "md5": "7a663aee2d797f7c269cbc5d7cb5643d"
        }
      ]
    }
  ]
}
