{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.2+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11.jar",
          "size": 33288,
          "sha512": "a31079bcfc5d85df858163d5c1aeed7e732a43348be40bb66f7f6420d2c1694b5dca13e63c276ec43618e3a555f18767a098542394d55f9fc9e1841e0ce2bea3",
          "sha256": "8f83fa5e92833385aa842e9d9c0da7e61d7975ad8720544af8ac85d10239c33e",
          "sha1": "b64f120bd3d5135daec5b84d07c7ef02fa496246",
          "md5": "afeab5bf0123d8cb8c4099e89238e84c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11.jar",
          "size": 33288,
          "sha512": "a31079bcfc5d85df858163d5c1aeed7e732a43348be40bb66f7f6420d2c1694b5dca13e63c276ec43618e3a555f18767a098542394d55f9fc9e1841e0ce2bea3",
          "sha256": "8f83fa5e92833385aa842e9d9c0da7e61d7975ad8720544af8ac85d10239c33e",
          "sha1": "b64f120bd3d5135daec5b84d07c7ef02fa496246",
          "md5": "afeab5bf0123d8cb8c4099e89238e84c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.2+1.21.11-sources.jar",
          "size": 19927,
          "sha512": "1ab59a0594d47841c316de5e98cbbd60d290ac4cf342ef984742571d89fd958dfc660df8b394f4c8da07e8b65dbd31a74cd6faadf40b680f0aa5d7799c384211",
          "sha256": "303b96e32e17782c11b9184e7523d562b9b4391ead1e78099990aff3a48cf7b0",
          "sha1": "d05fc8ad24d87e83c31fa416f78a37a80e290f8e",
          "md5": "f895ae2f4eca407c7e0c13a0533f4002"
        }
      ]
    }
  ]
}
