{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.3+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.2.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.2.jar",
          "size": 34238,
          "sha512": "30f78cbc8045ada62a204c9b12753fc2ff8b6a0d31e2da2c0b0214d57c57189cc5d55548cfead0d0a7f6a6dc4f41cdfc234ccd2ee0f0ccb329a032f3c827719c",
          "sha256": "18e3b282a00bbe2257e994a816cb9b5bd21ff5c8d0e8d259996d7838876eb8d7",
          "sha1": "38f94ba7238818a728b726dc08ef56952986c0b2",
          "md5": "41c4efaef5ca6df4ac0ac441b5e4128f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.2.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.2.jar",
          "size": 34238,
          "sha512": "30f78cbc8045ada62a204c9b12753fc2ff8b6a0d31e2da2c0b0214d57c57189cc5d55548cfead0d0a7f6a6dc4f41cdfc234ccd2ee0f0ccb329a032f3c827719c",
          "sha256": "18e3b282a00bbe2257e994a816cb9b5bd21ff5c8d0e8d259996d7838876eb8d7",
          "sha1": "38f94ba7238818a728b726dc08ef56952986c0b2",
          "md5": "41c4efaef5ca6df4ac0ac441b5e4128f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.2-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.2-sources.jar",
          "size": 19405,
          "sha512": "25777826d7fb35726114dab59a06856c36ccc5e761c0b85750bad892c4261fb078a2b8f0347f92e93a79be2640e36bd008fcd816f98242d2646aa292e5da9fc1",
          "sha256": "d53be9e363e05ac84e0944362092ff28d8a7419ebe26b0215daf4d63098f84fc",
          "sha1": "7e3e0f9c98510c1bc85d0a91a63f72ef32d0f7b6",
          "md5": "c26a72ed9a0542d45a631a68c5cf6601"
        }
      ]
    }
  ]
}
