{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.3+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.3+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.3+1.21.1.jar",
          "size": 675799,
          "sha512": "7c9210b1c2bec85bdeb7b0dea750db4dd21f53fb7a5ee66c5e5ae2deb1167f012b8b44b679fa2908788bbc4f7a074261c369b43dd3ec62f1ed9e32219a0b24c0",
          "sha256": "32e1330619f01e3e839b4a12b89aa850fa738c1578292dbeb301795361a5f3f5",
          "sha1": "f8b42e565fff0e1c70c102ed76bb0cb12cf4c202",
          "md5": "90f6c9a952ca60b19c3b0548f82e01eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.3+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.3+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.3+1.21.1.jar",
          "size": 675799,
          "sha512": "7c9210b1c2bec85bdeb7b0dea750db4dd21f53fb7a5ee66c5e5ae2deb1167f012b8b44b679fa2908788bbc4f7a074261c369b43dd3ec62f1ed9e32219a0b24c0",
          "sha256": "32e1330619f01e3e839b4a12b89aa850fa738c1578292dbeb301795361a5f3f5",
          "sha1": "f8b42e565fff0e1c70c102ed76bb0cb12cf4c202",
          "md5": "90f6c9a952ca60b19c3b0548f82e01eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.3+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.3+1.21.1-sources.jar",
          "size": 202460,
          "sha512": "3c44da7df4d823ca28f6b608898dc47f2a5d4908e3d47e0b29f410864a4e61dc89fd562f2b942bd0444ee753348b7a5bef0de4dfcb19f402d10caf1604741cf2",
          "sha256": "01e39e02ef30e001e7e4eeaf6449280e9ba26bf11498e9dc61901b11cc7fc262",
          "sha1": "d41fd2568a7f658a09556a77b5823cfe6d2d16c1",
          "md5": "7b235481205679a71bb0f5f16f0d494d"
        }
      ]
    }
  ]
}
