{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.2.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.1+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.2.1+1.21.1.jar",
          "size": 32348,
          "sha512": "a360e4544534d07cc9a827d01d8b3955abe8517038621eb71fe3c338c28d0983c9e40d76e38a660df1f22de92a1985442c9181321c3970c0c7efe853b4b4bec7",
          "sha256": "844cba342d486713eedead35382d34388bebf42a71762af779fe7eea8c9cb23b",
          "sha1": "6684847f70659c9a9b30b732e00bf429397ead54",
          "md5": "0421927f13123e1f44bb0bc19d6bf67b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.1+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.2.1+1.21.1.jar",
          "size": 32348,
          "sha512": "a360e4544534d07cc9a827d01d8b3955abe8517038621eb71fe3c338c28d0983c9e40d76e38a660df1f22de92a1985442c9181321c3970c0c7efe853b4b4bec7",
          "sha256": "844cba342d486713eedead35382d34388bebf42a71762af779fe7eea8c9cb23b",
          "sha1": "6684847f70659c9a9b30b732e00bf429397ead54",
          "md5": "0421927f13123e1f44bb0bc19d6bf67b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.1+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.2.1+1.21.1-sources.jar",
          "size": 19462,
          "sha512": "f24cb08ca9cffb0924d02ea31854e3dd7f23577e5a1990c758daebf5677318243e277f738abdd14e8d8234e9c19036a5119830cac9063610c994363771fbc60d",
          "sha256": "f907592f48f176fcfc0095e79eded23fa49eaa251840bf0b290bab4860959561",
          "sha1": "a7646a7c4ebd679ec0b6591986da2cda0e41951a",
          "md5": "5ecec4626caeb871a681e6dbf74fb2aa"
        }
      ]
    }
  ]
}
