{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-neoforge",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575221,
          "sha512": "c410c39d26d90540fa969c110e9a6c6a78daf8efdb26caa154b60656da802e3ea17f4837f25f7933b23bb98b9dc08a1019d19d0c245d507a58355b8e0a6d9d63",
          "sha256": "af33d36852078da4af519f03272433459d2436bddb5d8e64392e2982dabcae1a",
          "sha1": "f77db035a6ebb0c9ce4826aa4ca47ffa093d287e",
          "md5": "a769b45b5c5d315133910aeac9867599"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575221,
          "sha512": "c410c39d26d90540fa969c110e9a6c6a78daf8efdb26caa154b60656da802e3ea17f4837f25f7933b23bb98b9dc08a1019d19d0c245d507a58355b8e0a6d9d63",
          "sha256": "af33d36852078da4af519f03272433459d2436bddb5d8e64392e2982dabcae1a",
          "sha1": "f77db035a6ebb0c9ce4826aa4ca47ffa093d287e",
          "md5": "a769b45b5c5d315133910aeac9867599"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "size": 178895,
          "sha512": "38652aa2adf2cf0b62519cb8e9a3bfc866d19284181e72cf6d69f413014ca2f06cb7764d2859645de8feb4624c0b7a1d0e2f8bfb3e61dd44eedf3b0e21378be2",
          "sha256": "f06628db46a51e93e7dbc983e5ff1be4a8c796739a79e5ae00fd8dc9bd6b0589",
          "sha1": "a528cd54014d82784bbb238643efc8bcae5111f4",
          "md5": "37cccf363f6cfb509636b839a5c40904"
        }
      ]
    }
  ]
}
