{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-neoforge",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575276,
          "sha512": "dba2733d5adfe64b97058200c5907d6a17a82572a143e044e27eb9590d3f8b4e88703e554be53a2166aa788ffead638d9f8cdc0e041a060510c74570b61a6e69",
          "sha256": "a7a0f8753ff75a020444ed89fa4098a893f45469ee845ee6538d3f2470ab2315",
          "sha1": "38b195ecd5a0142d840551a34850e8cbdc14d8ae",
          "md5": "485487778bcba7b76cfc8432e056d782"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575276,
          "sha512": "dba2733d5adfe64b97058200c5907d6a17a82572a143e044e27eb9590d3f8b4e88703e554be53a2166aa788ffead638d9f8cdc0e041a060510c74570b61a6e69",
          "sha256": "a7a0f8753ff75a020444ed89fa4098a893f45469ee845ee6538d3f2470ab2315",
          "sha1": "38b195ecd5a0142d840551a34850e8cbdc14d8ae",
          "md5": "485487778bcba7b76cfc8432e056d782"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "size": 178865,
          "sha512": "dd8edfac293b04eb313031cf20fd3d6f47a4f71382883056f1184281fb9ca4b347f05f1b579a849869fffc6d3a82f05b77fe500667ef9f774acbc2df2ed4158c",
          "sha256": "d18c35a0526e8a3c5d2e1887a7f2e049d5e2e8bd02d19efca27d6c8aefb9082d",
          "sha1": "6794846f6121d5375ce9dca64ad31b1aba1c281d",
          "md5": "04dd95fee98552fffe3481558325dd9e"
        }
      ]
    }
  ]
}
