{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-neoforge",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575240,
          "sha512": "e232d4caf840dbdbf618564c9748ae5c5eee076bca536d7c8ef20e50c6845327c7b1071c8653814f0cafbd0e1172f2bdcbce4c0f9743026584f87600a04c4e62",
          "sha256": "d9417305c98b0f0b2abad9e0a24bf4c5279341fa7d8b60fc60b370e94c0088ab",
          "sha1": "3b315697e4269d4589993fc9499f30560f00b61e",
          "md5": "18d2848469b2a01781a4d819d09c82f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1.jar",
          "size": 575240,
          "sha512": "e232d4caf840dbdbf618564c9748ae5c5eee076bca536d7c8ef20e50c6845327c7b1071c8653814f0cafbd0e1172f2bdcbce4c0f9743026584f87600a04c4e62",
          "sha256": "d9417305c98b0f0b2abad9e0a24bf4c5279341fa7d8b60fc60b370e94c0088ab",
          "sha1": "3b315697e4269d4589993fc9499f30560f00b61e",
          "md5": "18d2848469b2a01781a4d819d09c82f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0+1.21.1-sources.jar",
          "size": 178865,
          "sha512": "85f2b2e13a782db816902ea546122a28bbbb50ddb399704aad9a7758e3517cbb24895231b78549b2dd7773f2296c96b6a3f56173e98a40e8d9a1d7864425022a",
          "sha256": "6733ab46356cf0c2f4ae9ce4de1b4ac113b2852c8881c3766754024225817b4b",
          "sha1": "0dfa32c4af3e5061a59f23fb8cbd7cf472e78ccf",
          "md5": "0a81cd6e56741f0b9c25b8eac8e57d05"
        }
      ]
    }
  ]
}
