{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.1+1.21.11.jar",
          "size": 32019,
          "sha512": "b974b4e9b8ee22969159adc6b328864be8a80dabeb73a7de14e5c1f96209aabb211a9e58134b8c8e838ac929be117265a2aa3f2cb46333bfc6564af8acf0dd7d",
          "sha256": "0594dfa4bea44006d7602f6e2f04ba5e74f31c89755f34b55031cc4e50995047",
          "sha1": "54068a3b29cdb5f205f40ed06cd87ebdebc640dd",
          "md5": "8f06bdac83bea429d4f9f2317aa8447c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.1+1.21.11.jar",
          "size": 32019,
          "sha512": "b974b4e9b8ee22969159adc6b328864be8a80dabeb73a7de14e5c1f96209aabb211a9e58134b8c8e838ac929be117265a2aa3f2cb46333bfc6564af8acf0dd7d",
          "sha256": "0594dfa4bea44006d7602f6e2f04ba5e74f31c89755f34b55031cc4e50995047",
          "sha1": "54068a3b29cdb5f205f40ed06cd87ebdebc640dd",
          "md5": "8f06bdac83bea429d4f9f2317aa8447c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+1.21.11-sources.jar",
          "url": "packed_packs_api-common-2.3.1+1.21.11-sources.jar",
          "size": 19104,
          "sha512": "177b8f9b04e1f3305e71a8b6bbb419a37ac9f93c5d390616f5ddbac988a925333e62380bc12233e0bb0c29599eed92973733b1d373c6e01811dc5cd3d4252561",
          "sha256": "e614be08669613b42a4c6bd8e8cd1c865119a7d7253063aeb8d8367328eb028f",
          "sha1": "3e7fe8e7604c706722ea783de0c0ed1120e374ce",
          "md5": "2002aa8b573920cb5b7461e160c85338"
        }
      ]
    }
  ]
}
