{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor",
    "version": "3.5.0+1.21-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-api",
          "version": {
            "requires": "3.5.0+1.21-1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-3.5.0+1.21-1.21.1.jar",
          "url": "minecraft-cursor-3.5.0+1.21-1.21.1.jar",
          "size": 178911,
          "sha512": "644545fe8b60511ac414d4f5f6a39c2d83abb4582abf08e3b264f83feee8cfbd84d98ea60b62059fc2e1353fef76a5b040cd583ff958518035ffa99dd409a353",
          "sha256": "65c1392da2b169f5da4a0691afc5da8d60e360572f63ee417f42d1613be8e7dc",
          "sha1": "7ad4ac741a252dbd93120a8339194bac9d8d1025",
          "md5": "274774c86ca80e3258fcc91c24a92af1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-api",
          "version": {
            "requires": "3.5.0+1.21-1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "11.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-3.5.0+1.21-1.21.1.jar",
          "url": "minecraft-cursor-3.5.0+1.21-1.21.1.jar",
          "size": 178911,
          "sha512": "644545fe8b60511ac414d4f5f6a39c2d83abb4582abf08e3b264f83feee8cfbd84d98ea60b62059fc2e1353fef76a5b040cd583ff958518035ffa99dd409a353",
          "sha256": "65c1392da2b169f5da4a0691afc5da8d60e360572f63ee417f42d1613be8e7dc",
          "sha1": "7ad4ac741a252dbd93120a8339194bac9d8d1025",
          "md5": "274774c86ca80e3258fcc91c24a92af1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-3.5.0+1.21-1.21.1-sources.jar",
          "url": "minecraft-cursor-3.5.0+1.21-1.21.1-sources.jar",
          "size": 89816,
          "sha512": "7d82ffa8a213b7c9b3e44c9d7c1b13447ed17fcaae349e11367d7b554533ed0b7f69197e6c825eb1b21000ffcf475e554d1524bfd1faf9b2c3469b155f579f4e",
          "sha256": "3dacc425948a77507095f60be72933e4ca4e49f6041fac23de104f7456ab025a",
          "sha1": "320b6c39ce568fdcddab43d52e87ef5e30b386b7",
          "md5": "89b4ef0eb9278c4227b5dd9c3e24560f"
        }
      ]
    }
  ]
}
