{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.2.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.0+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.5.2+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+26.1.jar",
          "url": "packed_packs-neoforge-2.2.0+26.1.jar",
          "size": 779613,
          "sha512": "94357a9a124235c5738b999d22b67dd10cdbee06e83fdcc27b556521b0ef95da964804be30ac300989c64eb6e4b3bd68f71c316fe2859716aa4c6641b749f948",
          "sha256": "a68129411463f31331fcb38d6af428689d5dba894d20e01b047f468c2eff92a5",
          "sha1": "f88d1c6c558a4483c100035853feb5eede4956f6",
          "md5": "ec6939a992a2d4e51c4383fb73b7a2c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.0+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.5.2+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+26.1.jar",
          "url": "packed_packs-neoforge-2.2.0+26.1.jar",
          "size": 779613,
          "sha512": "94357a9a124235c5738b999d22b67dd10cdbee06e83fdcc27b556521b0ef95da964804be30ac300989c64eb6e4b3bd68f71c316fe2859716aa4c6641b749f948",
          "sha256": "a68129411463f31331fcb38d6af428689d5dba894d20e01b047f468c2eff92a5",
          "sha1": "f88d1c6c558a4483c100035853feb5eede4956f6",
          "md5": "ec6939a992a2d4e51c4383fb73b7a2c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+26.1-sources.jar",
          "url": "packed_packs-neoforge-2.2.0+26.1-sources.jar",
          "size": 180520,
          "sha512": "0a73cf354243bf744be20cfbfe7d8358c5301fa15f3e3a9571106090cbe7d1b128f960ea5a5b5eece086302dd6de6917cc36da8e20788c01adc466d2ba261b01",
          "sha256": "083f6e3c573d9784ac46b09213ea2e07ad5a948540d388c945a97120303afee8",
          "sha1": "7782c9dbfeeba92703755d96a44eb7cce0e3af17",
          "md5": "85b042337a461a9d939f31d18a92377c"
        }
      ]
    }
  ]
}
