{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "size": 654482,
          "sha512": "bf858d2e5c1f0dfe6893c702cb90fbceb391e21172c3a04b689f23fa36d291a225bfc3c787bad95cc067edf543700cec4a6bbcf3f12e48d2f5fcb639373d6f68",
          "sha256": "10bbeb130c4424d59ac3cadf3d1f6859808c306214913551a9c720b1af1967fb",
          "sha1": "e4816e44a6d244e920d25ced3b1b91bc5a30bcd5",
          "md5": "60bbe9e1b324400ab4b679479cc4a039"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "size": 654482,
          "sha512": "bf858d2e5c1f0dfe6893c702cb90fbceb391e21172c3a04b689f23fa36d291a225bfc3c787bad95cc067edf543700cec4a6bbcf3f12e48d2f5fcb639373d6f68",
          "sha256": "10bbeb130c4424d59ac3cadf3d1f6859808c306214913551a9c720b1af1967fb",
          "sha1": "e4816e44a6d244e920d25ced3b1b91bc5a30bcd5",
          "md5": "60bbe9e1b324400ab4b679479cc4a039"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.2+1.21.1-sources.jar",
          "size": 178123,
          "sha512": "5d9546312c7c8fac2b7a805e26b76e49b39326fb8bbfbe064b13f49a3ab352982aa32da0e19cbcafaa5bb047dccefa395f1aff130da1f31553c8ea7e0d62f3dd",
          "sha256": "39befbeeba234c2db3088bcc686f6c111b6eb48a613e27bbb6e49f813ad507c6",
          "sha1": "cf5cb70b96d5f314acd4166506c9021bf1f25e15",
          "md5": "c3e5a559e7145c6f81f4336568b228a9"
        }
      ]
    }
  ]
}
