{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.8+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.8+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.8+1.21.1.jar",
          "size": 675648,
          "sha512": "41188ad31fdfc2d14901cef5fc1cb31022b1e92580de714d00254162da6df1b25fe5055777ddc723f813041e34a116250af596e76415063b7a055b487b90347b",
          "sha256": "775792b04650052b638e1e739c9cc7b8e21667e4dddf0cfcb0d3be40f34ffae3",
          "sha1": "4e011b0aeea0b5cf7b7f10560fbc71814c2efcf4",
          "md5": "82d72f760353d1c0c4718cfd5e00f369"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.8+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.8+1.21.1.jar",
          "size": 675648,
          "sha512": "41188ad31fdfc2d14901cef5fc1cb31022b1e92580de714d00254162da6df1b25fe5055777ddc723f813041e34a116250af596e76415063b7a055b487b90347b",
          "sha256": "775792b04650052b638e1e739c9cc7b8e21667e4dddf0cfcb0d3be40f34ffae3",
          "sha1": "4e011b0aeea0b5cf7b7f10560fbc71814c2efcf4",
          "md5": "82d72f760353d1c0c4718cfd5e00f369"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.8+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.8+1.21.1-sources.jar",
          "size": 202511,
          "sha512": "beb6d264a54528775e00c71c22b6c99dcfc218f972dc5ba80ce6367f3f0d77fdf0a12179952477f0074d6789e3540575e19f266c38374c3fa01c8920dcf550c0",
          "sha256": "cca7d20a81e71c5a988614b6697b6c661cb298477a6993417defe7e21f9505e3",
          "sha1": "a02eede80800ffe8b27ae35e053d85ae3452054a",
          "md5": "e0cdbc868e0d08f3eaf54d9653ba21c3"
        }
      ]
    }
  ]
}
