{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.9.2+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.2+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.9.2+1.21.4.jar",
          "size": 13478,
          "sha512": "c13d58ecbe85ec307ebd1b695d439e938349eca28dcf3bb383cdee62782bd1769bdcc71df89fecc5f045a150158f5daca6858f58473460cecff3fd34958d9716",
          "sha256": "7c4751c8cd183db5adb85988a2b52d787a61444304394c68f2f7a97c6998a1c3",
          "sha1": "9efe5b0d697aad0435752427fa18c6e945ba97a0",
          "md5": "2da50dd1da528bd0bc69c34e8d59944b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.2+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.9.2+1.21.4.jar",
          "size": 13478,
          "sha512": "c13d58ecbe85ec307ebd1b695d439e938349eca28dcf3bb383cdee62782bd1769bdcc71df89fecc5f045a150158f5daca6858f58473460cecff3fd34958d9716",
          "sha256": "7c4751c8cd183db5adb85988a2b52d787a61444304394c68f2f7a97c6998a1c3",
          "sha1": "9efe5b0d697aad0435752427fa18c6e945ba97a0",
          "md5": "2da50dd1da528bd0bc69c34e8d59944b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.2+1.21.4-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.9.2+1.21.4-sources.jar",
          "size": 10796,
          "sha512": "91c9271f73608d12f4474d8deaafd9ad16336294825a39163d592a808a5796d71f2592bb44ccba209ce95deb96eeddf8b2d51f7debb71237969800cecfd29971",
          "sha256": "d20fd0663ffb2624a2dd7ce8e8c408e2ea97e9a95b017e724ecb75fbb14ffb99",
          "sha1": "d44aec477eecd7bf103c067a67718aa9f08922e5",
          "md5": "2fe4cca13470646b1f3630b49acaabd9"
        }
      ]
    }
  ]
}
