{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0-beta.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11.jar",
          "size": 32348,
          "sha512": "422c7e549c7de433ef84cabb72c14ad316aec58435bf8a56b9b382312c2b1c1402bc4b86a34618616b0ac4cf9b2baaa44f21362c01f6761ea814dc5ab69692b4",
          "sha256": "cd9b05e0a81d76315bd95386c34ff1f0407a891848da987b7b8ef687b6f8fc08",
          "sha1": "285ea7e365e1b92ae5ca0d433da9a33a57f77ebc",
          "md5": "87c8f438ec3379921c930c91b21b085c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11.jar",
          "size": 32348,
          "sha512": "422c7e549c7de433ef84cabb72c14ad316aec58435bf8a56b9b382312c2b1c1402bc4b86a34618616b0ac4cf9b2baaa44f21362c01f6761ea814dc5ab69692b4",
          "sha256": "cd9b05e0a81d76315bd95386c34ff1f0407a891848da987b7b8ef687b6f8fc08",
          "sha1": "285ea7e365e1b92ae5ca0d433da9a33a57f77ebc",
          "md5": "87c8f438ec3379921c930c91b21b085c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+1.21.11-sources.jar",
          "size": 19415,
          "sha512": "a358f8ade3b46894dcfbf1efdaae5e75d5f6a3d98c06da739e5610d2724160b364220f35d02db4e49d4e367cb4a2eeeaa33509892da51f9e2b5337c61b51506b",
          "sha256": "ff217ac2acd259c10547d5046ab277c6461497cb23b7afe7c476c3c4a3473642",
          "sha1": "4482820cf97983954a741cda35885ee9883e2732",
          "md5": "2e3f1b97aa8b558dc4038d52ff0c7eb6"
        }
      ]
    }
  ]
}
