{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.2.5+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.5+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.1+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.5+26.1.jar",
          "url": "packed_packs-neoforge-2.2.5+26.1.jar",
          "size": 902517,
          "sha512": "f8ac93ae2d470c6c1f891bc8c718b7ff7416c4023b8e2af3cfc8b46dba52270db4085782ebc3fc5aca4a8ff2601a0d4b2cf812324fee5f9d861ff0fa5d059916",
          "sha256": "5d4a8fbe13b630b5ec568cabceea3a5d949144ddb2988959c627802d8b881336",
          "sha1": "3d385ec441493a9e9e0b3e4338d73cad05f21af4",
          "md5": "2f1a9d02710dfe237dabe19bc1e73a67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.5+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.1+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.5+26.1.jar",
          "url": "packed_packs-neoforge-2.2.5+26.1.jar",
          "size": 902517,
          "sha512": "f8ac93ae2d470c6c1f891bc8c718b7ff7416c4023b8e2af3cfc8b46dba52270db4085782ebc3fc5aca4a8ff2601a0d4b2cf812324fee5f9d861ff0fa5d059916",
          "sha256": "5d4a8fbe13b630b5ec568cabceea3a5d949144ddb2988959c627802d8b881336",
          "sha1": "3d385ec441493a9e9e0b3e4338d73cad05f21af4",
          "md5": "2f1a9d02710dfe237dabe19bc1e73a67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.5+26.1-sources.jar",
          "url": "packed_packs-neoforge-2.2.5+26.1-sources.jar",
          "size": 182805,
          "sha512": "ca7e02f645a0826d0a60561e71f327a96e5fbaccdc78301b4beaed55eb7dfab1181a3eebdfe675e8a6947d5edd946aad524e6d8d8e43e29a6a68dcf443678b0b",
          "sha256": "50d4b9eb15f9b7330b84caf194d46a16fb78d28cdc8deac9aa360767da42e160",
          "sha1": "68f071c2de1bc0804d3bdbbfdcf656f210e5f1fe",
          "md5": "3f84ba3a58f2ed947e019d12867c8f5c"
        }
      ]
    }
  ]
}
