{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.2.0.alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.2+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.2+1.21.1.jar",
          "size": 178783,
          "sha512": "042288cf18e52ea1daac47030bf02c6f1487b2ba8642d9aef58269952c7e82bf67a52890a8bc65c623bf897ffe829826722866bfe1403d0268119dfa1632362e",
          "sha256": "a6856348957e93a353f3b41ec46a9d08851dfcb2b891c8d901e6972f072200a4",
          "sha1": "2c3425fd63ba6ea181513b65c3f2c47ddf558585",
          "md5": "0d5674f94b5cb053ebe995a035cf14f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.2+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.2+1.21.1.jar",
          "size": 178783,
          "sha512": "042288cf18e52ea1daac47030bf02c6f1487b2ba8642d9aef58269952c7e82bf67a52890a8bc65c623bf897ffe829826722866bfe1403d0268119dfa1632362e",
          "sha256": "a6856348957e93a353f3b41ec46a9d08851dfcb2b891c8d901e6972f072200a4",
          "sha1": "2c3425fd63ba6ea181513b65c3f2c47ddf558585",
          "md5": "0d5674f94b5cb053ebe995a035cf14f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.2+1.21.1-sources.jar",
          "url": "fidgetz-common-0.2.0.alpha.2+1.21.1-sources.jar",
          "size": 73081,
          "sha512": "1110c5817c81e60824a30e014e28f5fa3c32336f4f8a52b6bc0c69945ab639305149dbd1be59f19ee12e39d89ba6c04d797cd77c381917c89ca48def507301e8",
          "sha256": "c027658bab3566efd1d03c4ab0b84e5d8962f5fde0ea9de3186d3b958a7d09d6",
          "sha1": "8e0ff1b816916b9d7fbe669bea52f36e24369e37",
          "md5": "61551fb980d14f71babb665b69ce90de"
        }
      ]
    }
  ]
}
