{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.2.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0+26.1.jar",
          "url": "fidgetz-fabric-0.2.0+26.1.jar",
          "size": 181661,
          "sha512": "e681bedd17821a9a1e3c2310dab5de62a02d7ebbbea1ac61d4423da1745946e7a46b823f02fdde77d562e3f604e155d1d3f626f040956aa2cbb6773bd9790759",
          "sha256": "eb329f0e03c3e4a272d926d240bfd80625357034144e56d457cdd3b722c20cc7",
          "sha1": "7b5e503a20213cd5deccf6ab1bf5fadff0e97cf2",
          "md5": "de0a1c30f251c5851bebcdaf40ecb30a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.143.15+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0+26.1.jar",
          "url": "fidgetz-fabric-0.2.0+26.1.jar",
          "size": 181661,
          "sha512": "e681bedd17821a9a1e3c2310dab5de62a02d7ebbbea1ac61d4423da1745946e7a46b823f02fdde77d562e3f604e155d1d3f626f040956aa2cbb6773bd9790759",
          "sha256": "eb329f0e03c3e4a272d926d240bfd80625357034144e56d457cdd3b722c20cc7",
          "sha1": "7b5e503a20213cd5deccf6ab1bf5fadff0e97cf2",
          "md5": "de0a1c30f251c5851bebcdaf40ecb30a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0+26.1-sources.jar",
          "url": "fidgetz-fabric-0.2.0+26.1-sources.jar",
          "size": 73015,
          "sha512": "7f07401670aff7ea5bfcfc385d524995b1104712cc781d2fe5dfd874c0a51acc9d60bf2d46339a1bb5b9f573d3c7bd7f01fe4c4f172fbeeadea33cd199098f44",
          "sha256": "f8b314726530b7d30ab41fd3062a4daa466cd1d9be6447c95b6b785daacafa80",
          "sha1": "60b6d6cb033852b47ff9f78badc33638ab26f014",
          "md5": "62837db22465e2ac6b38e1784a74814a"
        }
      ]
    }
  ]
}
