{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.5+1.21.1.jar",
          "size": 26479,
          "sha512": "57a8d0b222a0e1cc76016e3a74a45fb6c24172c605f7499cba4b3cc9b084d1844c3f0312e7cc5da53c1f5699026cd9e6ae2681080603deb7f6782b98b5090b53",
          "sha256": "898b28c735be7a2f0569d15d4308a1c88d45b4329c8a2ec5ced9640136dedc24",
          "sha1": "fca57ed1fafd2f107a685901d80029f1046cb500",
          "md5": "cc8ba1ca45f43cd550b59903c46cc171"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.5+1.21.1.jar",
          "size": 26479,
          "sha512": "57a8d0b222a0e1cc76016e3a74a45fb6c24172c605f7499cba4b3cc9b084d1844c3f0312e7cc5da53c1f5699026cd9e6ae2681080603deb7f6782b98b5090b53",
          "sha256": "898b28c735be7a2f0569d15d4308a1c88d45b4329c8a2ec5ced9640136dedc24",
          "sha1": "fca57ed1fafd2f107a685901d80029f1046cb500",
          "md5": "cc8ba1ca45f43cd550b59903c46cc171"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.5+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.5+1.21.1-sources.jar",
          "size": 14870,
          "sha512": "c256698fdb83d736ca10230cf0c8abd7cc014a188f83bcd2269672fe97f42148db2761909e47e19d36239d2ac62ede8969264cc2cd6fcd91a488d8e9caebd22f",
          "sha256": "bee297a2540678ad7b5827267b4dcbcb4b33678d9c72aaef529bcf421752f780",
          "sha1": "9e7eb3a2094162423ed0d61671b748aba441c895",
          "md5": "66cf94db0e9a90ceb157a8036fd66bd6"
        }
      ]
    }
  ]
}
