{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.2.0.alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1.jar",
          "size": 181511,
          "sha512": "6730445e8ee8d83f696a8b8dfc67be83bf046f9838b8715877492cebc199bf4c10ba7e98f81ccdb053a92b0c99ccbcd1fb980fd1451736bfb02b1600303f8178",
          "sha256": "da80bfcf002b99f944b19054a408d69a43b3cb32dd04a1f7b9055cb4aff9715a",
          "sha1": "e204f6a12d3396c74fa63b8eeb8e28122fb61d03",
          "md5": "effb06ad204d1eef62cf7e8d9e535bb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1.jar",
          "size": 181511,
          "sha512": "6730445e8ee8d83f696a8b8dfc67be83bf046f9838b8715877492cebc199bf4c10ba7e98f81ccdb053a92b0c99ccbcd1fb980fd1451736bfb02b1600303f8178",
          "sha256": "da80bfcf002b99f944b19054a408d69a43b3cb32dd04a1f7b9055cb4aff9715a",
          "sha1": "e204f6a12d3396c74fa63b8eeb8e28122fb61d03",
          "md5": "effb06ad204d1eef62cf7e8d9e535bb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.4+1.21.1-sources.jar",
          "size": 75250,
          "sha512": "8ec6c9ddb77d9ded8ba1a914c459cdb0c5e6d0d1566551e89aaa196c09a1788364a731ccfb15fd44aa4e839a009cdd00bb492eb2fe456d9371cbc5bd3be007b1",
          "sha256": "a85e1eb8fe03ffe87b767f7d489794672c17ab67821821c6bb57a699ff2eb8ec",
          "sha1": "ce4dffd241f3ba06775915c23fad9a727b6142c4",
          "md5": "747f8b67e20f76a4c8f4298adeeaa602"
        }
      ]
    }
  ]
}
