{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0+1.21.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0+1.21.9"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.9.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.9.jar",
          "size": 678589,
          "sha512": "a0bf3542d6df5afa6ad01ff454570a050b50cc0b7c588b9a05d850ae3f40353b63375667c0fd1266e7c7134852840fe1be09658ec8021d4e49ce484e6a2f81dd",
          "sha256": "2a17cc8ab7a01917574a183d63db70dfc2e6b193d1f70104e8c99ea7a9cbc0a6",
          "sha1": "1b6ac3dd7842334005189f3e7696726a0ca18996",
          "md5": "39429296576c5b4f230788abf0a4049f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0+1.21.9"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0+1.21.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.134.0+1.21.9"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.9.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.9.jar",
          "size": 678589,
          "sha512": "a0bf3542d6df5afa6ad01ff454570a050b50cc0b7c588b9a05d850ae3f40353b63375667c0fd1266e7c7134852840fe1be09658ec8021d4e49ce484e6a2f81dd",
          "sha256": "2a17cc8ab7a01917574a183d63db70dfc2e6b193d1f70104e8c99ea7a9cbc0a6",
          "sha1": "1b6ac3dd7842334005189f3e7696726a0ca18996",
          "md5": "39429296576c5b4f230788abf0a4049f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.9-sources.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.9-sources.jar",
          "size": 227773,
          "sha512": "76bb2b6f4bb52a091b2e8e1b17824e13149d174e8ea3551fa6a83c10836bd6ac51fca453cfa16b33a94fc8ac6adf05ddb5f91120c9f5d42f10b029f1a05791e2",
          "sha256": "565403aede25cbf034f6d74acdf6bd036e72583f9498311d1c3ac217c77146ff",
          "sha1": "f7aa613d46a92120a7a2e93c09320ceb68063ac4",
          "md5": "a6ab4120b74c3eabe3c06ad09ff67605"
        }
      ]
    }
  ]
}
