{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.7.3+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.11.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.11.jar",
          "size": 451232,
          "sha512": "4c2e584ed40fc87ef5bec2fae49c1ea32100e7a8ace8f73d5f79d2f0a52f7ad443e2cca0e7d17a54d633f7c38641c3add303e5b951669769b75ead87ef652195",
          "sha256": "a312bbd3593757142faeb5ec745449d18c94e18d496586743d7976881f9f4974",
          "sha1": "bcec18a3579a1f862fb7dc1ea577860a1f97f7b2",
          "md5": "8ed01898a6ed972975611883277a957c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.4+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.11.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.11.jar",
          "size": 451232,
          "sha512": "4c2e584ed40fc87ef5bec2fae49c1ea32100e7a8ace8f73d5f79d2f0a52f7ad443e2cca0e7d17a54d633f7c38641c3add303e5b951669769b75ead87ef652195",
          "sha256": "a312bbd3593757142faeb5ec745449d18c94e18d496586743d7976881f9f4974",
          "sha1": "bcec18a3579a1f862fb7dc1ea577860a1f97f7b2",
          "md5": "8ed01898a6ed972975611883277a957c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.11-sources.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.11-sources.jar",
          "size": 166089,
          "sha512": "62700f4f368800db4744d6b6ca218e0e6e21be5c91689f15efbfeba8492f5f58c1826a7f1254182b5481b5c7195f9c63059df381b9216e48dbb0bcbeddac2df6",
          "sha256": "3ef1f1508337d198d80d764e6bd4ac23f79cdef975f63fb9c2aa609751033160",
          "sha1": "e3fea5be313846d734da50fa9f4e31341d215b79",
          "md5": "01411f5b4b609381f46bfdd3e075555a"
        }
      ]
    }
  ]
}
