{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-common-api",
    "version": "3.6.3+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.6.3+1.21.4.jar",
          "url": "minecraft-cursor-common-api-3.6.3+1.21.4.jar",
          "size": 11471,
          "sha512": "56be6d6c817693a29e511b85c4b3149fd1ecf7de880c0636fc312645a9ebd2fdc14044effdd47bf386e9cf91a7f934020a7508bca55d65b96995e36b383a92a1",
          "sha256": "7a70436cbc605bb3f44ac086a2221f7550399adb390d0820ffc27413310e3f72",
          "sha1": "6acac7f59bb46d4ca8e4427501f060e5b794d3ff",
          "md5": "eb141cae5a3fb66466326cbbfb5e1171"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.6.3+1.21.4.jar",
          "url": "minecraft-cursor-common-api-3.6.3+1.21.4.jar",
          "size": 11471,
          "sha512": "56be6d6c817693a29e511b85c4b3149fd1ecf7de880c0636fc312645a9ebd2fdc14044effdd47bf386e9cf91a7f934020a7508bca55d65b96995e36b383a92a1",
          "sha256": "7a70436cbc605bb3f44ac086a2221f7550399adb390d0820ffc27413310e3f72",
          "sha1": "6acac7f59bb46d4ca8e4427501f060e5b794d3ff",
          "md5": "eb141cae5a3fb66466326cbbfb5e1171"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.6.3+1.21.4-sources.jar",
          "url": "minecraft-cursor-common-api-3.6.3+1.21.4-sources.jar",
          "size": 10335,
          "sha512": "d6236aa60186d29bce430c30a5d442788c3afe386e44d6d6d4f44a8a5297ac3ad0e71663a23d216ec0f93b56b49caa66e5f6bb40e9c11d4bab88f33dba748c51",
          "sha256": "a1dbb398304f5a695c275b6374de08f9b443fb16cfb6ff8e513781f602303a02",
          "sha1": "a9972a4cee80e8b1d43b1c61be2be53297adaf77",
          "md5": "21e6c0a129d76f4e9b8412920ca6a2dc"
        }
      ]
    }
  ]
}
