{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.5+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.5+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.5+26.2.jar",
          "size": 34134,
          "sha512": "a919d308278e389470f9fd647ab26eb580ae3d57da3fe6b145bc5960ea8ed1def4dc480e385c4784a7cd945e95bea1c8f04b97f7cc5ad2f7f10b6073aee1490e",
          "sha256": "ebe730f5e7c0d370bd360df57e828571e395b436bd3bec02cf8a1c498439684f",
          "sha1": "a52dd052361f3f1b3fe02cd808ae591f0797e8ac",
          "md5": "7c8d7d6f464fb0e77d059b538219c58e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.5+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.5+26.2.jar",
          "size": 34134,
          "sha512": "a919d308278e389470f9fd647ab26eb580ae3d57da3fe6b145bc5960ea8ed1def4dc480e385c4784a7cd945e95bea1c8f04b97f7cc5ad2f7f10b6073aee1490e",
          "sha256": "ebe730f5e7c0d370bd360df57e828571e395b436bd3bec02cf8a1c498439684f",
          "sha1": "a52dd052361f3f1b3fe02cd808ae591f0797e8ac",
          "md5": "7c8d7d6f464fb0e77d059b538219c58e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.5+26.2-sources.jar",
          "url": "packed_packs_api-fabric-2.2.5+26.2-sources.jar",
          "size": 19348,
          "sha512": "f489145d3742277311748748bb444ae9f20a73a86b754734e0f4e90bd4fdae1ca5e466478dec0838807016ab3cdfac2a7e02eaf25081278d20e0c08a8dbcbbf0",
          "sha256": "76aa19310426dcaf426d8abe79b9c665b1f3bb25dbb385919ddbcf29b5b0d74b",
          "sha1": "78ad3fa02f0af50516d1b35ae857e6b85d581792",
          "md5": "61794d2a19a183e74687726822380fe6"
        }
      ]
    }
  ]
}
