{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.2.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.0+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.5.2+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.0+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.0+1.21.11.jar",
          "size": 797132,
          "sha512": "1d2faf4ed79a3f6ea7194c693d194ef0f9164b77a2dbb94ffdf3f1ddee22e18767aa9f004bc3932b2a08fbc9cdd940105840c031574c5d215799089683061f25",
          "sha256": "f23467604478896222c6ca17cf55684be8b32b3223e21d175643c88971aa10e8",
          "sha1": "3cbe82652dd027f8f5b129fd1cac80bc3b342027",
          "md5": "b9a61c0f04fc9f4f081b583593b46c79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.0+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.5.2+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.0+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.0+1.21.11.jar",
          "size": 797132,
          "sha512": "1d2faf4ed79a3f6ea7194c693d194ef0f9164b77a2dbb94ffdf3f1ddee22e18767aa9f004bc3932b2a08fbc9cdd940105840c031574c5d215799089683061f25",
          "sha256": "f23467604478896222c6ca17cf55684be8b32b3223e21d175643c88971aa10e8",
          "sha1": "3cbe82652dd027f8f5b129fd1cac80bc3b342027",
          "md5": "b9a61c0f04fc9f4f081b583593b46c79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.2.0+1.21.11-sources.jar",
          "url": "packed_packs-fabric-2.2.0+1.21.11-sources.jar",
          "size": 188564,
          "sha512": "4a5a1d5936ca535df1b62269d903dbd528804f39776d8eba9fcaf0cc095f646564c001576b1840dcd9770630c156b0a575295caef70d5fc98b8f4a1ac601a827",
          "sha256": "27ca869379922293989118631c380c4b802bb9f18c24d39c679909ab0410b0f4",
          "sha1": "6de19fdd643617a834eed68a74768da204037419",
          "md5": "b528d67385598bbde4859e0a7f5476e0"
        }
      ]
    }
  ]
}
