{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.7.3+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.11.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.11.jar",
          "size": 444816,
          "sha512": "0d226a371eddbc252f83373401fcc1b79599a91b454d70cefb7d7a80e472d22cae9c6562f04d38811d0dab66d6a3c14a71e78fbdb99f6a0e17d4d747a392a374",
          "sha256": "bd9d5f489b105f2cc80a719cbcb46d26d1191668cf11b900e3516d72ebd2fc32",
          "sha1": "81c5bcc3ac9a0148d7d2922639ad82fade77f5e0",
          "md5": "2eb6bda79c72def49d98b87862e71e8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.11.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.11.jar",
          "size": 444816,
          "sha512": "0d226a371eddbc252f83373401fcc1b79599a91b454d70cefb7d7a80e472d22cae9c6562f04d38811d0dab66d6a3c14a71e78fbdb99f6a0e17d4d747a392a374",
          "sha256": "bd9d5f489b105f2cc80a719cbcb46d26d1191668cf11b900e3516d72ebd2fc32",
          "sha1": "81c5bcc3ac9a0148d7d2922639ad82fade77f5e0",
          "md5": "2eb6bda79c72def49d98b87862e71e8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.11-sources.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.11-sources.jar",
          "size": 165682,
          "sha512": "60a087d8747ddea40ce5569f56a19f71b906e7fb1d9749ccc3dabe9ec8a9f22a6e556c3c6d0ef6384cd9b34dfe2f58c38dcff94476d712e445c1b41ca6a30581",
          "sha256": "fda2698e1ea232aaa80bb277dff2546e05f964f2c3becea2412bc16a8acca844",
          "sha1": "5ca5f68cf978ded4479e6489d32832f69e9fc932",
          "md5": "94c9356f63aed3b2a98d51ab3e06ea2c"
        }
      ]
    }
  ]
}
