{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.2.0.alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-fabric-0.2.0.alpha.4+1.21.1.jar",
          "size": 186714,
          "sha512": "c0ba128d6657fcfa2c7f29adef4cba498bdbdfbc2f73d1fc3797cc4538e1e37d925eb558e989de626d16668ded6abf61180b2229e0f0d519125be22ac18b9bcc",
          "sha256": "94fa465c61c69d4998311aa02ccb404db8cf6d2bb9adf151e64f7a4d8f9bdb90",
          "sha1": "94cef809d0ee03c6e1ac6c37b7956dea4e4ad383",
          "md5": "f328e91c4d94e19ea834b337e1f70e5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-fabric-0.2.0.alpha.4+1.21.1.jar",
          "size": 186714,
          "sha512": "c0ba128d6657fcfa2c7f29adef4cba498bdbdfbc2f73d1fc3797cc4538e1e37d925eb558e989de626d16668ded6abf61180b2229e0f0d519125be22ac18b9bcc",
          "sha256": "94fa465c61c69d4998311aa02ccb404db8cf6d2bb9adf151e64f7a4d8f9bdb90",
          "sha1": "94cef809d0ee03c6e1ac6c37b7956dea4e4ad383",
          "md5": "f328e91c4d94e19ea834b337e1f70e5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.2.0.alpha.4+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.2.0.alpha.4+1.21.1-sources.jar",
          "size": 83274,
          "sha512": "2672b8bf20f4c9b4fa6d088c13670b98fde413d92cc74d9866d8aa80ce487f9401887c310e3ecb46a8a56bc9226fef80cc1bf7c75cbdf87aec29729be2c8ffeb",
          "sha256": "1f58ca4c85e24c8321453af8db43b57a354e4e99eefe44d6e8b9858b7e341578",
          "sha1": "67184a7a4bca61cd98e61f86ce3b59c1f15bf69d",
          "md5": "8cbc199389c6a4f981e2c28ccfb82a66"
        }
      ]
    }
  ]
}
