{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-neoforge",
    "version": "3.11.1+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.11.1+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.2.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.2.jar",
          "size": 281727,
          "sha512": "397acbf298840ed1da6161513b2fc7c73408e2f231de53ce7a7170163b1660ac3903c3ed38e4201562f8ed08e800c726d9a202a8bf0f7e8604ee635c51ebf5c5",
          "sha256": "29347eac5b992962e0736e52a485f3263f70181df0ba262119b786b7ee49928a",
          "sha1": "c3c59cce94c887b58ee9e8ef949ec45120e815ba",
          "md5": "53807966643b1333fb4dc71eb325aa0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.11.1+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.2.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.2.jar",
          "size": 281727,
          "sha512": "397acbf298840ed1da6161513b2fc7c73408e2f231de53ce7a7170163b1660ac3903c3ed38e4201562f8ed08e800c726d9a202a8bf0f7e8604ee635c51ebf5c5",
          "sha256": "29347eac5b992962e0736e52a485f3263f70181df0ba262119b786b7ee49928a",
          "sha1": "c3c59cce94c887b58ee9e8ef949ec45120e815ba",
          "md5": "53807966643b1333fb4dc71eb325aa0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.2-sources.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.2-sources.jar",
          "size": 132734,
          "sha512": "173ed0a3cfa69c0317f9d0b394cee5417cb78d9d00690257c5b9b38a40a03bf280c5fcd1aba1ec8d8fdb0e1e34813b71d436ac761aa46f8471cab99a38feb136",
          "sha256": "25c4d4dad44136b7f5a9ce54199f08d52bcff7f92dccb8d4402d3bedb0c3e1b6",
          "sha1": "29a2576ed07c1e70184edf5bb12a5af3f9df8526",
          "md5": "8830b8565a12e92cb00849929bfd6acb"
        }
      ]
    }
  ]
}
