{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.1+26.1-patch.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.1+26.1-patch.1.jar",
          "url": "packed_packs_api-neoforge-2.1.1+26.1-patch.1.jar",
          "size": 30617,
          "sha512": "f6a2516df7d3d1274a86fcc9298c426d9e0ca5dd30dc8f147315dc20ab2054585fb970218b9c0e27c876cae0c77bedb6d2ad54157820e517a28d7b9bb9a3223d",
          "sha256": "440d1d0d7d615ae5834c349ca55957ef1a11705ffa3fb65e7855c9b900d36d47",
          "sha1": "574508acee3fc6c5d3fde2610f9d29548e3e1aa4",
          "md5": "1f05106b80f9a16c8c2d8007454f7970"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.1+26.1-patch.1.jar",
          "url": "packed_packs_api-neoforge-2.1.1+26.1-patch.1.jar",
          "size": 30617,
          "sha512": "f6a2516df7d3d1274a86fcc9298c426d9e0ca5dd30dc8f147315dc20ab2054585fb970218b9c0e27c876cae0c77bedb6d2ad54157820e517a28d7b9bb9a3223d",
          "sha256": "440d1d0d7d615ae5834c349ca55957ef1a11705ffa3fb65e7855c9b900d36d47",
          "sha1": "574508acee3fc6c5d3fde2610f9d29548e3e1aa4",
          "md5": "1f05106b80f9a16c8c2d8007454f7970"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.1+26.1-patch.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.1+26.1-patch.1-sources.jar",
          "size": 18451,
          "sha512": "a7432646f3b39c73143df352a8adee987fbb44a93042fce8d5ac8b8668c11d9c29975df2f2e714f1f4189f031f6e11099955d72ed2a924dc9b087a6c52a6c5be",
          "sha256": "dc13c23f6e2e1a3801d765e6b6ccaa26644b7575f5b4ca0524070128ed0e4ac0",
          "sha1": "0abca2a9659def4ffa0bae78c3e3ee58cd37c045",
          "md5": "d6b22e050347a6f51e6535c2db59cb02"
        }
      ]
    }
  ]
}
