{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.1-alpha.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1-alpha.1+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.1-alpha.1+26.2.jar",
          "size": 34086,
          "sha512": "ef9a6256656dedb2586806734b5959c1e26a1073058ae0d90de139b20399b1ab8f9cd313e153e4bdec004d2b3a923b3672cc34a31288c94fc1bdfcd919f4732e",
          "sha256": "ba4678e05e24e75be0348a844ee7da852a03eff46f5fda05d57f35cfca88c9ad",
          "sha1": "779da55ba8cdaadb634b43f13d7887ef50e2afac",
          "md5": "054122ed5b421d6cfb314498050dea40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.150.1+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1-alpha.1+26.2.jar",
          "url": "packed_packs_api-fabric-2.2.1-alpha.1+26.2.jar",
          "size": 34086,
          "sha512": "ef9a6256656dedb2586806734b5959c1e26a1073058ae0d90de139b20399b1ab8f9cd313e153e4bdec004d2b3a923b3672cc34a31288c94fc1bdfcd919f4732e",
          "sha256": "ba4678e05e24e75be0348a844ee7da852a03eff46f5fda05d57f35cfca88c9ad",
          "sha1": "779da55ba8cdaadb634b43f13d7887ef50e2afac",
          "md5": "054122ed5b421d6cfb314498050dea40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1-alpha.1+26.2-sources.jar",
          "url": "packed_packs_api-fabric-2.2.1-alpha.1+26.2-sources.jar",
          "size": 19307,
          "sha512": "16a919818866407db45f5baa140d7db7a462073ec695ec299490d3247f7aeb61f6759834ddf8ddc84dcb77f3d3aff7554fb26acf109517953ea5f02d09203098",
          "sha256": "26aa97b2b7790f7bfec290f76c6576c239e0ee0df8d9b3829313f8777faa7db7",
          "sha1": "0ef74ce15932b206f0dc88065857681050d2d8fd",
          "md5": "d3778e44064a4e0e9fe5b9fc0cd37c05"
        }
      ]
    }
  ]
}
