{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.2.5+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.1.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.1.jar",
          "size": 32302,
          "sha512": "f5ea9147639917f62e7abc721938f8f4b62a5fb678f299433ced0b1a58448a442362bdfc99eee3ad3a7c25feb0beb77a35482b58b89012a1e1cb59b7ac8640b3",
          "sha256": "77d7b9b110f0ccab01a8f853adb848829cfc0cea1f654e4e7a6e135818b6e220",
          "sha1": "7840c8a648996b56cf59567fd8fac30d4bef3e38",
          "md5": "33593f62f7672641c768f079ed813d1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.1.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.1.jar",
          "size": 32302,
          "sha512": "f5ea9147639917f62e7abc721938f8f4b62a5fb678f299433ced0b1a58448a442362bdfc99eee3ad3a7c25feb0beb77a35482b58b89012a1e1cb59b7ac8640b3",
          "sha256": "77d7b9b110f0ccab01a8f853adb848829cfc0cea1f654e4e7a6e135818b6e220",
          "sha1": "7840c8a648996b56cf59567fd8fac30d4bef3e38",
          "md5": "33593f62f7672641c768f079ed813d1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.1-sources.jar",
          "size": 19409,
          "sha512": "60ed68477ed949acbae023f3f11645f4a7172e446b5e21125e7300bface228a513f8721ffe0de03d29e78f0d41aab7c8ec75fae2d4d30c19acc86a85f8f1121a",
          "sha256": "fc6f2f585cb6ea016a716e140aef724c0815c09045900b5a4bca0a732505bd55",
          "sha1": "dbe989060c0ff10cfa281c06ff7ec8beee3e914c",
          "md5": "bbf8164ab88d1331681e156183adf8b9"
        }
      ]
    }
  ]
}
