{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "size": 654679,
          "sha512": "2bb282c1801592e1b4b7cce05a8f015081d83ac990564688718be5df734fef6fa7f9afd83434882b23fee9adea2196575387840eb89f47b90f9c272c72f4e664",
          "sha256": "b47c2f199d669fd7b547bd04116557f005dc73ca7aac0f6c43e7abd86c337454",
          "sha1": "0e317924f7a8f2552e9be9c85c88f836188daa4b",
          "md5": "dbde1a1cb17ce1183afe171ac643cba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "size": 654679,
          "sha512": "2bb282c1801592e1b4b7cce05a8f015081d83ac990564688718be5df734fef6fa7f9afd83434882b23fee9adea2196575387840eb89f47b90f9c272c72f4e664",
          "sha256": "b47c2f199d669fd7b547bd04116557f005dc73ca7aac0f6c43e7abd86c337454",
          "sha1": "0e317924f7a8f2552e9be9c85c88f836188daa4b",
          "md5": "dbde1a1cb17ce1183afe171ac643cba6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.6+1.21.1-sources.jar",
          "size": 178196,
          "sha512": "ea483449c02cbb7f7e899a76a16ac2653a0f7acb66730626e0b0a731127e33bca58c631dd5b730ee367b641c7ff0868c76d155b71d90b5764ebe7d47dd4d1538",
          "sha256": "ec254adc60d56618659eb7eaa39a54547876d43c5b9019de57a6a944a8989a75",
          "sha1": "24ba8ae5057ac3f12f534bb65ef4936cb7470234",
          "md5": "841cb28d00bb7166f5bbb0d8e061d812"
        }
      ]
    }
  ]
}
