{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.7.1-neoforge.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.1-neoforge.1+26.2.jar",
          "url": "fidgetz-neoforge-0.7.1-neoforge.1+26.2.jar",
          "size": 435089,
          "sha512": "2af6e0994745d7f9fb7bc69b4ff650d1e64d540c41be1082ae3a9fcdeb5d28c4a38fd1ac603585586821dd72afffe896e3727e14ffd922c4f814b2c21a56d276",
          "sha256": "a3405db073804e0e89faa699b2eb092a0b52526e4c70c7f205269f05359e1b5d",
          "sha1": "b7ad15e27e14444d2ecbcf9953549896a60a0511",
          "md5": "362c03f7fd533f36a29569ae1ac34a38"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.1-neoforge.1+26.2.jar",
          "url": "fidgetz-neoforge-0.7.1-neoforge.1+26.2.jar",
          "size": 435089,
          "sha512": "2af6e0994745d7f9fb7bc69b4ff650d1e64d540c41be1082ae3a9fcdeb5d28c4a38fd1ac603585586821dd72afffe896e3727e14ffd922c4f814b2c21a56d276",
          "sha256": "a3405db073804e0e89faa699b2eb092a0b52526e4c70c7f205269f05359e1b5d",
          "sha1": "b7ad15e27e14444d2ecbcf9953549896a60a0511",
          "md5": "362c03f7fd533f36a29569ae1ac34a38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.1-neoforge.1+26.2-sources.jar",
          "url": "fidgetz-neoforge-0.7.1-neoforge.1+26.2-sources.jar",
          "size": 159871,
          "sha512": "4087c99f491969ffc678a855cffcd600300005e1372e86d8284511b568587e55a2ccb6252e6f21b6d81b0f340987e804e7b5ffc200fb744a7e33f8cfcf491a0f",
          "sha256": "70df0552b23382b4dff0ee6599a81023f5946edd9e5ee155de484680f8046d9f",
          "sha1": "2faedc47f81dfd0d58c633756a24a83f90abe018",
          "md5": "fe06f2bcf527ddfd345396f3cdf3ebbd"
        }
      ]
    }
  ]
}
