{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.3.0-beta.1+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.3.0-beta.1+26.3"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.3+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.3.0-beta.1+26.3.jar",
          "url": "packed_packs-neoforge-2.3.0-beta.1+26.3.jar",
          "size": 958845,
          "sha512": "0f4291ef2d328bec396801d771110e6363a4d03c4a4efc4cea1e872f5d14a1f21dcaf435fa99dd6bf7bbde0d671a63cfad680b88b5537b3fd3b3d2595c9dd44e",
          "sha256": "65d00ca5be50166eeae80592fc85fa0069b3fd20893b96d70ecca141813adc64",
          "sha1": "fb14f6d520781a6d7ed238d565186d089f73f253",
          "md5": "5dd8ef43416254c187f6781ab4536fe9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.3.0-beta.1+26.3"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.3+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.3.0-beta.1+26.3.jar",
          "url": "packed_packs-neoforge-2.3.0-beta.1+26.3.jar",
          "size": 958845,
          "sha512": "0f4291ef2d328bec396801d771110e6363a4d03c4a4efc4cea1e872f5d14a1f21dcaf435fa99dd6bf7bbde0d671a63cfad680b88b5537b3fd3b3d2595c9dd44e",
          "sha256": "65d00ca5be50166eeae80592fc85fa0069b3fd20893b96d70ecca141813adc64",
          "sha1": "fb14f6d520781a6d7ed238d565186d089f73f253",
          "md5": "5dd8ef43416254c187f6781ab4536fe9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.3.0-beta.1+26.3-sources.jar",
          "url": "packed_packs-neoforge-2.3.0-beta.1+26.3-sources.jar",
          "size": 190331,
          "sha512": "efe4dcf2070c9327e2590cce585e62d08a3a977331687534e63537e28cfe58bcecd5013adcec80543fed9f12160ef3536b87bf7d2caf7f22015bf4442708a0a1",
          "sha256": "104db2b58f685761231004a70bd31550e53b757870202ac4b0cfe7da7a9fe144",
          "sha1": "9fa1ae9f08e0c4746a06bfd87a8a6fb984b1791a",
          "md5": "f4566571fc2096ff7f702c911669ea2f"
        }
      ]
    }
  ]
}
