{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.5.0-beta.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.0-beta.5+1.21.1.jar",
          "url": "fidgetz-neoforge-0.5.0-beta.5+1.21.1.jar",
          "size": 314051,
          "sha512": "738f932ef624bb8f65940fd618f0a60ef925e59d0ad525d90f658180e338dfc1b0aed8c398d964e1acbf41b709c907afd2d3ff86a9c3b382a3286f0f83fa2380",
          "sha256": "5db2786d8936046e575f6911dba1cd09b359a2a42c3741b07f28623757e9f20d",
          "sha1": "51ba9d2206ba0154f0393f013ad214b19c5f9d90",
          "md5": "562fc358c1b3af8baefed8d9f7db66c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.0-beta.5+1.21.1.jar",
          "url": "fidgetz-neoforge-0.5.0-beta.5+1.21.1.jar",
          "size": 314051,
          "sha512": "738f932ef624bb8f65940fd618f0a60ef925e59d0ad525d90f658180e338dfc1b0aed8c398d964e1acbf41b709c907afd2d3ff86a9c3b382a3286f0f83fa2380",
          "sha256": "5db2786d8936046e575f6911dba1cd09b359a2a42c3741b07f28623757e9f20d",
          "sha1": "51ba9d2206ba0154f0393f013ad214b19c5f9d90",
          "md5": "562fc358c1b3af8baefed8d9f7db66c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.5.0-beta.5+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.5.0-beta.5+1.21.1-sources.jar",
          "size": 121943,
          "sha512": "9506d93252399351f03d06f70a3d7eebaa6eb025b8617c800aaebcea23cb69aa1d61f3dfc1d1d9a47b4cc3d7a9a9c0ffbe0d4fbea3b61ad7d3f264056325badb",
          "sha256": "6c03ec3741240bafb8616befa98af34e65cdb3b9335ceede345b46e9e2e0c3d2",
          "sha1": "45accbf32447fb4212e08bc29becbb62e12bdee4",
          "md5": "9c869f4c69560426fe62c07d00214d94"
        }
      ]
    }
  ]
}
