{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.11+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "size": 26472,
          "sha512": "7d37bab528d4c0e59c73788a4e903ddcf0304b7a57008d7fbbbe499fa126d02f7e01d01a75b26d4e592a89a99b6049eb76d07627c6315f6733f42499c0e4cd3a",
          "sha256": "cd3edf8ae13511727b24c2eb443ebdf903455b3ae7f4724de2d0a86497834a9b",
          "sha1": "58d92b3308789b65c64f8754467027efb5298c33",
          "md5": "3cf2c0217258632c0e721c2666a87700"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "size": 26472,
          "sha512": "7d37bab528d4c0e59c73788a4e903ddcf0304b7a57008d7fbbbe499fa126d02f7e01d01a75b26d4e592a89a99b6049eb76d07627c6315f6733f42499c0e4cd3a",
          "sha256": "cd3edf8ae13511727b24c2eb443ebdf903455b3ae7f4724de2d0a86497834a9b",
          "sha1": "58d92b3308789b65c64f8754467027efb5298c33",
          "md5": "3cf2c0217258632c0e721c2666a87700"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.11+1.21.1-sources.jar",
          "size": 15133,
          "sha512": "b365e4a515858faed8015e8f21e33d90aa7e1269c4598eeb4517ab387d0992586c79bae108700a3ef9a554aa6a9f45dd53f85015f448545dfd1bdce77ef10d91",
          "sha256": "7a2cb2965090a98c8beb2e02ae9a540eb1e55664dc41b76064cb4b47798500ca",
          "sha1": "aa81395b7e80310b146d481cba3f57d6403f19e7",
          "md5": "7268b28a938a2c6603524c0ac5a60372"
        }
      ]
    }
  ]
}
