{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1.jar",
          "size": 30719,
          "sha512": "9edbac7e9bf3c9872ccf493a3e57507b379a7551bb2c638f7b5cf9617a3edfde7af1ac3f04be5713e8ed88932927c09af8bcdf92ba42affac63b1d55ccd22ba8",
          "sha256": "f7f7d3d5cb236bea554d510ad3c16a9daa9018130d0426832b66c0089ccf52ac",
          "sha1": "4b76def84578e3e876fc14669e6bc046e692046d",
          "md5": "4e72bf8fbd598bcabb63d34e41cfae4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1.jar",
          "size": 30719,
          "sha512": "9edbac7e9bf3c9872ccf493a3e57507b379a7551bb2c638f7b5cf9617a3edfde7af1ac3f04be5713e8ed88932927c09af8bcdf92ba42affac63b1d55ccd22ba8",
          "sha256": "f7f7d3d5cb236bea554d510ad3c16a9daa9018130d0426832b66c0089ccf52ac",
          "sha1": "4b76def84578e3e876fc14669e6bc046e692046d",
          "md5": "4e72bf8fbd598bcabb63d34e41cfae4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.12+1.21.1-sources.jar",
          "size": 18542,
          "sha512": "935fdd9732b9c86cd590fc649476eb65f4f3762c6a98eb69e5aaac9c5df1c84b7aa1effecb1700d13fd510337f79986c5410855955b184c30516f32d687cdebc",
          "sha256": "04cea7a126f2bf8e41cf9f8796cfe8a0a1db73ca7764cd255c530380e65642c0",
          "sha1": "e5b01b6c88d769eab766cf5cb5ba652b65b1de46",
          "md5": "f915c56f398608051aba904ffcbdf603"
        }
      ]
    }
  ]
}
