{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.5.0-beta.4+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.4+1.21.11.jar",
          "url": "fidgetz-common-0.5.0-beta.4+1.21.11.jar",
          "size": 305873,
          "sha512": "74c28c64c3c209e4b72503cf7f5995909320e7adb4df7efda1a688464e7eac4d9bedce6f92446fdf14e03e76dd92beebb1c5bbc1559cf27599f4ca080d0593ee",
          "sha256": "1cdfe0da8214d0644b77184c190ca356da1d42366baed5ae61de889f166159fb",
          "sha1": "63a31c0e1a3e0e50ef156ce53cc911780ca33fdc",
          "md5": "45994911b118ee4fb40372f9e56ed67f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.4+1.21.11.jar",
          "url": "fidgetz-common-0.5.0-beta.4+1.21.11.jar",
          "size": 305873,
          "sha512": "74c28c64c3c209e4b72503cf7f5995909320e7adb4df7efda1a688464e7eac4d9bedce6f92446fdf14e03e76dd92beebb1c5bbc1559cf27599f4ca080d0593ee",
          "sha256": "1cdfe0da8214d0644b77184c190ca356da1d42366baed5ae61de889f166159fb",
          "sha1": "63a31c0e1a3e0e50ef156ce53cc911780ca33fdc",
          "md5": "45994911b118ee4fb40372f9e56ed67f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.4+1.21.11-sources.jar",
          "url": "fidgetz-common-0.5.0-beta.4+1.21.11-sources.jar",
          "size": 117015,
          "sha512": "5f8b98fa2f7bfe6815c6c3ef4a94df344832ae1740f354093dc6b8b375f2e7e258b6636c1f0d9bc3cd5f40b08541382d2156f1903844e7104d68dc09dd13845d",
          "sha256": "fc84bb0479aca0e0121c4eb5d66acba7e55210b1534149489cebd8f956f85c30",
          "sha1": "18865627c673c015381e13a0b98e462f959aeafd",
          "md5": "8029c7a54ce04835703b97256d1c6b79"
        }
      ]
    }
  ]
}
