{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.4+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+26.2.jar",
          "url": "packed_packs_api-common-2.2.4+26.2.jar",
          "size": 31930,
          "sha512": "79775b62b9d0d8de25c7d7e60287416b780980b60dad3acafc591528d2bc73a8edb645cdee401453baaf4978076cc39e35f5b95335b4cb3d4ed84b0834d61269",
          "sha256": "6d64d0260d33ee9f32c53a4fa2d8db5ffb9eebe08a8c812acccba3663a4be8de",
          "sha1": "dbe1bfab4a6fc5bb5f66a42c498a74a19d93bdbe",
          "md5": "6dcb24a9fbeadd3f8765c2a052a7ac1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+26.2.jar",
          "url": "packed_packs_api-common-2.2.4+26.2.jar",
          "size": 31930,
          "sha512": "79775b62b9d0d8de25c7d7e60287416b780980b60dad3acafc591528d2bc73a8edb645cdee401453baaf4978076cc39e35f5b95335b4cb3d4ed84b0834d61269",
          "sha256": "6d64d0260d33ee9f32c53a4fa2d8db5ffb9eebe08a8c812acccba3663a4be8de",
          "sha1": "dbe1bfab4a6fc5bb5f66a42c498a74a19d93bdbe",
          "md5": "6dcb24a9fbeadd3f8765c2a052a7ac1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+26.2-sources.jar",
          "url": "packed_packs_api-common-2.2.4+26.2-sources.jar",
          "size": 19058,
          "sha512": "52cb8c2275cf1cc3ca906f7bf1ebed5a5b1ecee83b3d0aee8027995b2891349305c5b2698d84647dd3b0e94e57d9c3be10eda7c9bde0234b01e259e48195ad48",
          "sha256": "be884312cb5403cd6cbef89f7740c067bea72e753031cf162993267c180c03bd",
          "sha1": "250f9a9fa28b421b084f1b290331c7671cef057d",
          "md5": "f2ef4b32c8ec3418ab9f0e75b959b272"
        }
      ]
    }
  ]
}
