{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.11+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.11+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "size": 656547,
          "sha512": "813711056c859049e062906ceff12c15a4a93628da67e41181355582498eb6e1bed042e84351ace8420f3b25a8ba3718b8a1455922e21b9fec0e55e7fdf9c000",
          "sha256": "656f9f0b1bc3c9500d389e5476eca5c84185becfb0d73f7c22cfa6e6f36716ca",
          "sha1": "3d452c6a3e52524e5d101cd622a30ad513a1b03e",
          "md5": "c054ae4af042f2821ce240ba7e750fbc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.11+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1.jar",
          "size": 656547,
          "sha512": "813711056c859049e062906ceff12c15a4a93628da67e41181355582498eb6e1bed042e84351ace8420f3b25a8ba3718b8a1455922e21b9fec0e55e7fdf9c000",
          "sha256": "656f9f0b1bc3c9500d389e5476eca5c84185becfb0d73f7c22cfa6e6f36716ca",
          "sha1": "3d452c6a3e52524e5d101cd622a30ad513a1b03e",
          "md5": "c054ae4af042f2821ce240ba7e750fbc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.11+1.21.1-sources.jar",
          "size": 178903,
          "sha512": "e0c51fe6065ff1b11e8bc6c87284f184d75cd1b7fe3d9a52838b63399228eed08e40eb00e43bcb614da7070046e083f475235a0c9048f5d9b6a03db51bb5725f",
          "sha256": "e6c5aa947a5473fdf1c38ca8011b5a0213090175b95cc41e5a670e17cce36027",
          "sha1": "06d46fbf855629d62644998d49b5b039884c4378",
          "md5": "61f1aeb701d8bd39ecdb943a7740d132"
        }
      ]
    }
  ]
}
