{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.2.0.alpha.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1.jar",
          "size": 181689,
          "sha512": "af87d4d1e472466e942a7ffd17043988ae67f244cf10bc9d22646748083902b1b6667172eed0cf4ed027c4332e4d711ab762b1821402833a4dfc4ac5cb46eebf",
          "sha256": "8117a2e5c84a75fefc5dfa51789b40570057566a50890d4fe422e76e21e1f7b5",
          "sha1": "1a54568edc705ab97cba4a92f137a44bec9501fa",
          "md5": "54deeecd07f0fdf9fb8a60426a819517"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1.jar",
          "size": 181689,
          "sha512": "af87d4d1e472466e942a7ffd17043988ae67f244cf10bc9d22646748083902b1b6667172eed0cf4ed027c4332e4d711ab762b1821402833a4dfc4ac5cb46eebf",
          "sha256": "8117a2e5c84a75fefc5dfa51789b40570057566a50890d4fe422e76e21e1f7b5",
          "sha1": "1a54568edc705ab97cba4a92f137a44bec9501fa",
          "md5": "54deeecd07f0fdf9fb8a60426a819517"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.2.0.alpha.3+1.21.1-sources.jar",
          "size": 75315,
          "sha512": "658af5c57b149bb64d8f52b1b671a90ad62fc2680baac9e92142b6dccceb72148639acd768151885eeaea5e8d1e60bc9b5b8be67234489c87ae0000c456edf25",
          "sha256": "afa5caad164209c42277c56db69a486cfb7caa6cc814d6fba0d9066874560d8a",
          "sha1": "6158500c7dc11a44f66f09038320ab70636c9a63",
          "md5": "d2a52863e7911834347ca60401ee5044"
        }
      ]
    }
  ]
}
