{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0-beta.2+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+26.2.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+26.2.jar",
          "size": 32029,
          "sha512": "b600a9a4b5bd27929a98c2b913a5ca69fa84832849f6ea5a63c0331686608a85df9380d0a2797bec89c9b1f641c1542584187cc3d943052b11945b5375b76bd2",
          "sha256": "f0d25edb2a4bf3b348cfedc097d385db648b8127e6534ab54f7a7a7bf15e561c",
          "sha1": "688dfd44535b92ba70b81decb5f77598a9b452f9",
          "md5": "79f8ea03ecd5076ed2b587466135fe25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+26.2.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+26.2.jar",
          "size": 32029,
          "sha512": "b600a9a4b5bd27929a98c2b913a5ca69fa84832849f6ea5a63c0331686608a85df9380d0a2797bec89c9b1f641c1542584187cc3d943052b11945b5375b76bd2",
          "sha256": "f0d25edb2a4bf3b348cfedc097d385db648b8127e6534ab54f7a7a7bf15e561c",
          "sha1": "688dfd44535b92ba70b81decb5f77598a9b452f9",
          "md5": "79f8ea03ecd5076ed2b587466135fe25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+26.2-sources.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+26.2-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
