{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.2.5+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.3.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.3.jar",
          "size": 32323,
          "sha512": "d65a3795c3228d836151fd661d180c13ad77a31a32f28b1f5fe723d0f994a8e5b18aa11dd4ec15da20f8665222c78db5ace5d6c95e5a1ca9d4e024b9d9f5cbec",
          "sha256": "1692f89a96f5e55e7894ff2f9093f3eee74e58efeabb2c684eececcb505079c7",
          "sha1": "ad039eb0f4003172ec46c9bc59275d52a697ee47",
          "md5": "6f4628e7cd6f2526c16752297a7d1b05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.3.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.3.jar",
          "size": 32323,
          "sha512": "d65a3795c3228d836151fd661d180c13ad77a31a32f28b1f5fe723d0f994a8e5b18aa11dd4ec15da20f8665222c78db5ace5d6c95e5a1ca9d4e024b9d9f5cbec",
          "sha256": "1692f89a96f5e55e7894ff2f9093f3eee74e58efeabb2c684eececcb505079c7",
          "sha1": "ad039eb0f4003172ec46c9bc59275d52a697ee47",
          "md5": "6f4628e7cd6f2526c16752297a7d1b05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.3-sources.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.3-sources.jar",
          "size": 19429,
          "sha512": "6dbc7e3f96a49cc0e74cb48160e6192ad5a17ab22a5a26e044711af690f4cae73e43deba2e069141311cf041d5fc534727fb3b747299874527a8c230ed81b877",
          "sha256": "144c1b8d399f287536338fcf459aebd7001a5f9d3ba798fe4cc025a5d9c51376",
          "sha1": "a122614f4415632a394366c1c68b3b1fd83d91a0",
          "md5": "6bb34dc317cbb83496d20abd24925ef4"
        }
      ]
    }
  ]
}
