{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-common-api",
    "version": "3.9.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-common-api-3.9.0+1.21.4.jar",
          "size": 10438,
          "sha512": "c1da088bb7143391bea3ea8268f133b6647396c6e02cb233f99776ea931a62c764532f7b65a1f85589fd893aa2ec45f0d174e06eef79f5d198767060845f4193",
          "sha256": "ef5d3a4e85685a2f12854d10daf681bf37ef58a8ca9567c15d6175a152cb3309",
          "sha1": "f39a02903c832da96a1f8c3ce560da793638d426",
          "md5": "af1d35bbab45443713e3b0c3dac82c37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-common-api-3.9.0+1.21.4.jar",
          "size": 10438,
          "sha512": "c1da088bb7143391bea3ea8268f133b6647396c6e02cb233f99776ea931a62c764532f7b65a1f85589fd893aa2ec45f0d174e06eef79f5d198767060845f4193",
          "sha256": "ef5d3a4e85685a2f12854d10daf681bf37ef58a8ca9567c15d6175a152cb3309",
          "sha1": "f39a02903c832da96a1f8c3ce560da793638d426",
          "md5": "af1d35bbab45443713e3b0c3dac82c37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-common-api-3.9.0+1.21.4-sources.jar",
          "url": "minecraft-cursor-common-api-3.9.0+1.21.4-sources.jar",
          "size": 8789,
          "sha512": "4e40dcef4ff58b6fafe0566bc034ad04ba2530d89a85d8e01b30e0688ae667c6abe35862c95cad634e89aed5e112792246323588bc60ccd6c7aea9d6872d1c39",
          "sha256": "2e8e5bf38f8f84c781d396a463b3a36187e2299dcd78a9c1f68c69c11e0d6601",
          "sha1": "74a9ed41e9ba1c54239d24d920571b96ae65daef",
          "md5": "9f2086fb052cb21b923f1ce340cb2ef0"
        }
      ]
    }
  ]
}
