{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.6.4+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.4+1.20.1.jar",
          "url": "minecraft-cursor-fabric-api-3.6.4+1.20.1.jar",
          "size": 12217,
          "sha512": "b12d3ca1896a46b04d3be6bdf85a6ce5c79e8466f194803b8de5bc2e3a13d94008f0558df535ab2e17a0860f5c56867c5e4c7d373b84273ec6f54f8d761ba820",
          "sha256": "b199e43fcb3e530ae98e40c418130b4fc9b39dc5c76160dac2fa4ab98695d0ba",
          "sha1": "6258c0dbf3678cd676371b7eda578b1c771dedc8",
          "md5": "e2d3d9302cd607fe88f94054908ec8dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.4+1.20.1.jar",
          "url": "minecraft-cursor-fabric-api-3.6.4+1.20.1.jar",
          "size": 12217,
          "sha512": "b12d3ca1896a46b04d3be6bdf85a6ce5c79e8466f194803b8de5bc2e3a13d94008f0558df535ab2e17a0860f5c56867c5e4c7d373b84273ec6f54f8d761ba820",
          "sha256": "b199e43fcb3e530ae98e40c418130b4fc9b39dc5c76160dac2fa4ab98695d0ba",
          "sha1": "6258c0dbf3678cd676371b7eda578b1c771dedc8",
          "md5": "e2d3d9302cd607fe88f94054908ec8dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.4+1.20.1-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.6.4+1.20.1-sources.jar",
          "size": 12271,
          "sha512": "83fab61e5adc059902f1c9bde3526896e1ed11376ae7a8d9a1cb681e78c8e842e356052f0d0122022771b0a4c0451530d856bfba0fcfeca9cc57de04c0479d06",
          "sha256": "d55225e1346418a0d779e81d114bce68aed3212d5acd7b94dca364e81f2eed6e",
          "sha1": "0835f8ea70166b0b6b41dfac0fd552f0640585d0",
          "md5": "5100437577bf522581ffdebb187981c1"
        }
      ]
    }
  ]
}
