{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "size": 179591,
          "sha512": "5ccc105ac56509ee7784bf9a8cb54e448642c7add5f84aa0df2cd3ef439355e883f6273b67d4de1ba36191ffde10185fadf2fd014252744235b87f9c24affb6c",
          "sha256": "068e25a2c18da7754c00f2715227fa18fcc582c7af7a65293237331695ad4a81",
          "sha1": "ea0f68c7ebddb944e87d3ed1aedb2725c724c21e",
          "md5": "1573dd5420345dfda03dfbb379c96ceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "size": 179591,
          "sha512": "5ccc105ac56509ee7784bf9a8cb54e448642c7add5f84aa0df2cd3ef439355e883f6273b67d4de1ba36191ffde10185fadf2fd014252744235b87f9c24affb6c",
          "sha256": "068e25a2c18da7754c00f2715227fa18fcc582c7af7a65293237331695ad4a81",
          "sha1": "ea0f68c7ebddb944e87d3ed1aedb2725c724c21e",
          "md5": "1573dd5420345dfda03dfbb379c96ceb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1-sources.jar",
          "size": 73159,
          "sha512": "00b1690a1c2f6bc872c3f7fedf40e28c703392d317256198fe3250b2eb526b7e8267c62ae7d9a8ea1cb1b982e8fc6aef1adda0dc7dd8b49f259c5a15fc9f9fac",
          "sha256": "8d62e639d07416ad6bea851867c5cc6d4bcaf14c7a0a5a03257ee0c2c4d79dca",
          "sha1": "b5bb64237181c2884bc1bcf1ce259c3904de8400",
          "md5": "c33db8c437f47e8c041ce0fb146c23dd"
        }
      ]
    }
  ]
}
