{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "size": 179591,
          "sha512": "08a5bbea638e0e09831f8363fc657fd741b2bc9df300d3fa638f5e5afcf535bd036eed61d8bf111f088e7b86dba7876a5144780f7b1a75b8572735d8fe2a1ef1",
          "sha256": "50734de40948daf05f9dbc7c653c490507fa6f5ef6618522412d2b5a6b3159d0",
          "sha1": "351eeab3d87bc3382d7e1396a436600fd37f8c71",
          "md5": "5ae01e19865894982bf84115f042e3e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1.jar",
          "size": 179591,
          "sha512": "08a5bbea638e0e09831f8363fc657fd741b2bc9df300d3fa638f5e5afcf535bd036eed61d8bf111f088e7b86dba7876a5144780f7b1a75b8572735d8fe2a1ef1",
          "sha256": "50734de40948daf05f9dbc7c653c490507fa6f5ef6618522412d2b5a6b3159d0",
          "sha1": "351eeab3d87bc3382d7e1396a436600fd37f8c71",
          "md5": "5ae01e19865894982bf84115f042e3e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.1.0+1.21.1-sources.jar",
          "size": 73159,
          "sha512": "31d0428372cd7fc46e4c98d65d3bb6741beab44296b2686d8214a7c042a6242e2d3c84f7c3d78203451191e058e5cf021b5899709e919a44834217bc2a2d0d85",
          "sha256": "71bedfc794876672dfeab28470480a59ec138e758b7fc1285079df3757935bb1",
          "sha1": "3e4d9173bb65bebc3903de19d6a826b205c5c041",
          "md5": "3ff34d5b0eb394b31fbc4331081b977b"
        }
      ]
    }
  ]
}
