{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.3+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+26.1.jar",
          "url": "packed_packs_api-common-2.2.3+26.1.jar",
          "size": 31930,
          "sha512": "bf24774d32d8eed9483e3ee5ec589a94ead5d8e69be25144e7b050d21ba35cd12fbbe604337c4536d1615a9887a58b2a5a5bc009a3ba0133a794baa27aa9f96d",
          "sha256": "bc809737c16ffdb0c9287762ca45b99ada3fba1b62ae4352dd5526f140e25895",
          "sha1": "fa51e6302dad11c0a6a597fddaf348e5fcb99c45",
          "md5": "89324bb8c3f080fddfd73468fef2e44f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+26.1.jar",
          "url": "packed_packs_api-common-2.2.3+26.1.jar",
          "size": 31930,
          "sha512": "bf24774d32d8eed9483e3ee5ec589a94ead5d8e69be25144e7b050d21ba35cd12fbbe604337c4536d1615a9887a58b2a5a5bc009a3ba0133a794baa27aa9f96d",
          "sha256": "bc809737c16ffdb0c9287762ca45b99ada3fba1b62ae4352dd5526f140e25895",
          "sha1": "fa51e6302dad11c0a6a597fddaf348e5fcb99c45",
          "md5": "89324bb8c3f080fddfd73468fef2e44f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+26.1-sources.jar",
          "url": "packed_packs_api-common-2.2.3+26.1-sources.jar",
          "size": 19058,
          "sha512": "52cb8c2275cf1cc3ca906f7bf1ebed5a5b1ecee83b3d0aee8027995b2891349305c5b2698d84647dd3b0e94e57d9c3be10eda7c9bde0234b01e259e48195ad48",
          "sha256": "be884312cb5403cd6cbef89f7740c067bea72e753031cf162993267c180c03bd",
          "sha1": "250f9a9fa28b421b084f1b290331c7671cef057d",
          "md5": "f2ef4b32c8ec3418ab9f0e75b959b272"
        }
      ]
    }
  ]
}
