{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.7.2+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.2+26.3.jar",
          "url": "fidgetz-fabric-0.7.2+26.3.jar",
          "size": 447794,
          "sha512": "35b82c3cfae743ddbe449843edfd2566876712737a8ba33a906b3d6d325947f0888852f0a8f100ca54c7fe9e6e072d3c7a832f7ca52921ecbf34074c174ade15",
          "sha256": "f9cd2c08300318c72ee309f414a67754712c3cc1f5f65f746878b26fbf539406",
          "sha1": "6b44f4cc3866f8af32395cefb1ed1da618d897bb",
          "md5": "c7120a884b4c60ec37c4ccd76323964a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.3+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.7.2+26.3.jar",
          "url": "fidgetz-fabric-0.7.2+26.3.jar",
          "size": 447794,
          "sha512": "35b82c3cfae743ddbe449843edfd2566876712737a8ba33a906b3d6d325947f0888852f0a8f100ca54c7fe9e6e072d3c7a832f7ca52921ecbf34074c174ade15",
          "sha256": "f9cd2c08300318c72ee309f414a67754712c3cc1f5f65f746878b26fbf539406",
          "sha1": "6b44f4cc3866f8af32395cefb1ed1da618d897bb",
          "md5": "c7120a884b4c60ec37c4ccd76323964a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.2+26.3-sources.jar",
          "url": "fidgetz-fabric-0.7.2+26.3-sources.jar",
          "size": 164516,
          "sha512": "564272fca1fc04297bd493974e12f1463495db1b2ed3af2e63431691b0cb4312b6528c1a276739c6ac5f48e59f9daacc67ecde103c8448043327f023b6ff0ed8",
          "sha256": "3c96d133d33de28e751e0d616cbf7acd3fbb8dfdcb6bd036726bd2adfbcfd7a4",
          "sha1": "531b0e6085002e5313684e437af8b1f07df9764f",
          "md5": "1083b3df92b03fae824b32c94dc4b017"
        }
      ]
    }
  ]
}
