{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.2.jar",
          "url": "packed_packs_api-common-2.3.1+26.2.jar",
          "size": 32024,
          "sha512": "b96dcf368aa63bf75d46f2615eca5038f7497968501320bdf1bbaeec7172b63f744e262df3fdda8623a2adc53a9eb0622c116fd6bac0f19ce69420823701c92c",
          "sha256": "20b8e4f8ed187d175a54f4b88bb8d7a3de2562645acfe34cc8fc17dc0f010e89",
          "sha1": "32d9e5b5771dad16bd81c768cab0f0e9c07bb027",
          "md5": "3506e5d8180046132b262a0adbac785f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.2.jar",
          "url": "packed_packs_api-common-2.3.1+26.2.jar",
          "size": 32024,
          "sha512": "b96dcf368aa63bf75d46f2615eca5038f7497968501320bdf1bbaeec7172b63f744e262df3fdda8623a2adc53a9eb0622c116fd6bac0f19ce69420823701c92c",
          "sha256": "20b8e4f8ed187d175a54f4b88bb8d7a3de2562645acfe34cc8fc17dc0f010e89",
          "sha1": "32d9e5b5771dad16bd81c768cab0f0e9c07bb027",
          "md5": "3506e5d8180046132b262a0adbac785f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.2-sources.jar",
          "url": "packed_packs_api-common-2.3.1+26.2-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
