{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.6.0+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.0+1.21.2.jar",
          "url": "minecraft-cursor-fabric-api-3.6.0+1.21.2.jar",
          "size": 12228,
          "sha512": "7820bc5adcb1ae0a62944012ced832e395862b884263ff0dc6d53775dd976a09f83a79e5711826ccb90c4d827d277f91b52cd3b1f825a6f7410535a965d839f5",
          "sha256": "c0484d3ff678401910df5b9d49f4cbb3cd9199d2bb50ccf40f9bc68e83fe14cf",
          "sha1": "7610426ee33909fca7e28df35736d430dc01363a",
          "md5": "01ce9806ac70150be8951421a64016c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.0+1.21.2.jar",
          "url": "minecraft-cursor-fabric-api-3.6.0+1.21.2.jar",
          "size": 12228,
          "sha512": "7820bc5adcb1ae0a62944012ced832e395862b884263ff0dc6d53775dd976a09f83a79e5711826ccb90c4d827d277f91b52cd3b1f825a6f7410535a965d839f5",
          "sha256": "c0484d3ff678401910df5b9d49f4cbb3cd9199d2bb50ccf40f9bc68e83fe14cf",
          "sha1": "7610426ee33909fca7e28df35736d430dc01363a",
          "md5": "01ce9806ac70150be8951421a64016c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.6.0+1.21.2-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.6.0+1.21.2-sources.jar",
          "size": 12285,
          "sha512": "617731202940d03e4cb5ae918e15a414b3bf302501ade31ef587f1346e2f709dff93f9acfca60e5a97f0d2c92bf6f6e9a5f254623207f966f74f3bee2e7fed32",
          "sha256": "c19fed842829912df10f8995b84b89d387ba42735b6748511d89a2444d1f60cb",
          "sha1": "fa436f3ee6ce4d257f50ecdeee16dc8e4b3fd561",
          "md5": "bae5314c33a66d199e36487a32cd1f52"
        }
      ]
    }
  ]
}
