{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.6.6+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.6+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.6+1.21.4.jar",
          "url": "minecraft-cursor-fabric-3.6.6+1.21.4.jar",
          "size": 198908,
          "sha512": "b08e99659e801c2005109456beeed69c867fda4a47ec198055a6fa9a964877903a9f763e68b93f2d90a008b06a00512ea41b1eb46327b26b2b9dd2b243a66149",
          "sha256": "8b575797096e00645b77172d295af92dc4d00188256e0cc44686657cb823c425",
          "sha1": "8d814b0d86349a62d4bc24e460a64beea40da451",
          "md5": "409b2db7df83408b4069fbc0b38f3829"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.6+1.21.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.114.0+1.21.4"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "13.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.6+1.21.4.jar",
          "url": "minecraft-cursor-fabric-3.6.6+1.21.4.jar",
          "size": 198908,
          "sha512": "b08e99659e801c2005109456beeed69c867fda4a47ec198055a6fa9a964877903a9f763e68b93f2d90a008b06a00512ea41b1eb46327b26b2b9dd2b243a66149",
          "sha256": "8b575797096e00645b77172d295af92dc4d00188256e0cc44686657cb823c425",
          "sha1": "8d814b0d86349a62d4bc24e460a64beea40da451",
          "md5": "409b2db7df83408b4069fbc0b38f3829"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.6+1.21.4-sources.jar",
          "url": "minecraft-cursor-fabric-3.6.6+1.21.4-sources.jar",
          "size": 100811,
          "sha512": "b5fe71cdf8f91fe817f2b9c27551fac86dfaec1d2fbcb95df1a516965c516e85d76978b14fef1880f63f161870701de02de28f59e6fd86f0e614943647b90712",
          "sha256": "2950508dd2b692098449155fec76d67434d68c177fd31a9adf2c968a97f0c449",
          "sha1": "a8ecef91e9567e63e05102836a226e6d18ebf9d0",
          "md5": "1293a6e89cf80c1f656bae3629fd43e3"
        }
      ]
    }
  ]
}
