{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.3+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.2.3+1.21.11.jar",
          "size": 33203,
          "sha512": "3b885ccfa9943300531deaa3e6809e1537d28a101d435f4b5865a526c462c860b5edb2f995dcd246a2254502ca0c5fca9121f52cbd29ad7722bbb6464945c68e",
          "sha256": "9084a2f17b0ba15bb80d13421b456a0d6504c93c9573dbe79b02c941240691b2",
          "sha1": "e500f74148f336f48480f7cd1f894d91e60f2ab6",
          "md5": "be7843e17f48a55c800de40100e05992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.2.3+1.21.11.jar",
          "size": 33203,
          "sha512": "3b885ccfa9943300531deaa3e6809e1537d28a101d435f4b5865a526c462c860b5edb2f995dcd246a2254502ca0c5fca9121f52cbd29ad7722bbb6464945c68e",
          "sha256": "9084a2f17b0ba15bb80d13421b456a0d6504c93c9573dbe79b02c941240691b2",
          "sha1": "e500f74148f336f48480f7cd1f894d91e60f2ab6",
          "md5": "be7843e17f48a55c800de40100e05992"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.3+1.21.11-sources.jar",
          "url": "packed_packs_api-fabric-2.2.3+1.21.11-sources.jar",
          "size": 19886,
          "sha512": "e6e9c261a50b1d12e87c109593eabd7fba0c68a2a45603906496792257cfdba46e9e76c6a3a17c4eb3f6c2f67330bbfcbd29fac7ed0029780f1f3b5767a174ba",
          "sha256": "936f3e5ca16a65857350a31ce351d195681415da387b9f8adf3314d9a8be738e",
          "sha1": "2144c41405753282484908ade133d77d931ab1eb",
          "md5": "b1c54ab2d9b5150435bde161243ea1f2"
        }
      ]
    }
  ]
}
