{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.3+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1.jar",
          "size": 654533,
          "sha512": "29b2b43536623f2792e23e49c9b8670664ec07138e22aa54b8bfbfd902c272afea236d39c3832d166df35f1d1815e34d4b88aea8783e5a5044367a976438a456",
          "sha256": "eda0b90fa838e0a8599e9eee6f9be86de49f262325ae3a23346f5176f60d8f85",
          "sha1": "ce0546d8b38ea83188c8ddd92c4a9f8b408a0274",
          "md5": "afeafcd36629041b0793d3e7fdf5a2e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.3+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1.jar",
          "size": 654533,
          "sha512": "29b2b43536623f2792e23e49c9b8670664ec07138e22aa54b8bfbfd902c272afea236d39c3832d166df35f1d1815e34d4b88aea8783e5a5044367a976438a456",
          "sha256": "eda0b90fa838e0a8599e9eee6f9be86de49f262325ae3a23346f5176f60d8f85",
          "sha1": "ce0546d8b38ea83188c8ddd92c4a9f8b408a0274",
          "md5": "afeafcd36629041b0793d3e7fdf5a2e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.3+1.21.1-sources.jar",
          "size": 178150,
          "sha512": "aba378b381e863ff50a546a275607ec65c9d6f7ebd9d470b35656e0a3f2632aab3cf826aaf48bd6d232d9f794446a4161d7b72614bfa7f16550cf9a7849f71ff",
          "sha256": "fd211d0f7ee7bd14069eb559354d7fe03d7e0b48ac0fbbcd28534e46c3d7aa67",
          "sha1": "438d59b0853f1ae14483727715c3e8f9470f679c",
          "md5": "1d10b59cc3490b06d8b6bbc12fce4051"
        }
      ]
    }
  ]
}
