{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.6.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.6.2+1.21.1.jar",
          "url": "fidgetz-fabric-0.6.2+1.21.1.jar",
          "size": 337920,
          "sha512": "8a05484a59076bc17a9d14fee51fd96a349c73b1852cc178b93708f32d42d77a5e0875cd82b9b0872ee26d892a47b46a0011e724fbc385f752324e4283395d5b",
          "sha256": "13e8502f00538f3d2069aeeea6bad033c524926e9298a08af6a271d54ccadfd3",
          "sha1": "8f4b9708b9fe77e5c2a909a253286a6278685a9b",
          "md5": "5e1c55e1fa785480a3a1196046e89bc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.12+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.6.2+1.21.1.jar",
          "url": "fidgetz-fabric-0.6.2+1.21.1.jar",
          "size": 337920,
          "sha512": "8a05484a59076bc17a9d14fee51fd96a349c73b1852cc178b93708f32d42d77a5e0875cd82b9b0872ee26d892a47b46a0011e724fbc385f752324e4283395d5b",
          "sha256": "13e8502f00538f3d2069aeeea6bad033c524926e9298a08af6a271d54ccadfd3",
          "sha1": "8f4b9708b9fe77e5c2a909a253286a6278685a9b",
          "md5": "5e1c55e1fa785480a3a1196046e89bc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.6.2+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.6.2+1.21.1-sources.jar",
          "size": 127841,
          "sha512": "468cff338a891966e1221e87c96523d0fadd9ce192809e8ffb1038e3b4616f0dde68148f1c65847e10b7257f0361e5bf03e1387ad426e7e058dfe94f526c4569",
          "sha256": "902221d286720d47a0df379b435e04cf05feb46817f8b3231bbdc47baaaa5879",
          "sha1": "5817e03acc3ad5f412d5eef24ee75259f9772e92",
          "md5": "311ae91ad3d13b2c43278eaa05185f44"
        }
      ]
    }
  ]
}
