{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.9.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.4.jar",
          "size": 11194,
          "sha512": "001adfa4c3e0d2f9a8f212e42899473496fa7f070afcb43cf6149d17b92037c5755d4b3622667aa0d02ca9ab12281f48fd811301b83dc7319e70113d7db59a76",
          "sha256": "6dcd5f5ab834ee1e534d3a04259ee0f9b28b791beddec69108b02798706833ca",
          "sha1": "d0a346d2f4940abb8d90519a731741ae30f6e73e",
          "md5": "b5e61799c96c59fb93f66e390156b7f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.4.jar",
          "size": 11194,
          "sha512": "001adfa4c3e0d2f9a8f212e42899473496fa7f070afcb43cf6149d17b92037c5755d4b3622667aa0d02ca9ab12281f48fd811301b83dc7319e70113d7db59a76",
          "sha256": "6dcd5f5ab834ee1e534d3a04259ee0f9b28b791beddec69108b02798706833ca",
          "sha1": "d0a346d2f4940abb8d90519a731741ae30f6e73e",
          "md5": "b5e61799c96c59fb93f66e390156b7f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.9.0+1.21.4-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.9.0+1.21.4-sources.jar",
          "size": 10501,
          "sha512": "7254c1c88731ef71b9dce6aab392f30b083ce14d2c63d7aa52f5b28f68b4f4988958fa2e4aaba8149b3e67746b8e616c90245d06d3a36f9e600e8529af89e6dd",
          "sha256": "a2e32f43360d590508133f0b328225e24b41d0a247e3d1cfe4a7bb0de33f7106",
          "sha1": "53643d8b0270abfa3723af1f6750e0369f6dc7af",
          "md5": "0e38fa057970d0ab8e12b78f1547d9a4"
        }
      ]
    }
  ]
}
