{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.2.1+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.1+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.5.2+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.1+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.1+1.21.11.jar",
          "size": 797203,
          "sha512": "5f80f167ffd60e6895acb2ded735e43d7cb1114b18e35aa742af2962ff3a2e2a7f4257b709ad29e4cd0488ba0fb0b2ebc5b57a30dec4aec62d59e1f1e7f16c53",
          "sha256": "9f234ce7eb3415cd6206f62f3c4837efe7e0976271ce1e8cbe5fec92f392b62c",
          "sha1": "68e765ba891c2f1e6cc6f3116d744afae41150ac",
          "md5": "5afe9e86df1cd2d6b17468ed617bd96f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.2.1+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.5.2+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.2.1+1.21.11.jar",
          "url": "packed_packs-fabric-2.2.1+1.21.11.jar",
          "size": 797203,
          "sha512": "5f80f167ffd60e6895acb2ded735e43d7cb1114b18e35aa742af2962ff3a2e2a7f4257b709ad29e4cd0488ba0fb0b2ebc5b57a30dec4aec62d59e1f1e7f16c53",
          "sha256": "9f234ce7eb3415cd6206f62f3c4837efe7e0976271ce1e8cbe5fec92f392b62c",
          "sha1": "68e765ba891c2f1e6cc6f3116d744afae41150ac",
          "md5": "5afe9e86df1cd2d6b17468ed617bd96f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.2.1+1.21.11-sources.jar",
          "url": "packed_packs-fabric-2.2.1+1.21.11-sources.jar",
          "size": 188616,
          "sha512": "dd30db49d7ea3d9208eca96bc4faf1817f37d07143a86628bee1a2400b16d23780640472f4b6ce49ec988a51bb6fb465b2c7745eb2bcaf971518a97199215528",
          "sha256": "6c94e7190e4859bbf8357b84e18a34445740eae38d675f9d2386594fba656b44",
          "sha1": "ff0e51e2a75e192c2ee6da9520968c03c4df761e",
          "md5": "6139720fe44c8931e4bc1e87201b2b7e"
        }
      ]
    }
  ]
}
