{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.6.7+1.21.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.7+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.7+1.21.2.jar",
          "url": "minecraft-cursor-fabric-3.6.7+1.21.2.jar",
          "size": 192344,
          "sha512": "7ac0ac264d041895401dc796d7886ab26518e7dc575ae646188fa13677ae302156febf3b6e582cb71414f955cc042101095ec23b9fd7f3c0f91fc7944184adbd",
          "sha256": "daf2c604f166fec1d03e332dd6631185937bf0b227442a0468d877de7a0a5c57",
          "sha1": "844f19c051cba925ed823599fa79c6e91715976b",
          "md5": "fe9583699a49225d2e067d07be8efead"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.7+1.21.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.106.1+1.21.2"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.7+1.21.2.jar",
          "url": "minecraft-cursor-fabric-3.6.7+1.21.2.jar",
          "size": 192344,
          "sha512": "7ac0ac264d041895401dc796d7886ab26518e7dc575ae646188fa13677ae302156febf3b6e582cb71414f955cc042101095ec23b9fd7f3c0f91fc7944184adbd",
          "sha256": "daf2c604f166fec1d03e332dd6631185937bf0b227442a0468d877de7a0a5c57",
          "sha1": "844f19c051cba925ed823599fa79c6e91715976b",
          "md5": "fe9583699a49225d2e067d07be8efead"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.7+1.21.2-sources.jar",
          "url": "minecraft-cursor-fabric-3.6.7+1.21.2-sources.jar",
          "size": 98223,
          "sha512": "46ee0d6e312b9519bdf1575896793e347d32e2ac26bd7a6444189eafcf5655aa0cef024b3e16fe4717b08ce37cc5f20bba990d8123cc0176b6cfd686125431a3",
          "sha256": "d790be971b0cb75ff03124a9b8308e5ff1450ca58c9d19974343eecbf3ed87b9",
          "sha1": "8df30f7fa53a94cc113397d8d132e035c7bf9992",
          "md5": "26cd899b9935534136b0abc327856143"
        }
      ]
    }
  ]
}
