{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.2+1.21.1.jar",
          "size": 26479,
          "sha512": "37591eb047afdcb7ef653b77cd4923d9470d9e4031ed633068c6dca5e35cb3519d6c5bc2fba034de3f8983542fe1ad2530906a02c81c25a1d712f52658c8a8e2",
          "sha256": "b1ad5db8d8331ba7ca120f67a49b82204d00648aa92213c62eb828bf730bb4af",
          "sha1": "5201519dd953c2b2089f2bda8f4f9fe6cae17aef",
          "md5": "11382a1b9852f94b779427ea12dc6967"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.2+1.21.1.jar",
          "size": 26479,
          "sha512": "37591eb047afdcb7ef653b77cd4923d9470d9e4031ed633068c6dca5e35cb3519d6c5bc2fba034de3f8983542fe1ad2530906a02c81c25a1d712f52658c8a8e2",
          "sha256": "b1ad5db8d8331ba7ca120f67a49b82204d00648aa92213c62eb828bf730bb4af",
          "sha1": "5201519dd953c2b2089f2bda8f4f9fe6cae17aef",
          "md5": "11382a1b9852f94b779427ea12dc6967"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.2+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.2+1.21.1-sources.jar",
          "size": 14870,
          "sha512": "bd8a46e4e224827959e1602b7b0aa2db9a77400dc982628f2de19f55eca0572336c7409f77217103b0223fa762120e11ef4a49b942034fb34d664c692bd74ce0",
          "sha256": "8e6eabec550669705b40d54960f3c26fd893a83515defc1d6329bf8630815c54",
          "sha1": "dc4bbd5e75f0d5a72d42900399299409ac0b9dd0",
          "md5": "3f7c5835b792bcae009ac1b12a0f0755"
        }
      ]
    }
  ]
}
