{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.2+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.2+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.2+26.1.jar",
          "url": "packed_packs-fabric-2.1.2+26.1.jar",
          "size": 683031,
          "sha512": "811ba1d8ee7710701ab69ddc16869834e5c5c0fb00a98768da944e0fb72a41c6c8e2408da580e2661bfd7626e4d9cea06a984c4129807989c2b2bb42807acf01",
          "sha256": "3e10e8dc88804525d18284a7fff95cee68f94701c17f90f2f3ea30a47709e3c4",
          "sha1": "4da19178786f521b71233148f105e5d8709a4f48",
          "md5": "5e33d66a775433da6f1d33d68e104f14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.143.15+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0+26.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.2+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.2+26.1.jar",
          "url": "packed_packs-fabric-2.1.2+26.1.jar",
          "size": 683031,
          "sha512": "811ba1d8ee7710701ab69ddc16869834e5c5c0fb00a98768da944e0fb72a41c6c8e2408da580e2661bfd7626e4d9cea06a984c4129807989c2b2bb42807acf01",
          "sha256": "3e10e8dc88804525d18284a7fff95cee68f94701c17f90f2f3ea30a47709e3c4",
          "sha1": "4da19178786f521b71233148f105e5d8709a4f48",
          "md5": "5e33d66a775433da6f1d33d68e104f14"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.2+26.1-sources.jar",
          "url": "packed_packs-fabric-2.1.2+26.1-sources.jar",
          "size": 209200,
          "sha512": "7fe0fb5384da31d9a39ca8986e5e55f78aea171a84563042a114d43f0f0e3ec09247d09bc7c9e133278d8557e0c030fa297a408a814aba239022713254a478ff",
          "sha256": "807e2edbfc4f67e4f6594c5928205eaa28d7bf860514f58b551a66761b0459b1",
          "sha1": "c649d73a29f372691e4f4c3ce06b8df69c4018a4",
          "md5": "ae825f8df1031d1474dce5f3e5355da3"
        }
      ]
    }
  ]
}
