{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "size": 184673,
          "sha512": "f9a45e04535830bcd444761936ab6e8d281a9e606f77c1e8e2fa11f878b737ef7da2d861e5f12f6057f511b12dd018f0429470794fa78e8bda5564ae88a9dc96",
          "sha256": "876d669f1a80b3d24fcb34e7467467a6313c10b57816e0f7a7e3c6ee7a5344d7",
          "sha1": "b69ccd46d3d7ea1c0ffb43c44608212233e9607d",
          "md5": "0b4fa8995acb15b34efcee8c13c283c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "size": 184673,
          "sha512": "f9a45e04535830bcd444761936ab6e8d281a9e606f77c1e8e2fa11f878b737ef7da2d861e5f12f6057f511b12dd018f0429470794fa78e8bda5564ae88a9dc96",
          "sha256": "876d669f1a80b3d24fcb34e7467467a6313c10b57816e0f7a7e3c6ee7a5344d7",
          "sha1": "b69ccd46d3d7ea1c0ffb43c44608212233e9607d",
          "md5": "0b4fa8995acb15b34efcee8c13c283c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1-sources.jar",
          "size": 80879,
          "sha512": "8101601806e76ae6efa3d7d083629699bacaaa115b28ab6da6013bd119bfd7d880933b3a48609e5fd250e7f03573dc5f2a23f5d198b6e7302a00393d1e5f4977",
          "sha256": "44f722441f0d22653ea3d09d31671f75799f96d2350512c5d7005a844e9b60bd",
          "sha1": "5a1dfdf1a0fc6dc12713bd73b71d938cc13a31cb",
          "md5": "1e63283d087629ae2c12248699e81b05"
        }
      ]
    }
  ]
}
