{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "size": 184673,
          "sha512": "f9a45e04535830bcd444761936ab6e8d281a9e606f77c1e8e2fa11f878b737ef7da2d861e5f12f6057f511b12dd018f0429470794fa78e8bda5564ae88a9dc96",
          "sha256": "876d669f1a80b3d24fcb34e7467467a6313c10b57816e0f7a7e3c6ee7a5344d7",
          "sha1": "b69ccd46d3d7ea1c0ffb43c44608212233e9607d",
          "md5": "0b4fa8995acb15b34efcee8c13c283c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1.jar",
          "size": 184673,
          "sha512": "f9a45e04535830bcd444761936ab6e8d281a9e606f77c1e8e2fa11f878b737ef7da2d861e5f12f6057f511b12dd018f0429470794fa78e8bda5564ae88a9dc96",
          "sha256": "876d669f1a80b3d24fcb34e7467467a6313c10b57816e0f7a7e3c6ee7a5344d7",
          "sha1": "b69ccd46d3d7ea1c0ffb43c44608212233e9607d",
          "md5": "0b4fa8995acb15b34efcee8c13c283c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.1.0+1.21.1-sources.jar",
          "size": 80879,
          "sha512": "6bb723db285d0b82d9b40e4bfbc6daf002a5b5ed9f6f4424d2fbaa421c6c9129c4de023ee05b5086ef75f40930ec80002bd129ac397c15d517ed9059f6234072",
          "sha256": "3aa2bf07a4b019cf6c8c4fccab025db6b6595823a115ff24571b680239740edb",
          "sha1": "cad31cc9315648261c0fc87a734d50a7bf840020",
          "md5": "0461df2152c9920e3ed6105a9043d51a"
        }
      ]
    }
  ]
}
