{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.2.6+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.6+26.3"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.1+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.6+26.3.jar",
          "url": "packed_packs-neoforge-2.2.6+26.3.jar",
          "size": 903283,
          "sha512": "087674176d4368c0628c6cf568d987e52af86ba8399beed678f55a8cb5ffbb5e6067c3b3e73255ac065adf6fdc45faf058ce0bd1d82d650b59eb35c27a5806d6",
          "sha256": "7646c2b485b2d517e64aad5d36dae0956332dcda811bc8bdd9c9b245cfb7e708",
          "sha1": "d7f3080e8bf82472a9a6d1e24c560c133a9979c2",
          "md5": "579bdc447c306faec8387f7e230e1e22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.6+26.3"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.7.1+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.6+26.3.jar",
          "url": "packed_packs-neoforge-2.2.6+26.3.jar",
          "size": 903283,
          "sha512": "087674176d4368c0628c6cf568d987e52af86ba8399beed678f55a8cb5ffbb5e6067c3b3e73255ac065adf6fdc45faf058ce0bd1d82d650b59eb35c27a5806d6",
          "sha256": "7646c2b485b2d517e64aad5d36dae0956332dcda811bc8bdd9c9b245cfb7e708",
          "sha1": "d7f3080e8bf82472a9a6d1e24c560c133a9979c2",
          "md5": "579bdc447c306faec8387f7e230e1e22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.6+26.3-sources.jar",
          "url": "packed_packs-neoforge-2.2.6+26.3-sources.jar",
          "size": 182943,
          "sha512": "d27b4f14d8018fa5ceab37f19ca8169b567d7b00a9d6460608ad613f3a11119f868ae7aef52dae8d271da1b66719f1524c89376a7b1b519a67d1f0e490d48034",
          "sha256": "0d07415ace181b985d02d446e8575b7d5b3609bb97672be74fc09836234214cd",
          "sha1": "7912f451cfbc2bba9fa7147fe0a3e6143b105098",
          "md5": "15634bb55bcbf5ba666b558c49b90ecb"
        }
      ]
    }
  ]
}
