{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1.jar",
          "size": 27535,
          "sha512": "b32c8b7520a29db2d510a5666e42250b3c0785c5de75f806ab5947348a526a364541ae882f1c9e0fbe27138a417c817779430935d97b7affa79f02632c8d4e48",
          "sha256": "c605087af6c6bb07f770e8b77feb2230fe05ccfdcaff3afb768faee68d717068",
          "sha1": "fb176e889fd204ec49931b0663cd86974cef20df",
          "md5": "3b9624de68736a2e90b09c0b975904df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1.jar",
          "size": 27535,
          "sha512": "b32c8b7520a29db2d510a5666e42250b3c0785c5de75f806ab5947348a526a364541ae882f1c9e0fbe27138a417c817779430935d97b7affa79f02632c8d4e48",
          "sha256": "c605087af6c6bb07f770e8b77feb2230fe05ccfdcaff3afb768faee68d717068",
          "sha1": "fb176e889fd204ec49931b0663cd86974cef20df",
          "md5": "3b9624de68736a2e90b09c0b975904df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.5+1.21.1-sources.jar",
          "size": 17425,
          "sha512": "6f78da97e6d6b42c3247436a812290d179d33ce69b0ccf207a36aaa694aeeb8ebeaa5d148f828aa44ff003c3251dde1bd36da7e9ed3e0e5ea3dcffd966c4ba4e",
          "sha256": "7e90944445b50903c34ffe3d1a56783a09cb980fef6a1fe8faace35a253bb281",
          "sha1": "260d77a6466356748d28543cd4909c10424af1b5",
          "md5": "a67e6347191ed459cccccd73b1dfe505"
        }
      ]
    }
  ]
}
