{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1.jar",
          "url": "fidgetz-common-0.1.0+1.21.1.jar",
          "size": 176694,
          "sha512": "a4d1760324eec6db561c09cb9d215359415c3a3daeceb642c233e89e5b82a7b05f3b75ea7ecfee557a671f5d05d2dad48434e156a76843e7f3515b7b77d82555",
          "sha256": "8477c5ee77fb83f398e2c5a58b539e300c736e875f64ba99fe9a85db44d1d32c",
          "sha1": "a58d6eabddc5882eda9ed32cc0725cf934c0303e",
          "md5": "fe85954d81993c5ef872601407d258bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1.jar",
          "url": "fidgetz-common-0.1.0+1.21.1.jar",
          "size": 176694,
          "sha512": "a4d1760324eec6db561c09cb9d215359415c3a3daeceb642c233e89e5b82a7b05f3b75ea7ecfee557a671f5d05d2dad48434e156a76843e7f3515b7b77d82555",
          "sha256": "8477c5ee77fb83f398e2c5a58b539e300c736e875f64ba99fe9a85db44d1d32c",
          "sha1": "a58d6eabddc5882eda9ed32cc0725cf934c0303e",
          "md5": "fe85954d81993c5ef872601407d258bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-common-0.1.0+1.21.1-sources.jar",
          "size": 70943,
          "sha512": "b0bfebbfd3a5588da6fa60292b914188ee6b7102698babc4a5f8eae83f3321f1f4362cdb8340c97329acf3b9665c4f4046dc49582aeef7186951fc6f1311e29e",
          "sha256": "7683e9621c88097b98c5c3d13fef2a0d319a19488616de178421e36c7d0a1ca4",
          "sha1": "2d64dd5f80f4300b7c4aa556d57e37e8943be9ac",
          "md5": "fbeec0b693693b3203461e16afed3465"
        }
      ]
    }
  ]
}
