{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1.jar",
          "url": "fidgetz-common-0.1.0+1.21.1.jar",
          "size": 176694,
          "sha512": "195e7363c6fdeaa4237f89324bbd37b5881ff4e3b213c2e63c733f5462766e41efeb2ed292aa61ec33f7c587c854cc390e7ddba72e5e4ce6c5217ca83764c83c",
          "sha256": "8e92033d88212ca1ee11234550bdedca748b474a3f1ac4db67b233f8a1fa7417",
          "sha1": "d41be18734dd772ea4fcb24f981befbd500a742b",
          "md5": "082400f249fdf61144f76a5c0460341a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1.jar",
          "url": "fidgetz-common-0.1.0+1.21.1.jar",
          "size": 176694,
          "sha512": "195e7363c6fdeaa4237f89324bbd37b5881ff4e3b213c2e63c733f5462766e41efeb2ed292aa61ec33f7c587c854cc390e7ddba72e5e4ce6c5217ca83764c83c",
          "sha256": "8e92033d88212ca1ee11234550bdedca748b474a3f1ac4db67b233f8a1fa7417",
          "sha1": "d41be18734dd772ea4fcb24f981befbd500a742b",
          "md5": "082400f249fdf61144f76a5c0460341a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.1.0+1.21.1-sources.jar",
          "url": "fidgetz-common-0.1.0+1.21.1-sources.jar",
          "size": 70943,
          "sha512": "f6f28010e485ad36a77d2827302726b9a6cc1907bc22effa88b21d5ba64ab059792c28823254833a17213c0b17b924e71540da0018e8ebce482182301a569162",
          "sha256": "0697ecf0939bcba075aa1543ae9e26f8ab74c9b7da3077813cc5bc2c2d21a83c",
          "sha1": "f5476a2270989e9df6db894668224be439ba3789",
          "md5": "bc42f6a599e206a448cc966dda62bc6d"
        }
      ]
    }
  ]
}
