{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.11+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1.jar",
          "size": 27188,
          "sha512": "6024a01738e3c8c8949c7f15c3501d06caa469501b69bbdef22f15a54b1e4792853183cf27ad3666a63963d31e2d9d08c863c57883914bf78b5be54498b89898",
          "sha256": "de16001f99d4b19c1eee9b9fb7eb3d619673f4939e49bb915788566f4d58c9ae",
          "sha1": "6285564c688448efc4ac0c55dca990b967b964d8",
          "md5": "0af079a5a1c80d75e37aaa0062f815e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1.jar",
          "size": 27188,
          "sha512": "6024a01738e3c8c8949c7f15c3501d06caa469501b69bbdef22f15a54b1e4792853183cf27ad3666a63963d31e2d9d08c863c57883914bf78b5be54498b89898",
          "sha256": "de16001f99d4b19c1eee9b9fb7eb3d619673f4939e49bb915788566f4d58c9ae",
          "sha1": "6285564c688448efc4ac0c55dca990b967b964d8",
          "md5": "0af079a5a1c80d75e37aaa0062f815e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.11+1.21.1-sources.jar",
          "size": 17380,
          "sha512": "e2c2ea2f9a24971b9a87415c47ba4473e28f57e452ad8cca93cb3fd5172bf40c7e22553da147f1478c9e4680d298a55f9d4c7545e87c6c386f9aad64a7bbbb3e",
          "sha256": "faa8dcaae795dc325ebc5a52ebb151ae7896b6b35d934e972436574faa38bd27",
          "sha1": "385e0e72e446bd85ea8a3480383833f5e26189e0",
          "md5": "7a403eb1198925ef68a33e10fb859b2e"
        }
      ]
    }
  ]
}
