{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0-beta.3+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.1.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.1.jar",
          "size": 32030,
          "sha512": "4764c82cab27dcd4ffe75a03dfb38f8a73757062f6d5b3a5cb096fa0a327c7bad33652fc62f9945024d034c2c840cf76f15676de978d360a0742d9426af268b5",
          "sha256": "ca77185568abe411bbb9ebd418f8654c5fcbb208336823a3fbff7844d0412d14",
          "sha1": "1ae5b50d6c2c1e548278606c0d71b7936a9ac421",
          "md5": "258c600795885e5fc706040651b497d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.1.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.1.jar",
          "size": 32030,
          "sha512": "4764c82cab27dcd4ffe75a03dfb38f8a73757062f6d5b3a5cb096fa0a327c7bad33652fc62f9945024d034c2c840cf76f15676de978d360a0742d9426af268b5",
          "sha256": "ca77185568abe411bbb9ebd418f8654c5fcbb208336823a3fbff7844d0412d14",
          "sha1": "1ae5b50d6c2c1e548278606c0d71b7936a9ac421",
          "md5": "258c600795885e5fc706040651b497d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.1-sources.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.1-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
