{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.6+1.21.1.jar",
          "size": 467277,
          "sha512": "d91a99aec3610c14069e6b8169c29603ee1d4339af59c5015a98eec34cac3e3198059af50321a1d2d5350bd2ceb92cf6e322bc4e3dcb1b8af9d640844c80b925",
          "sha256": "e2829d1a117b247a198b87c89632070788f8dead28a723fc6246dd1d43f33090",
          "sha1": "446171548dcbfe35ab1ecb45bea48125a2e1933e",
          "md5": "93934705c141231370ba00b36b1a2776"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.6+1.21.1.jar",
          "size": 467277,
          "sha512": "d91a99aec3610c14069e6b8169c29603ee1d4339af59c5015a98eec34cac3e3198059af50321a1d2d5350bd2ceb92cf6e322bc4e3dcb1b8af9d640844c80b925",
          "sha256": "e2829d1a117b247a198b87c89632070788f8dead28a723fc6246dd1d43f33090",
          "sha1": "446171548dcbfe35ab1ecb45bea48125a2e1933e",
          "md5": "93934705c141231370ba00b36b1a2776"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.6+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.6+1.21.1-sources.jar",
          "size": 175533,
          "sha512": "eabbbbc937a0f70dd64e74dff10e4c66bc542a2e8ba88207e38df938ba6e8b1f09fa1632b0278d019f0f7aa590fcb97a7f7225c610f456a48ff8f76bf7289a3b",
          "sha256": "d59ac82f75cc429afd45e842291839fc49ee0ab84b87e6c304bf8b42c99a489b",
          "sha1": "28089e924373f59290386cc464ccf94b6049199d",
          "md5": "c2ab12abff2da58bf3095d49f221b6eb"
        }
      ]
    }
  ]
}
