{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric-api",
    "version": "3.7.1+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.7.1+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.7.1+1.21.4.jar",
          "size": 10518,
          "sha512": "767de4419f8c074ed4d74488ee3362c1508e57243197f538926252d55a83fb095032f153945fbfa7b63190e5a7aa643ac5cf2b27166a5f5eec028f34bef1eb6f",
          "sha256": "29b087fc836162adc28c5f0f70c2ead06d146f3e11d14338344bab6d17917708",
          "sha1": "51a0ba8c4bab4e2d60b8d657b3be3a108841e994",
          "md5": "5a42f36ffec40cde916c941ba1b4cda7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.7.1+1.21.4.jar",
          "url": "minecraft-cursor-fabric-api-3.7.1+1.21.4.jar",
          "size": 10518,
          "sha512": "767de4419f8c074ed4d74488ee3362c1508e57243197f538926252d55a83fb095032f153945fbfa7b63190e5a7aa643ac5cf2b27166a5f5eec028f34bef1eb6f",
          "sha256": "29b087fc836162adc28c5f0f70c2ead06d146f3e11d14338344bab6d17917708",
          "sha1": "51a0ba8c4bab4e2d60b8d657b3be3a108841e994",
          "md5": "5a42f36ffec40cde916c941ba1b4cda7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-api-3.7.1+1.21.4-sources.jar",
          "url": "minecraft-cursor-fabric-api-3.7.1+1.21.4-sources.jar",
          "size": 10401,
          "sha512": "8a4c6e02fc3438d7c7aa04583402582256ccd62627c4e0a261ac03973c944c9ad51beb8b0a4ac901398136ccecc4098cd6d40fed61bf2f0c4861eb569627bc36",
          "sha256": "c7522dc3b3a8a55341a19d15ca785041e6dd366975bd306b6071ef1960d974fe",
          "sha1": "6c6ce3f4837d1a4c70cd3c086684c22de5641a5c",
          "md5": "50f080cd9430b4ff62912447a1302f5a"
        }
      ]
    }
  ]
}
