{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.4+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "size": 654572,
          "sha512": "16d549f481a406b3590f2a4a259f814ed1a49e0fdf3815300b437e7bf8436a654f0c51136e997d7f7348aa36288d6f5a896bd72421e035d7cfc65bbb58fb75ef",
          "sha256": "8ab6996a7e27a6af77463eae24d783412cad3d5249e9e13bc530d6a527ce2e8c",
          "sha1": "d0974e5ed6af44dce7438fcd60893ef4668e7f87",
          "md5": "3b97279f537742f1d343860623b52993"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.4+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1.jar",
          "size": 654572,
          "sha512": "16d549f481a406b3590f2a4a259f814ed1a49e0fdf3815300b437e7bf8436a654f0c51136e997d7f7348aa36288d6f5a896bd72421e035d7cfc65bbb58fb75ef",
          "sha256": "8ab6996a7e27a6af77463eae24d783412cad3d5249e9e13bc530d6a527ce2e8c",
          "sha1": "d0974e5ed6af44dce7438fcd60893ef4668e7f87",
          "md5": "3b97279f537742f1d343860623b52993"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.4+1.21.1-sources.jar",
          "size": 178161,
          "sha512": "7c9e9a050d90cca4dd07143356dce7ddeb89b2320f566f3a779f11b1c4dcae77eadce319a22a57a878244e03f56d967ab2c77510272a406b6dd63f0b1b1e1e6c",
          "sha256": "8a2b5565910627faa7af6a4b8d2628c47934cfd81351b3d6930a5fc212e05b00",
          "sha1": "21d6a31ca50d4b38b454ef2169c9aea1c981a12a",
          "md5": "4162602c2d5249ead0457827c1de878a"
        }
      ]
    }
  ]
}
