{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0+1.21.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0+1.21.6.jar",
          "url": "packed_packs_api-common-2.1.0+1.21.6.jar",
          "size": 30356,
          "sha512": "6349280f075d20338d38139cb1ee43b2cb176e92a5efde95af2cd484efc45779ce272db06ace84b16decf03e5506b810aafdb43b774ddea81c73309ebd004a81",
          "sha256": "9d6aa05288bce334f7191a927c0a93e4ec894e8a1bea523b6d6fc1efd19638dd",
          "sha1": "6dc6c009f4279dff8636fea7b5cef747af778f71",
          "md5": "72f118b066635ea71fbdf007dfc37366"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0+1.21.6.jar",
          "url": "packed_packs_api-common-2.1.0+1.21.6.jar",
          "size": 30356,
          "sha512": "6349280f075d20338d38139cb1ee43b2cb176e92a5efde95af2cd484efc45779ce272db06ace84b16decf03e5506b810aafdb43b774ddea81c73309ebd004a81",
          "sha256": "9d6aa05288bce334f7191a927c0a93e4ec894e8a1bea523b6d6fc1efd19638dd",
          "sha1": "6dc6c009f4279dff8636fea7b5cef747af778f71",
          "md5": "72f118b066635ea71fbdf007dfc37366"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0+1.21.6-sources.jar",
          "url": "packed_packs_api-common-2.1.0+1.21.6-sources.jar",
          "size": 18189,
          "sha512": "318ee8ad9f4777fce7c97e81d1255d10184c9fd68eae0ab67e5e23c3ade2c475f365a79dd6589ae6c63ac41173234e89fa801ad4a8c1ed73f302999d235a0c49",
          "sha256": "858f0cebf2602eae29dd71060949ba277ebb9aa1376052a539522f9fb163d1a2",
          "sha1": "3423774438f8ef390cbe63f5fb22165a1752a61b",
          "md5": "cbf636fd5465cb860294ef2a1b116af3"
        }
      ]
    }
  ]
}
