{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1.jar",
          "size": 27189,
          "sha512": "94ccc2d73075e590ffa7eb96f69967f75089aa2712484aa14f47bab262b41941759da564f5e617dc07810261148d77290274b46c4f974649d0e6cd41ce664e54",
          "sha256": "52bb9c4dafdcb422863fd13f8cbe0016c694af2e0df74ed4ac6d86f262560648",
          "sha1": "971335d1df911032f1baad39e04faa10c3e85de9",
          "md5": "cf9bcf1fe47760b71f24c0b280283db4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1.jar",
          "size": 27189,
          "sha512": "94ccc2d73075e590ffa7eb96f69967f75089aa2712484aa14f47bab262b41941759da564f5e617dc07810261148d77290274b46c4f974649d0e6cd41ce664e54",
          "sha256": "52bb9c4dafdcb422863fd13f8cbe0016c694af2e0df74ed4ac6d86f262560648",
          "sha1": "971335d1df911032f1baad39e04faa10c3e85de9",
          "md5": "cf9bcf1fe47760b71f24c0b280283db4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.9+1.21.1-sources.jar",
          "size": 17380,
          "sha512": "bc440f48ffcf1e85844714f3d405e82d0c921a61358cb2879f9a8da8e6e85deab8bcb99cbbd33cba562d0944e1678b6bc54c0ef30d8707c400a6a732053e7cd2",
          "sha256": "0fa5ea3cc6ebcfe2e06d3b5cd980c13ed72d9fc33a23d7d0fc315df08f030703",
          "sha1": "ca7244e6ae88f7d832bb390b91719bc9dbb2ddd6",
          "md5": "23c5682a776d941b16bf10501af1c919"
        }
      ]
    }
  ]
}
