{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.6+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.6+26.3.jar",
          "url": "packed_packs_api-common-2.2.6+26.3.jar",
          "size": 31934,
          "sha512": "19ae2f38defc3f1aaf0d7a04070283aac16873b0cfd19e323f2d4506b4c5ea7ee943117214d3eafcd46cdb7314a86be5b29d86d06652f98596ea312324c0997c",
          "sha256": "684788f1d6cf827b80c1d3634fc157edfdee301e87c65816728859303ff9f876",
          "sha1": "ee8aabf9ed3b6ae11ca48efa3a87ad90f74c1464",
          "md5": "c9512bc44adeb8f94188fc6b06a7d97c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.6+26.3.jar",
          "url": "packed_packs_api-common-2.2.6+26.3.jar",
          "size": 31934,
          "sha512": "19ae2f38defc3f1aaf0d7a04070283aac16873b0cfd19e323f2d4506b4c5ea7ee943117214d3eafcd46cdb7314a86be5b29d86d06652f98596ea312324c0997c",
          "sha256": "684788f1d6cf827b80c1d3634fc157edfdee301e87c65816728859303ff9f876",
          "sha1": "ee8aabf9ed3b6ae11ca48efa3a87ad90f74c1464",
          "md5": "c9512bc44adeb8f94188fc6b06a7d97c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.6+26.3-sources.jar",
          "url": "packed_packs_api-common-2.2.6+26.3-sources.jar",
          "size": 19058,
          "sha512": "52cb8c2275cf1cc3ca906f7bf1ebed5a5b1ecee83b3d0aee8027995b2891349305c5b2698d84647dd3b0e94e57d9c3be10eda7c9bde0234b01e259e48195ad48",
          "sha256": "be884312cb5403cd6cbef89f7740c067bea72e753031cf162993267c180c03bd",
          "sha1": "250f9a9fa28b421b084f1b290331c7671cef057d",
          "md5": "f2ef4b32c8ec3418ab9f0e75b959b272"
        }
      ]
    }
  ]
}
