{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.2.0+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.0+26.1.jar",
          "url": "packed_packs_api-neoforge-2.2.0+26.1.jar",
          "size": 32248,
          "sha512": "ec9fc2370d89276befb584a3f4b9bc4ac4fb2277f38e800e9b508e8d7d28ede3599af43f48d6567b2e01b0c56a6e98be8938988d9e035860ca6e13ebed1a327f",
          "sha256": "7bdf7b9e676354211634b71f7f4f5e4946ca148a61d24f2b947bb92f1bddc10b",
          "sha1": "42703bbc55036b6e673691c65a0209ca97ababd9",
          "md5": "551ac22354dadbf6ecc60560b6b5cae5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.0+26.1.jar",
          "url": "packed_packs_api-neoforge-2.2.0+26.1.jar",
          "size": 32248,
          "sha512": "ec9fc2370d89276befb584a3f4b9bc4ac4fb2277f38e800e9b508e8d7d28ede3599af43f48d6567b2e01b0c56a6e98be8938988d9e035860ca6e13ebed1a327f",
          "sha256": "7bdf7b9e676354211634b71f7f4f5e4946ca148a61d24f2b947bb92f1bddc10b",
          "sha1": "42703bbc55036b6e673691c65a0209ca97ababd9",
          "md5": "551ac22354dadbf6ecc60560b6b5cae5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.0+26.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.2.0+26.1-sources.jar",
          "size": 19369,
          "sha512": "baa8c14d4a57246a4a97e3f4cfeda284bd5d750e339977e06ad2a216af24f19be0a3a0b927c8d7d71da126cc94a7bc8e8f9c982eda335c76eed635e962e54c38",
          "sha256": "fd5625a805f4819664d7833c0a29e9c95840b01ac6fbdb528511989733aeb080",
          "sha1": "3311bd1563c76bf1862788ea5e58f9916d6b6e0f",
          "md5": "92bace87032cd3575e7a7b1ec9d1d478"
        }
      ]
    }
  ]
}
