{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0-beta.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+26.2.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+26.2.jar",
          "size": 32408,
          "sha512": "837f4bbed61a4ab898a1d5236166780a51145a55c5bfa3c78e49f669219981b1daed0f525750a4f84a03935348e7a8b72ed1710d6fa6069a5f73745468fb64fa",
          "sha256": "9e9c7dfc2e66b165689edb76bf433cb57231697a0fb538273aac19835a35c841",
          "sha1": "f77717656d09c94aa689eac7edb1b00953ab61cd",
          "md5": "0b777fbdfe087c47430e15fd7ab85b18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+26.2.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+26.2.jar",
          "size": 32408,
          "sha512": "837f4bbed61a4ab898a1d5236166780a51145a55c5bfa3c78e49f669219981b1daed0f525750a4f84a03935348e7a8b72ed1710d6fa6069a5f73745468fb64fa",
          "sha256": "9e9c7dfc2e66b165689edb76bf433cb57231697a0fb538273aac19835a35c841",
          "sha1": "f77717656d09c94aa689eac7edb1b00953ab61cd",
          "md5": "0b777fbdfe087c47430e15fd7ab85b18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.1+26.2-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.1+26.2-sources.jar",
          "size": 19466,
          "sha512": "a166af16de1fb11d616a169e915dc3ea7c2f7f2a0fd9f7ea36a59067dbec6de087abc6032e985975f6002fceab673d7a88e3a9fcfc69412dc8998c84599245ed",
          "sha256": "c50ac8ab33ad664b81ec5a8edd7a5c122322e494ed1dad2c30661ae6df99a6c8",
          "sha1": "9eeefdeef79d733aa86129700ccdb6ce481e1cef",
          "md5": "cf35879e748902d2b85cbadb3c27d038"
        }
      ]
    }
  ]
}
