{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.11.2+1.21.2-patch.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.11.2+1.21.2-patch.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1.jar",
          "size": 290827,
          "sha512": "83e1cdcac0e1a253e8bc18446ffd1f18bda7f4d58cb07a3b84d127a536d6e2fe6398a64e91368c5d68a730460d98b8879591093e104e4ac42d827544ba7f7513",
          "sha256": "656ff829587f5582f30162ec9ceccb223906e9a1b6101dccd32441292c76537a",
          "sha1": "c571bff2bfd4f1a859604b107eac34e8e9c3634a",
          "md5": "ce7c444de7e5966ab60beaceb9f20bec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.11.2+1.21.2-patch.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.106.1+1.21.2"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1.jar",
          "size": 290827,
          "sha512": "83e1cdcac0e1a253e8bc18446ffd1f18bda7f4d58cb07a3b84d127a536d6e2fe6398a64e91368c5d68a730460d98b8879591093e104e4ac42d827544ba7f7513",
          "sha256": "656ff829587f5582f30162ec9ceccb223906e9a1b6101dccd32441292c76537a",
          "sha1": "c571bff2bfd4f1a859604b107eac34e8e9c3634a",
          "md5": "ce7c444de7e5966ab60beaceb9f20bec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1-sources.jar",
          "url": "minecraft-cursor-fabric-3.11.2+1.21.2-patch.1-sources.jar",
          "size": 147744,
          "sha512": "9cfaff0b3bb35fc8a205fdf5260b150bad2d35853b21d3e326430531ff6f1b7391fd5155c4897c1a9cfda26df91523001397495e1c0a3303cdcb8fe931434aab",
          "sha256": "e25b52105f29041e4b3b230512bdeea129b945650b084f18cb193faba02e01c3",
          "sha1": "a74263762f3bdb76fe00a3b677d728dbc61c6f66",
          "md5": "386846382665bbed9942c0ec08a756b8"
        }
      ]
    }
  ]
}
