{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.4+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.4+1.21.1.jar",
          "size": 675845,
          "sha512": "65d2b9f6ca475adb7967b34f3527ef882a88d59329935737fc485c100dd8816f83f2257f4a73ce613c30f9680ce9df4fbeaa7cbbc6dedc7f4c103b6a839e9941",
          "sha256": "21760ca99ce6cd80c3e05ff045fb471d5931f28b40615e640bea42a1cd0fe126",
          "sha1": "041516030945b48504381a852d8f12c7238b218b",
          "md5": "1a2b1d846a6e000f320046082f5f0fdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.4+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.4+1.21.1.jar",
          "size": 675845,
          "sha512": "65d2b9f6ca475adb7967b34f3527ef882a88d59329935737fc485c100dd8816f83f2257f4a73ce613c30f9680ce9df4fbeaa7cbbc6dedc7f4c103b6a839e9941",
          "sha256": "21760ca99ce6cd80c3e05ff045fb471d5931f28b40615e640bea42a1cd0fe126",
          "sha1": "041516030945b48504381a852d8f12c7238b218b",
          "md5": "1a2b1d846a6e000f320046082f5f0fdb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.4+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.4+1.21.1-sources.jar",
          "size": 202469,
          "sha512": "48f8958a4cdc57404b9e110643df85a2e2349b0b3ef5b9c6b0bb43364948cf2385e2aeeaafc44f88f6b2326016070cf32479a35e3b10e039d6ec0c0ab34244e3",
          "sha256": "198ddd05d81e48bcaf38f4cf6561d098f94bb8993efb77dc75e6485ada7f200b",
          "sha1": "d5ee301b08890cf8ad7a2b2aeba1c38cea991b0c",
          "md5": "eb28a2450acd57873852230f4e008ed1"
        }
      ]
    }
  ]
}
