{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-neoforge",
    "version": "3.7.0+1.21.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.7.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.7.0+1.21.4.jar",
          "url": "minecraft-cursor-neoforge-3.7.0+1.21.4.jar",
          "size": 191419,
          "sha512": "5c062b9ce96dbdc2cdab5dedcb4a58f7fc72438e011eecc0b2b89afead622fb6f4a2ccd44ef7e5984898d0a164acdbba1720b79d1e565e118f9d8bb02d6f9d80",
          "sha256": "1a8393c46b502c64b1ef5a000b103231a77235d1d645f2008518750b7829ee3e",
          "sha1": "7b79cbc8b681856a3d8f38949d99ffa5cb459342",
          "md5": "5b4df575edfaee2e57202882f72297a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.7.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.7.0+1.21.4.jar",
          "url": "minecraft-cursor-neoforge-3.7.0+1.21.4.jar",
          "size": 191419,
          "sha512": "5c062b9ce96dbdc2cdab5dedcb4a58f7fc72438e011eecc0b2b89afead622fb6f4a2ccd44ef7e5984898d0a164acdbba1720b79d1e565e118f9d8bb02d6f9d80",
          "sha256": "1a8393c46b502c64b1ef5a000b103231a77235d1d645f2008518750b7829ee3e",
          "sha1": "7b79cbc8b681856a3d8f38949d99ffa5cb459342",
          "md5": "5b4df575edfaee2e57202882f72297a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.7.0+1.21.4-sources.jar",
          "url": "minecraft-cursor-neoforge-3.7.0+1.21.4-sources.jar",
          "size": 89387,
          "sha512": "870b49704b259ecf4066193c58fd291b6a61a4aef1025ace5e1ade87c4bf58bd4c98a8bd069ca5ba32e839ce1b549701d0736d735397f634757f719761446671",
          "sha256": "582660743cc4f8c4d49804f8714ba08775a2b3e2ba66770d04fe3978e5d65f5c",
          "sha1": "b69a34044d64e1717421e6a4893ad8e605cc87cb",
          "md5": "9824082da965c4f58a18ed3efae4f9b4"
        }
      ]
    }
  ]
}
