{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.2+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.2+1.21.5.jar",
          "url": "packed_packs_api-common-2.1.2+1.21.5.jar",
          "size": 30377,
          "sha512": "42f402e86f2ba9f72897dfbb56bd433f862682923327b7fa2890c2b3b0f3c6983f37800e3f08d190e8da7f08e1f7c1ef0fde38cde5ab0ec7f3b1308c8bba7520",
          "sha256": "be6e76d456ca8df9a2b4485833431f29cfab297ed53bc2773a3a63140c0533f8",
          "sha1": "a6485078475871f0e82f8d8bdb82c1ffeabb7097",
          "md5": "879ff5237afe0b745b5ac473892af079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.2+1.21.5.jar",
          "url": "packed_packs_api-common-2.1.2+1.21.5.jar",
          "size": 30377,
          "sha512": "42f402e86f2ba9f72897dfbb56bd433f862682923327b7fa2890c2b3b0f3c6983f37800e3f08d190e8da7f08e1f7c1ef0fde38cde5ab0ec7f3b1308c8bba7520",
          "sha256": "be6e76d456ca8df9a2b4485833431f29cfab297ed53bc2773a3a63140c0533f8",
          "sha1": "a6485078475871f0e82f8d8bdb82c1ffeabb7097",
          "md5": "879ff5237afe0b745b5ac473892af079"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.2+1.21.5-sources.jar",
          "url": "packed_packs_api-common-2.1.2+1.21.5-sources.jar",
          "size": 18187,
          "sha512": "9df6475eec311dcebd32837b3046a3d0846a094b43d976f1bc46db28ff1bcf1d1a15a2d5039b384ba5259e46b18d8c490c75964073fe61b10fd34e2d405085ac",
          "sha256": "ea81a67369cbbb84f3d1dbd1d633e56244aaaab97add6512658b3ea218b45400",
          "sha1": "eef548ec3f310d9c550b924ca8c5c2df2e99e9be",
          "md5": "3ea61636cc3f6d424f99ff09d785c45a"
        }
      ]
    }
  ]
}
