{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "size": 26801,
          "sha512": "175f5b8005e6ad24c6eaa042105aad8417cc4814cf629d668e47408706f9769138d03bae950e9a90441c85ca91edc2841db36299878855910aa2d795e8cdd0a3",
          "sha256": "845936696f8696380551301c6827ebe5292ff80bcbaa701ac3353c69219c6da7",
          "sha1": "6df1f0304a629aa0076f7cc852f7bb711e8e99e8",
          "md5": "df4b5fb9b8ecbe6251df5b088596cbbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1.jar",
          "size": 26801,
          "sha512": "175f5b8005e6ad24c6eaa042105aad8417cc4814cf629d668e47408706f9769138d03bae950e9a90441c85ca91edc2841db36299878855910aa2d795e8cdd0a3",
          "sha256": "845936696f8696380551301c6827ebe5292ff80bcbaa701ac3353c69219c6da7",
          "sha1": "6df1f0304a629aa0076f7cc852f7bb711e8e99e8",
          "md5": "df4b5fb9b8ecbe6251df5b088596cbbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.2+1.21.1-sources.jar",
          "size": 15181,
          "sha512": "a799917b53f8345bb3786ea7018449e2426811e0d4f3766422b961b5b33362683d03622ca42e595004e6408efa5d6b251ddb679ad087e1c04084b04e1c46957b",
          "sha256": "d0064078fd1a88ad6a8c10b12d1c125aa49e4194a1729ace7cbf2e06ee831aa3",
          "sha1": "deccd5e35fd47f0264dd8483bab83107e28d7d83",
          "md5": "637b91022f966d38e8f7a12a90adb751"
        }
      ]
    }
  ]
}
