{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.4+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.12+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.12+1.21.1.jar",
          "size": 683701,
          "sha512": "19b45381b85987a5cebd22adef12296d53072959418a47cc293f0359cefa4e5d64003a2e9b86e77b8d97500ab467c881c2de40e079baece1a301d1b5f7573264",
          "sha256": "d5be51a9ef99ef597838f5343bfbc14a2603b9ff61917ba2d36ab50569f40d7c",
          "sha1": "6f83abb197400930d3bcb5c27eff6158b7383236",
          "md5": "1d7ef5fad8e3d9c2b59f1d0ba2f195bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.4+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.12+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.12+1.21.1.jar",
          "size": 683701,
          "sha512": "19b45381b85987a5cebd22adef12296d53072959418a47cc293f0359cefa4e5d64003a2e9b86e77b8d97500ab467c881c2de40e079baece1a301d1b5f7573264",
          "sha256": "d5be51a9ef99ef597838f5343bfbc14a2603b9ff61917ba2d36ab50569f40d7c",
          "sha1": "6f83abb197400930d3bcb5c27eff6158b7383236",
          "md5": "1d7ef5fad8e3d9c2b59f1d0ba2f195bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.12+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.12+1.21.1-sources.jar",
          "size": 256355,
          "sha512": "e26c0c8c34a976594c3b3510209940ff26cf0b548048ab87980311c41814acf8e6b716c4bb22704aab953ac0a4d3f8ef8c0ec1fae0ab7a3f4a6d542b4d2bc436",
          "sha256": "56ea00f6783d4dec4e1e3bd3f03bdd5c8620fc4be52c2269662b455c827d2f4e",
          "sha1": "9b7f12d3a9d956206949ae1e3768a339a6ce5905",
          "md5": "f9c3a43b53ac89d8c931c4873c98dbfc"
        }
      ]
    }
  ]
}
