{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.2+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.2+1.21.1.jar",
          "size": 31641,
          "sha512": "4e34c1862a2630f9771ba83e4f681304f3d6bdda24562aeca37706f013a6626d74bde9c1b54470fc47e7f7388399e2fc742bad9320bf23d2559755944c27f7f8",
          "sha256": "2cbdb2be14f1e194ebfb1f9d976ac06265c02d1d8afaa16f941a43f4d1c5dfa4",
          "sha1": "90c4ba8381f848e9f1e90e8d9bd7cffa7f73e664",
          "md5": "5ef64936e59c6c572d2150d33e1ba80a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.2+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.2+1.21.1.jar",
          "size": 31641,
          "sha512": "4e34c1862a2630f9771ba83e4f681304f3d6bdda24562aeca37706f013a6626d74bde9c1b54470fc47e7f7388399e2fc742bad9320bf23d2559755944c27f7f8",
          "sha256": "2cbdb2be14f1e194ebfb1f9d976ac06265c02d1d8afaa16f941a43f4d1c5dfa4",
          "sha1": "90c4ba8381f848e9f1e90e8d9bd7cffa7f73e664",
          "md5": "5ef64936e59c6c572d2150d33e1ba80a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.2+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.2+1.21.1-sources.jar",
          "size": 21235,
          "sha512": "bb2a910ddd33df3985fb946b5a07a298f13b049a447edb3f3a4e860afd8f61afa3dee8f228c636b5202ac2fd4ff7e55e2df0570ee39b41e85e1df446023b1330",
          "sha256": "5e9cbb08baba9636b06e868299ce2a48024f63cf176edc8bfb33710a1bb6a8e9",
          "sha1": "d19db453f369cc091a7caff6a8d543229316cee9",
          "md5": "c80e9e4a235dce4710d5a8b8f1d0bd93"
        }
      ]
    }
  ]
}
