{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.2.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.0+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.5.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.2.0+1.21.1.jar",
          "size": 781201,
          "sha512": "ba2b8ba33f236e424f6a5afaca4e22422cc561eaa497fc9ce7b048f8a710abc8da1d8ffc3bf68027296c5baa84903ec161bbdb42454114667a142229cd5dbd76",
          "sha256": "3eb030f0d2c38116babc010e800d85dfe9f3d3a93258ffec783793f58ecb1751",
          "sha1": "43df1fd459821927cbe2f7e6995de2d2bf116dff",
          "md5": "5f0a44dc694f815cd527722628c45a1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.2.0+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.5.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+1.21.1.jar",
          "url": "packed_packs-neoforge-2.2.0+1.21.1.jar",
          "size": 781201,
          "sha512": "ba2b8ba33f236e424f6a5afaca4e22422cc561eaa497fc9ce7b048f8a710abc8da1d8ffc3bf68027296c5baa84903ec161bbdb42454114667a142229cd5dbd76",
          "sha256": "3eb030f0d2c38116babc010e800d85dfe9f3d3a93258ffec783793f58ecb1751",
          "sha1": "43df1fd459821927cbe2f7e6995de2d2bf116dff",
          "md5": "5f0a44dc694f815cd527722628c45a1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.2.0+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.2.0+1.21.1-sources.jar",
          "size": 178810,
          "sha512": "e8e9518dba3bcfeb7669723f6ca11409faf1364730181352563758ca47901471060985180ff76868d484698d7f02331161de82bd73ede8cf2389f9b036c3f6b1",
          "sha256": "5b579216d17abc78226c3ee3fc80f17ee8e1ebd4aa4cb2aa50dcc5693ecdf779",
          "sha1": "23f4126e49da43220388e8ee0d1af434e3271960",
          "md5": "8592e5e558e58caa231f363a902dd783"
        }
      ]
    }
  ]
}
