{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0-beta.3+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.2.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.2.jar",
          "size": 32029,
          "sha512": "039136f087921ce7e3e8f367db9e431d54b7f9bde45506786e9896108e620ebc1031d852127ebe3b87da94fd3f950b69ec4fd87bcf6652618e6ab02114bcdd64",
          "sha256": "025e02f36e52f73031e55291a4e4e6dd8fdf921454533668eb24caaf2b75ff20",
          "sha1": "ceb8755ee02aaee191b30e317e5197892d8bbd01",
          "md5": "fcbb2950728f7cbba2315e97be28a83a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.2.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.2.jar",
          "size": 32029,
          "sha512": "039136f087921ce7e3e8f367db9e431d54b7f9bde45506786e9896108e620ebc1031d852127ebe3b87da94fd3f950b69ec4fd87bcf6652618e6ab02114bcdd64",
          "sha256": "025e02f36e52f73031e55291a4e4e6dd8fdf921454533668eb24caaf2b75ff20",
          "sha1": "ceb8755ee02aaee191b30e317e5197892d8bbd01",
          "md5": "fcbb2950728f7cbba2315e97be28a83a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.3+26.2-sources.jar",
          "url": "packed_packs_api-common-2.3.0-beta.3+26.2-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
