{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.1+26.1-patch.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.1+26.1-patch.1.jar",
          "url": "packed_packs_api-fabric-2.1.1+26.1-patch.1.jar",
          "size": 32425,
          "sha512": "8a4f9c9cf8e38b8eeab2e847146acd02d32be821933ab2de962f3d528e39bc5457c02d4e94199400e71aecdf894d633c65853677af6ed23985cbd30cdde427c2",
          "sha256": "07686b67e3550be61bed9930cef61d40d32c43884917eab5e50000674de0d6a2",
          "sha1": "b7293d7b21036587238f04f27e3cc2a374517eb1",
          "md5": "bdd9b428c2bd694ab77ff34cc54ddd92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.143.15+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.1+26.1-patch.1.jar",
          "url": "packed_packs_api-fabric-2.1.1+26.1-patch.1.jar",
          "size": 32425,
          "sha512": "8a4f9c9cf8e38b8eeab2e847146acd02d32be821933ab2de962f3d528e39bc5457c02d4e94199400e71aecdf894d633c65853677af6ed23985cbd30cdde427c2",
          "sha256": "07686b67e3550be61bed9930cef61d40d32c43884917eab5e50000674de0d6a2",
          "sha1": "b7293d7b21036587238f04f27e3cc2a374517eb1",
          "md5": "bdd9b428c2bd694ab77ff34cc54ddd92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.1+26.1-patch.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.1+26.1-patch.1-sources.jar",
          "size": 18389,
          "sha512": "54e8037bd016f6fb5639d16a26ac5447a44f9eee64305d9ab8eed4ae05a62b497a5a12815cdd3543c020ac18bc5b585f12461caeb74276f7017c127a9bb5921b",
          "sha256": "15e94fa921f43765dd7c108ec9f7757013a7a3a6f9921635d7eb7bde010a4f1c",
          "sha1": "5e4b8356172eb91f007967039ae27d4452d045bf",
          "md5": "d95ba1a3b14efecbdd757d5b06b0408b"
        }
      ]
    }
  ]
}
