{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.3+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+1.21.11.jar",
          "url": "packed_packs_api-common-2.2.3+1.21.11.jar",
          "size": 31923,
          "sha512": "b864718b666c898e52a9a0515c61019dda6f620b8d2b6b4eedfcaaea3fd7722f91d6d5246d833951902f09e1c28831b1d06800f8171dbc086244a14156b4b7c0",
          "sha256": "0b80f697b620f1d8d1e478dddc2665cd17bc416dbafb38fef6f01e7afe770947",
          "sha1": "3acfb4a8686095cd29bb5319ce98a2c4768e4512",
          "md5": "a58584b3a54d2fa5b7296aae02bbc54b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+1.21.11.jar",
          "url": "packed_packs_api-common-2.2.3+1.21.11.jar",
          "size": 31923,
          "sha512": "b864718b666c898e52a9a0515c61019dda6f620b8d2b6b4eedfcaaea3fd7722f91d6d5246d833951902f09e1c28831b1d06800f8171dbc086244a14156b4b7c0",
          "sha256": "0b80f697b620f1d8d1e478dddc2665cd17bc416dbafb38fef6f01e7afe770947",
          "sha1": "3acfb4a8686095cd29bb5319ce98a2c4768e4512",
          "md5": "a58584b3a54d2fa5b7296aae02bbc54b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.3+1.21.11-sources.jar",
          "url": "packed_packs_api-common-2.2.3+1.21.11-sources.jar",
          "size": 19047,
          "sha512": "51f6fd6c73dd33a6ff813692ece9cd26bb57f6eb9b6370f5589645e1d34c7b896d230232e5a66feeaa288dc92bcc1dc169087d473a9c404f27df90c9d847bda5",
          "sha256": "e707ccd1a74a851945bcf6a4f96c2aa277f1cb9600ae4a342a430a0f6c345237",
          "sha1": "fe09f41b1aff36ee7c1e1bb7d4ff78bc7d285138",
          "md5": "2f7dbafec084158cc52af5c52334ec59"
        }
      ]
    }
  ]
}
