{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0+1.21.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0+1.21.5.jar",
          "url": "packed_packs_api-fabric-2.1.0+1.21.5.jar",
          "size": 31625,
          "sha512": "7cea0da0ca8fd70512b649a5b47b73f421552f7436708b4f48fcfd5a3df7276b56385287b7d70ce734ad5dcca9bebfc851a2b2ff451b29c54083530218376cb3",
          "sha256": "e8c9ba7526e462d76e2c3b32d28d402230fa27933fe05b7d3216924248b93636",
          "sha1": "d3fdde6fdeab6ff63fb4df1f7a22b055f713d5ea",
          "md5": "f714b2a3afc9c62b3e2f4df1bc87080b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.14"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.123.2+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0+1.21.5.jar",
          "url": "packed_packs_api-fabric-2.1.0+1.21.5.jar",
          "size": 31625,
          "sha512": "7cea0da0ca8fd70512b649a5b47b73f421552f7436708b4f48fcfd5a3df7276b56385287b7d70ce734ad5dcca9bebfc851a2b2ff451b29c54083530218376cb3",
          "sha256": "e8c9ba7526e462d76e2c3b32d28d402230fa27933fe05b7d3216924248b93636",
          "sha1": "d3fdde6fdeab6ff63fb4df1f7a22b055f713d5ea",
          "md5": "f714b2a3afc9c62b3e2f4df1bc87080b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0+1.21.5-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0+1.21.5-sources.jar",
          "size": 21254,
          "sha512": "ab82658e43073d8b0bc055f222571b088fc00f0d58d6774cc96fe09407e98146db722172f0c6693f1b521f30c462c1ae290279d0f803f19e41cfa89776164ac3",
          "sha256": "6b0e407eb031a8cd267092abe355a3a77bfd376c7d4f8cc7bb186ec4d7bc150d",
          "sha1": "72195f13c9c2dc05b4677178fc8190ec40123601",
          "md5": "164768e21b0d2cad602b2bbb787fc12b"
        }
      ]
    }
  ]
}
