{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-fabric",
    "version": "0.7.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.1.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.1.jar",
          "size": 458062,
          "sha512": "a1ab6e4a65323e3e6427ca93060a2e0679d82aab6b29992d27b4d6f2344f465780839392299ef26526c07ac24c362e1404c97033959764ee680decc94d18557d",
          "sha256": "99291344ad476abced8dcd75551482e80a11d526c0d0b4372e3d808ae641e0ce",
          "sha1": "7de4ee28a4d4bb980ec77604770f17612cd3af85",
          "md5": "9a881813cc5dd6e70639e946f72dec98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.12+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.1.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.1.jar",
          "size": 458062,
          "sha512": "a1ab6e4a65323e3e6427ca93060a2e0679d82aab6b29992d27b4d6f2344f465780839392299ef26526c07ac24c362e1404c97033959764ee680decc94d18557d",
          "sha256": "99291344ad476abced8dcd75551482e80a11d526c0d0b4372e3d808ae641e0ce",
          "sha1": "7de4ee28a4d4bb980ec77604770f17612cd3af85",
          "md5": "9a881813cc5dd6e70639e946f72dec98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-fabric-0.7.3+1.21.1-sources.jar",
          "url": "fidgetz-fabric-0.7.3+1.21.1-sources.jar",
          "size": 169758,
          "sha512": "f94a80983f68d4071447397a6dec019d55050270320cffb0371954d2d389855d0193f030899ff29887924a86c5f79aaf9ec6acca99bb27280be1fba5faabd915",
          "sha256": "d37b0b0b4e74c97cff6a23c09197da6a1840744abb955dea0011b1b02babbe8d",
          "sha1": "1b13039ade36ca9de2461803231bdef8a2867795",
          "md5": "cd9b44c6458ffc80bcc99935800428e0"
        }
      ]
    }
  ]
}
