{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.6+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.6+1.21.1.jar",
          "size": 675938,
          "sha512": "536d74c7abd24bcaaf4db4bdf8d4f18a1c9ebb406bb7f383acdde2ba83df577e635ab0ee18d58713b9581cca37ff1f5e09eb06c6f4365ec5cfaf98138fcd2918",
          "sha256": "39e80bbd8b6d9fb1cac6664e648346e2fbc921a3f3fa284aaacc514eff391118",
          "sha1": "923a861e3188fc3d63e18c0777bf93e163060d1b",
          "md5": "a99942718b2a943601575b5f5c42a4e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.6+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.6+1.21.1.jar",
          "size": 675938,
          "sha512": "536d74c7abd24bcaaf4db4bdf8d4f18a1c9ebb406bb7f383acdde2ba83df577e635ab0ee18d58713b9581cca37ff1f5e09eb06c6f4365ec5cfaf98138fcd2918",
          "sha256": "39e80bbd8b6d9fb1cac6664e648346e2fbc921a3f3fa284aaacc514eff391118",
          "sha1": "923a861e3188fc3d63e18c0777bf93e163060d1b",
          "md5": "a99942718b2a943601575b5f5c42a4e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.6+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.6+1.21.1-sources.jar",
          "size": 202502,
          "sha512": "1e13b9c3ea05ee361d76f987225126fa1048aff81dcb1cb9a7a71e868a0dfd807c2326a851c141c00504346ece74d7d1e445c53a2008be1cf3a26df957e3b2c0",
          "sha256": "a3db2b98b64d6f9ab421bea3c78c794c436f827884873b9c5472bdb3941d8aeb",
          "sha1": "2197a57e8c3a3ca2fd708e06a240d5512f82533c",
          "md5": "c11011d4dbeb70856c096d454d006ebd"
        }
      ]
    }
  ]
}
