{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0-beta.3+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.3+26.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.3+26.1.jar",
          "size": 32408,
          "sha512": "18a8b330662073283726173f4386fd72b10d356c0aec6d0ebcb9b569f5d46ac9cb74a54f6ed04251d1662fa4cca88c6dec1116c1a695aecc34c503df80e4751c",
          "sha256": "4da2412321735b95636f35209114518df2c90a5f8783986ef096b7d617356936",
          "sha1": "5971e959c3a03b7401d21c3aa7cd8c0699447d7f",
          "md5": "0db5e6be03bdde748ac56462fafc58bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.3+26.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.3+26.1.jar",
          "size": 32408,
          "sha512": "18a8b330662073283726173f4386fd72b10d356c0aec6d0ebcb9b569f5d46ac9cb74a54f6ed04251d1662fa4cca88c6dec1116c1a695aecc34c503df80e4751c",
          "sha256": "4da2412321735b95636f35209114518df2c90a5f8783986ef096b7d617356936",
          "sha1": "5971e959c3a03b7401d21c3aa7cd8c0699447d7f",
          "md5": "0db5e6be03bdde748ac56462fafc58bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.3+26.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.3+26.1-sources.jar",
          "size": 19466,
          "sha512": "a166af16de1fb11d616a169e915dc3ea7c2f7f2a0fd9f7ea36a59067dbec6de087abc6032e985975f6002fceab673d7a88e3a9fcfc69412dc8998c84599245ed",
          "sha256": "c50ac8ab33ad664b81ec5a8edd7a5c122322e494ed1dad2c30661ae6df99a6c8",
          "sha1": "9eeefdeef79d733aa86129700ccdb6ce481e1cef",
          "md5": "cf35879e748902d2b85cbadb3c27d038"
        }
      ]
    }
  ]
}
