{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-fabric",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "size": 597663,
          "sha512": "411c2283d7cf4da3c5b4eca1ebef8b552b7150ded66f952a71892e39abd7d04f69a1bb6037da2f7f22540b1a5b959833cfdf4e001ccc99ec7fc0f4ee04b6f29b",
          "sha256": "853626cb9e5755e8c80ac4e49e36823500788b939bd1f0d8ad4f75719d78a483",
          "sha1": "c78835f31070c38ae6d5999b38f7b56a93710e62",
          "md5": "593c0b9e8fa3f684081733e8ef4f8d26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "size": 597663,
          "sha512": "411c2283d7cf4da3c5b4eca1ebef8b552b7150ded66f952a71892e39abd7d04f69a1bb6037da2f7f22540b1a5b959833cfdf4e001ccc99ec7fc0f4ee04b6f29b",
          "sha256": "853626cb9e5755e8c80ac4e49e36823500788b939bd1f0d8ad4f75719d78a483",
          "sha1": "c78835f31070c38ae6d5999b38f7b56a93710e62",
          "md5": "593c0b9e8fa3f684081733e8ef4f8d26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1-sources.jar",
          "size": 205179,
          "sha512": "d5182387c73fa54d1cb5574b6eb532210bb32ad6092e6193ab036b0cfe932524893e9c8c5885a52fee6bcc4b977cca5f3102fb304599c4dac4dbeb7a49c3e11a",
          "sha256": "5673af849fa18ad9b47df6c6bea684f4a20065f43b241c3b535dcdbb4cf563bf",
          "sha1": "00891ca0d9006c113aa78d294a63c8045e64d5db",
          "md5": "69f6e9682b940a95168fc187a72aa2c8"
        }
      ]
    }
  ]
}
