{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "packed_packs-fabric",
    "version": "2.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "size": 597713,
          "sha512": "fed36d1a3abc07439824dcac71469080a75211d771b6b0165c041dd65bcb125bd2560c094db7a71c263d5c5fe4c0d2507b0703bc8861970f5dc8c87b9b463707",
          "sha256": "a69d7e1604dd491a512f41f4cafa5005bd1ac35bc2c736e812d8ab58fdd9b33a",
          "sha1": "e9aa4a7c2473f99fd619d4d596f35b4273d297f2",
          "md5": "8eddad6bbfc9598700abec13b853e23a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.1.0+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1.jar",
          "size": 597713,
          "sha512": "fed36d1a3abc07439824dcac71469080a75211d771b6b0165c041dd65bcb125bd2560c094db7a71c263d5c5fe4c0d2507b0703bc8861970f5dc8c87b9b463707",
          "sha256": "a69d7e1604dd491a512f41f4cafa5005bd1ac35bc2c736e812d8ab58fdd9b33a",
          "sha1": "e9aa4a7c2473f99fd619d4d596f35b4273d297f2",
          "md5": "8eddad6bbfc9598700abec13b853e23a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0+1.21.1-sources.jar",
          "size": 205186,
          "sha512": "bfd832d7be54b022d3ee8a3d1eb7d99272599265007463aee5aa1640de96fb9e23d53fb2917c71c78b6614636f03491132e49fd145ea6641b880126d6bbbe535",
          "sha256": "e92c3d3304f05210943eece9e67e2c1c4e347a8f89c790d175a645c59a60a4a7",
          "sha1": "c8c1a3bb6b24715700fc0417f7770cb614fb0a1b",
          "md5": "3193ede77105ca39fe29b26b158ffd56"
        }
      ]
    }
  ]
}
