{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.7.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.7.3+1.21.1.jar",
          "url": "fidgetz-common-0.7.3+1.21.1.jar",
          "size": 450081,
          "sha512": "daa3708c4d0850465a6f4a9f802719a6cabb32a7c1585529b504f2ac81045236bb96a67ed973fbf9bdabe27c1d51432114fa8ffa18ce37bb3228d703eae09431",
          "sha256": "34a0fc63aef9ab335c9a97dca8e76c2012e80ef37896d35e1f4de7b4b45caf59",
          "sha1": "c24f11f5f3774ef51d13748d200add27b1503904",
          "md5": "3012a638bbd152e3fe5ece57d283e9e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.7.3+1.21.1.jar",
          "url": "fidgetz-common-0.7.3+1.21.1.jar",
          "size": 450081,
          "sha512": "daa3708c4d0850465a6f4a9f802719a6cabb32a7c1585529b504f2ac81045236bb96a67ed973fbf9bdabe27c1d51432114fa8ffa18ce37bb3228d703eae09431",
          "sha256": "34a0fc63aef9ab335c9a97dca8e76c2012e80ef37896d35e1f4de7b4b45caf59",
          "sha1": "c24f11f5f3774ef51d13748d200add27b1503904",
          "md5": "3012a638bbd152e3fe5ece57d283e9e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.7.3+1.21.1-sources.jar",
          "url": "fidgetz-common-0.7.3+1.21.1-sources.jar",
          "size": 168281,
          "sha512": "ed8865d56193488b3db9071bc68bb3f9c8a9222e1d5c18637b282dbed431cd794601aba452ad74ab35f6b91043f2800e1b17677f56bb5b4101566417923c0217",
          "sha256": "e0c9e364c3cc20499ed24d01ca8d356383ade8814f33c2205015452155af92f7",
          "sha1": "56fddad34d97f6cac0868c046ac995c3a03b094b",
          "md5": "1000a160c7e8bdb21d41e8cc44875e4f"
        }
      ]
    }
  ]
}
