{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.9+1.21.1.jar",
          "size": 26149,
          "sha512": "164e2d3539ac4872a104c02f8f8912612b31562dcbbd23b75206a9c4fbc8a89bb68aa1b3df0cef8c7abb4cbd6c9dab3f2fd6ba9ad6ff0c5e403a0d3cd74c0d63",
          "sha256": "577db752c2502b3edf0c70373a51115da98a455f61fdccf20c6b1d69469fd046",
          "sha1": "5193186a2665801fa5a1c44db7c403e3435fc196",
          "md5": "d08fe12a2846fe4a550c0eea5676bce9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.9+1.21.1.jar",
          "size": 26149,
          "sha512": "164e2d3539ac4872a104c02f8f8912612b31562dcbbd23b75206a9c4fbc8a89bb68aa1b3df0cef8c7abb4cbd6c9dab3f2fd6ba9ad6ff0c5e403a0d3cd74c0d63",
          "sha256": "577db752c2502b3edf0c70373a51115da98a455f61fdccf20c6b1d69469fd046",
          "sha1": "5193186a2665801fa5a1c44db7c403e3435fc196",
          "md5": "d08fe12a2846fe4a550c0eea5676bce9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.9+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.9+1.21.1-sources.jar",
          "size": 14822,
          "sha512": "2a3ce655a9c4bd234767e10f775350281f28cca16d0cfa1ac78ce2d7eaf28bd040ef746d326775df93d194ed88637d648c242a71c5e6f73044b295ef530fdcab",
          "sha256": "56fbc728e4aab8af408f54f5e065f0eb10ffa631fdb0c0bdade876fc202cb99c",
          "sha1": "416b8e352fc0ed3572f40067405e7927e532b067",
          "md5": "d99edcdef7ea3e74b79d1bd8c54f558c"
        }
      ]
    }
  ]
}
