{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.1+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.3.jar",
          "url": "packed_packs_api-common-2.3.1+26.3.jar",
          "size": 32025,
          "sha512": "f2f9ae35831bc27da51ff035665b23cb59445bf39c9fb5be7fb24a97ece8cb7ec7d8baf95785a61a7c53e40d32657dc5c719fd73b5c919b348cffd006e91a864",
          "sha256": "5192a62095a358d7b31e65fb5aa14641465351de49ef84acfa5fbac0ff68d0e8",
          "sha1": "47b31f8d1bde71ffab58d50464402cf501778667",
          "md5": "3b8cbbd4da3c17d09516fc18ae50574b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.3.jar",
          "url": "packed_packs_api-common-2.3.1+26.3.jar",
          "size": 32025,
          "sha512": "f2f9ae35831bc27da51ff035665b23cb59445bf39c9fb5be7fb24a97ece8cb7ec7d8baf95785a61a7c53e40d32657dc5c719fd73b5c919b348cffd006e91a864",
          "sha256": "5192a62095a358d7b31e65fb5aa14641465351de49ef84acfa5fbac0ff68d0e8",
          "sha1": "47b31f8d1bde71ffab58d50464402cf501778667",
          "md5": "3b8cbbd4da3c17d09516fc18ae50574b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.1+26.3-sources.jar",
          "url": "packed_packs_api-common-2.3.1+26.3-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
