{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1.jar",
          "size": 27535,
          "sha512": "a88cc78221ea4cafcac60da88cc8dbf9976da28bab5cb979259eb5577b028a8794da6251a84abd10d78db540c929c5183e074d61abcef96bdafea367c59819f8",
          "sha256": "f0a1223809e00ad083b0f1be563824fee03454f0693eea629cf13ef36e51bed9",
          "sha1": "733869a273d7233dd14824989f1117cd80759270",
          "md5": "36c8c8754da1917a7765049fe01cf191"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1.jar",
          "size": 27535,
          "sha512": "a88cc78221ea4cafcac60da88cc8dbf9976da28bab5cb979259eb5577b028a8794da6251a84abd10d78db540c929c5183e074d61abcef96bdafea367c59819f8",
          "sha256": "f0a1223809e00ad083b0f1be563824fee03454f0693eea629cf13ef36e51bed9",
          "sha1": "733869a273d7233dd14824989f1117cd80759270",
          "md5": "36c8c8754da1917a7765049fe01cf191"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.6+1.21.1-sources.jar",
          "size": 17425,
          "sha512": "cc49807fba05c5aed855d58ec5eb26e67d74e15d0dcca55daeb8759163de24489662fa758134b84732f1d0f47b74ee60956d55009745dce94cf9f3b80391debe",
          "sha256": "25a567dcd939466364c653b6def57aff26804a3f8bffe4d8d9e6c26487d4d818",
          "sha1": "c67502cfc92d7fcb296f474cc064e46ab7379ad5",
          "md5": "6f7ba50e47ff3a50100e3ea50b07f481"
        }
      ]
    }
  ]
}
