{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0+1.21.1.jar",
          "size": 32443,
          "sha512": "bda1ec9a6575a06ec9b769b4c5a9702da792b60915d0f5f5846f2ce836389d1c190e9524caa9325018e9dff60ecfa7b8f6a468423647a22dbd3eb46b08fb8af0",
          "sha256": "444c9e7135866968454fd1b3d1cd8e0b40936f4978e1a995a21be44bd299c5fb",
          "sha1": "9bdf7fcf515bac515c427e24876db268af315f67",
          "md5": "c63670c328dd980a3f52c30ddc97a388"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0+1.21.1.jar",
          "size": 32443,
          "sha512": "bda1ec9a6575a06ec9b769b4c5a9702da792b60915d0f5f5846f2ce836389d1c190e9524caa9325018e9dff60ecfa7b8f6a468423647a22dbd3eb46b08fb8af0",
          "sha256": "444c9e7135866968454fd1b3d1cd8e0b40936f4978e1a995a21be44bd299c5fb",
          "sha1": "9bdf7fcf515bac515c427e24876db268af315f67",
          "md5": "c63670c328dd980a3f52c30ddc97a388"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0+1.21.1-sources.jar",
          "size": 19518,
          "sha512": "a72e7f8c100b4ff12b6e6fd0a2b071e32101636365f2eadbb6f3e0e855bef43c2a4ba2d5a67b6c01535f895b6fe9225de1df2ce2d8427d896bff8df9fcadf978",
          "sha256": "152aea6c790c8da526e6fb8c0a3945ccafe9196a5c370777ac6653e846d4afe2",
          "sha1": "d4b270c22f600fd7437e1b562d0e848b8b1f409a",
          "md5": "93495e7e3b91c771d81d45b630d837c1"
        }
      ]
    }
  ]
}
