{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.9+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "size": 654480,
          "sha512": "d789b4174f323822e604ed474f5f05f493b6a91e8ebe40f184cbb39869fe3346012ef1a6a01be4ba4458d2b7162fbd13b71990f6af2208aa5dd5f5843b801bcf",
          "sha256": "9bbe85c2e9c6f0ed19191d989899d00b697e477647734b92a46ba0a83870ecf7",
          "sha1": "35e0cbec6b41405e872e9d5f29bd88c2bcf0651a",
          "md5": "f8eefc9c641c94272bc9ad5de04dfef3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.9+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "size": 654480,
          "sha512": "d789b4174f323822e604ed474f5f05f493b6a91e8ebe40f184cbb39869fe3346012ef1a6a01be4ba4458d2b7162fbd13b71990f6af2208aa5dd5f5843b801bcf",
          "sha256": "9bbe85c2e9c6f0ed19191d989899d00b697e477647734b92a46ba0a83870ecf7",
          "sha1": "35e0cbec6b41405e872e9d5f29bd88c2bcf0651a",
          "md5": "f8eefc9c641c94272bc9ad5de04dfef3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.9+1.21.1-sources.jar",
          "size": 178202,
          "sha512": "a35fd4c2a7219e8d3ea484e932c06b113e024f55812e2c877f95529c5dd5de7806455e4fa811e2b0bd94fd46c183f67dc452b12a4d508634a56d5e8ae4ae884e",
          "sha256": "1b179eb181ee79e110f33dee791a8bb3c39eee4f36e433ef6f43bbefb0dec307",
          "sha1": "28f5e82ab84da1a7771752b4bc56b89870fcf241",
          "md5": "5a4d9999d926a6d898b45880cd94686c"
        }
      ]
    }
  ]
}
