{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.11+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.11+1.21.1.jar",
          "size": 26149,
          "sha512": "e36a3709cb4dab6d2036a90542f2dd2c0fb9b3b431a163964665bd1f8d426b4fb02e54879be155a704064aba8d740fe63c2f2a64fc61c2bafab85e57ee340ae0",
          "sha256": "99b848a1fce8343a046429d70e82602334f153fd64179dfec2977945e5a7c5e5",
          "sha1": "a5d339f8c15dc4b748f69f379918b94fa5899c33",
          "md5": "41d1e76d2990a56e46d111e302b34716"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.11+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.11+1.21.1.jar",
          "size": 26149,
          "sha512": "e36a3709cb4dab6d2036a90542f2dd2c0fb9b3b431a163964665bd1f8d426b4fb02e54879be155a704064aba8d740fe63c2f2a64fc61c2bafab85e57ee340ae0",
          "sha256": "99b848a1fce8343a046429d70e82602334f153fd64179dfec2977945e5a7c5e5",
          "sha1": "a5d339f8c15dc4b748f69f379918b94fa5899c33",
          "md5": "41d1e76d2990a56e46d111e302b34716"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.11+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.11+1.21.1-sources.jar",
          "size": 14822,
          "sha512": "31889cb3d7065b9f870e3bea2c42a45a46f5bdd290ff7c4159f4cb70dca90850c0532bd8bd879f9bc7a0cbf051aa98ad14bc3a17be6d883cbc92c6e0db5c0abc",
          "sha256": "18bfde0caf4a0f89b39df94650fa73d25841cdcfc5a892d9a259f7bcebcde721",
          "sha1": "f2d3c41a52b75a68ea630111d12c5f0454751271",
          "md5": "90bbb68e8707e527527c4c774f89c9e9"
        }
      ]
    }
  ]
}
