{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.4.0+26.1-beta.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.4.0+26.1-beta.1.jar",
          "url": "fidgetz-neoforge-0.4.0+26.1-beta.1.jar",
          "size": 304331,
          "sha512": "ac52b2b3176f6ec30e5591887231b2d2d32b81dee945d512d13f8742d241a78dd92a2a24f6203fff0b7a83694daa5bb6a2adbed51462b669d3c62c500c755540",
          "sha256": "93e8aa980d94b73ef4ede298c55d60fb2e753b9fee591ae2ed6e2a35bc7d905a",
          "sha1": "33788bff569d43d03ff10dad01b41bd4b028d0b1",
          "md5": "7077ed918b463156f0e3dd8e01a217cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.4.0+26.1-beta.1.jar",
          "url": "fidgetz-neoforge-0.4.0+26.1-beta.1.jar",
          "size": 304331,
          "sha512": "ac52b2b3176f6ec30e5591887231b2d2d32b81dee945d512d13f8742d241a78dd92a2a24f6203fff0b7a83694daa5bb6a2adbed51462b669d3c62c500c755540",
          "sha256": "93e8aa980d94b73ef4ede298c55d60fb2e753b9fee591ae2ed6e2a35bc7d905a",
          "sha1": "33788bff569d43d03ff10dad01b41bd4b028d0b1",
          "md5": "7077ed918b463156f0e3dd8e01a217cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.4.0+26.1-beta.1-sources.jar",
          "url": "fidgetz-neoforge-0.4.0+26.1-beta.1-sources.jar",
          "size": 119152,
          "sha512": "d6c692e9c88cb7438ebb2e4e0b31526166f265d34046eab214acfa64a9553af48f15bee5add119f98d0f041f6b056018a33582ab58385a51835d4c36346c2143",
          "sha256": "262b219f0a23a4380b08ed6b5181966da71efc6b28e844519108bf3f1b45b01a",
          "sha1": "2978537d9beef13da5ba6c9003c26ad3006ee3f5",
          "md5": "b6c82b43eaea13521c9e7c4986305835"
        }
      ]
    }
  ]
}
