{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "size": 26802,
          "sha512": "0e7d65634c5cbfe23841fbe051b1d3599a97b4325189465f6617bb121950b342f6af93c82883e9b06a1f29d3f580ba0950a1d66c298330111a8abc4257eda534",
          "sha256": "8ae3ad5eb927cb7069fe7ad8fb5088bafedf36d33d82d61c25e16de15100d051",
          "sha1": "677de2b41a6b1295f54a2f5b53f74b4ebc0ad356",
          "md5": "c73760e1862e86f16158282d9e9871a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1.jar",
          "size": 26802,
          "sha512": "0e7d65634c5cbfe23841fbe051b1d3599a97b4325189465f6617bb121950b342f6af93c82883e9b06a1f29d3f580ba0950a1d66c298330111a8abc4257eda534",
          "sha256": "8ae3ad5eb927cb7069fe7ad8fb5088bafedf36d33d82d61c25e16de15100d051",
          "sha1": "677de2b41a6b1295f54a2f5b53f74b4ebc0ad356",
          "md5": "c73760e1862e86f16158282d9e9871a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.6+1.21.1-sources.jar",
          "size": 15181,
          "sha512": "a144822c9093c581b1744367f93467cd09b4daceb097b0b471ffe1c416e4aa4764774f5d2960295d2f4b6c7e0906543d63b085f1f584158f269ef602162d456b",
          "sha256": "f186c0a0617af480849a0b4db5cf2944bf999489cd84a63bda7a8042817dec3b",
          "sha1": "078c4bad03836e71833daa3440a4791440061de1",
          "md5": "df2b37480c8de822708d8efc886fffef"
        }
      ]
    }
  ]
}
