{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.2.1+1.21.1.jar",
          "size": 33229,
          "sha512": "639dfccea2898ae876fdd2bad5e7f61225eaa402c9b5bf121fdf0a6d53bddfa292d3f83b8ec915beb553751b826bcd062ad04efbfd1371680f49ce7602202ec9",
          "sha256": "1a6164c119db45f2d07a3b5dc56ea835eaa07d1f7a9d285cb75286d08046b141",
          "sha1": "2544a70bb9f09931ab78ba2071c55f6d8aaf1a71",
          "md5": "54d397169f7c1e2451772e564bd11852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.2.1+1.21.1.jar",
          "size": 33229,
          "sha512": "639dfccea2898ae876fdd2bad5e7f61225eaa402c9b5bf121fdf0a6d53bddfa292d3f83b8ec915beb553751b826bcd062ad04efbfd1371680f49ce7602202ec9",
          "sha256": "1a6164c119db45f2d07a3b5dc56ea835eaa07d1f7a9d285cb75286d08046b141",
          "sha1": "2544a70bb9f09931ab78ba2071c55f6d8aaf1a71",
          "md5": "54d397169f7c1e2451772e564bd11852"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.1+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.2.1+1.21.1-sources.jar",
          "size": 19860,
          "sha512": "249511dd7e9ec6535e23a5fd81abead13e2075052f22305b9ba8ce5805c02cb9ecb83988182cb304366e6ab8a080c63fec151461c0d35c85292cd128a3a41f90",
          "sha256": "49c007f64643b34765ec22283917b35ca4075c003f3da366d6049731adcd84bc",
          "sha1": "620e3fb08f7cccb877f8326248e6b47307ea3b45",
          "md5": "fad35a57910f8623fbc2f93715d8d467"
        }
      ]
    }
  ]
}
