{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+26.3.jar",
          "url": "packed_packs_api-common-2.3.0+26.3.jar",
          "size": 32025,
          "sha512": "2955831287b10923aa921a871c6504a71cfbefa9c3b64de839c1bf4124baa936655c1e266fd1e02af469f254a9faf66de49b6ab0c17660dfcf6d7407fd9c01a5",
          "sha256": "7b870f77110c31ff99e1183088bbee9dfa480dd4ed3f9aeb69beae66cdd813b5",
          "sha1": "c15ab92db0a99f61c14e5481af677ca7ace06bb1",
          "md5": "a8d5e1e49a21215747d5d2641753a752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+26.3.jar",
          "url": "packed_packs_api-common-2.3.0+26.3.jar",
          "size": 32025,
          "sha512": "2955831287b10923aa921a871c6504a71cfbefa9c3b64de839c1bf4124baa936655c1e266fd1e02af469f254a9faf66de49b6ab0c17660dfcf6d7407fd9c01a5",
          "sha256": "7b870f77110c31ff99e1183088bbee9dfa480dd4ed3f9aeb69beae66cdd813b5",
          "sha1": "c15ab92db0a99f61c14e5481af677ca7ace06bb1",
          "md5": "a8d5e1e49a21215747d5d2641753a752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0+26.3-sources.jar",
          "url": "packed_packs_api-common-2.3.0+26.3-sources.jar",
          "size": 19115,
          "sha512": "bbbafc88bfaf5f316c0140acc2945300ea98c178c48bde298c99caff2ccc21669f8c6ae57ec16e1f68c749f5854df935205c1a3b1e1977c2bec479ad19811a96",
          "sha256": "f6c754558ff4f53c65c3bd925d44ae1046c4a98cbc989777c94b5438532c912b",
          "sha1": "e9443296541b805ffe865df75efe931d85ec7114",
          "md5": "934b89e8ede3f5e68cb0610205a8434e"
        }
      ]
    }
  ]
}
