{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.3.0-beta.3+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.3.jar",
          "size": 33251,
          "sha512": "064be78f68d042769135977f0741ba04cfbc917466469102d01d31627832d888cdd95417287b3be784d692757f2a5a41975dd83f7c49926c80a109df676d302b",
          "sha256": "7dd81681197a205a407ee54c23d8ef98c81c0dcefaec56a8cbefc8f9fc159ef8",
          "sha1": "fc85803f55dcebb598ace98bae319f47fa3f0c4e",
          "md5": "5699b218df453f79c844a6ac077bb6f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.3.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.3.jar",
          "size": 33251,
          "sha512": "064be78f68d042769135977f0741ba04cfbc917466469102d01d31627832d888cdd95417287b3be784d692757f2a5a41975dd83f7c49926c80a109df676d302b",
          "sha256": "7dd81681197a205a407ee54c23d8ef98c81c0dcefaec56a8cbefc8f9fc159ef8",
          "sha1": "fc85803f55dcebb598ace98bae319f47fa3f0c4e",
          "md5": "5699b218df453f79c844a6ac077bb6f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.3.0-beta.3+26.3-sources.jar",
          "url": "packed_packs_api-fabric-2.3.0-beta.3+26.3-sources.jar",
          "size": 19405,
          "sha512": "25777826d7fb35726114dab59a06856c36ccc5e761c0b85750bad892c4261fb078a2b8f0347f92e93a79be2640e36bd008fcd816f98242d2646aa292e5da9fc1",
          "sha256": "d53be9e363e05ac84e0944362092ff28d8a7419ebe26b0215daf4d63098f84fc",
          "sha1": "7e3e0f9c98510c1bc85d0a91a63f72ef32d0f7b6",
          "md5": "c26a72ed9a0542d45a631a68c5cf6601"
        }
      ]
    }
  ]
}
