{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.3.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.0+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+1.21.11.jar",
          "url": "packed_packs-fabric-2.3.0+1.21.11.jar",
          "size": 999182,
          "sha512": "0c877ed356f477a861e669b99117df44c3baec8850f790d4853312aee9491b76e720ad19b07de369ee525f74273a6f9dac2693fbc152bc0173b6c1081c273695",
          "sha256": "dfb6dbdad60cb9f33be3085b4ecaf6fb49fef46cb3f95834f79e4e8ad414261d",
          "sha1": "1ddda2955630dfde9cc64861083a5c3f3d0594b4",
          "md5": "cf4ae8cf5eb9bc933ca9b4cb4685f92d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.0+1.21.11"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+1.21.11"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+1.21.11.jar",
          "url": "packed_packs-fabric-2.3.0+1.21.11.jar",
          "size": 999182,
          "sha512": "0c877ed356f477a861e669b99117df44c3baec8850f790d4853312aee9491b76e720ad19b07de369ee525f74273a6f9dac2693fbc152bc0173b6c1081c273695",
          "sha256": "dfb6dbdad60cb9f33be3085b4ecaf6fb49fef46cb3f95834f79e4e8ad414261d",
          "sha1": "1ddda2955630dfde9cc64861083a5c3f3d0594b4",
          "md5": "cf4ae8cf5eb9bc933ca9b4cb4685f92d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.3.0+1.21.11-sources.jar",
          "url": "packed_packs-fabric-2.3.0+1.21.11-sources.jar",
          "size": 207439,
          "sha512": "cc85e88f18d912dc1808cfde10b6f171ff8c14175cdacc77f50e27e33b84f028b59a0f06d591557c78f59aa7cdd1e17064bd138190c8a0430f2f89fd20199652",
          "sha256": "68e76a89e8c1f259f89f831d4557212c6878856e8b8baf9c95d318f9e43c29e8",
          "sha1": "428c1b51407eeff685e34711c0f59bac9f2459e8",
          "md5": "9e8192fc8472f26b4295d4dacd25f3f5"
        }
      ]
    }
  ]
}
