{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-neoforge",
    "version": "3.11.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.11.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.1.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.1.jar",
          "size": 283851,
          "sha512": "cc5107354f16fb4817c92a0afdba0ef0558ca4445d0ada59c8e6af35aab5a4c12839ddcdba1f6093b9e00262fe0f003ee305f148b6c03e7db7652e297dcfa29f",
          "sha256": "da17b45479c327aa0edec79ae23f69cfc73c718c99aedbbc95952c9ca73b769a",
          "sha1": "b5f6759198700f0f83747df478506d1307624701",
          "md5": "6528bb8d714e5550ccf9d8f285446f83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-common-api",
          "version": {
            "requires": "3.11.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.1.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.1.jar",
          "size": 283851,
          "sha512": "cc5107354f16fb4817c92a0afdba0ef0558ca4445d0ada59c8e6af35aab5a4c12839ddcdba1f6093b9e00262fe0f003ee305f148b6c03e7db7652e297dcfa29f",
          "sha256": "da17b45479c327aa0edec79ae23f69cfc73c718c99aedbbc95952c9ca73b769a",
          "sha1": "b5f6759198700f0f83747df478506d1307624701",
          "md5": "6528bb8d714e5550ccf9d8f285446f83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-neoforge-3.11.1+1.21.1-sources.jar",
          "url": "minecraft-cursor-neoforge-3.11.1+1.21.1-sources.jar",
          "size": 134706,
          "sha512": "526ec7e5cb1cf0cfc261244b93c3874251c95c093a8c8b838401aa3082effc23d87440d8e5e0cd75c2f6b07efea69d6b3e1b19714ccfd5e67ecfcd123ab411ae",
          "sha256": "d27d68fbf43ecc62b5a87ab83cc881c176d49349f445fbf87621518eff34aff8",
          "sha1": "7bdbf95c6d1bd38e0292238d5093eecf2d43a3c0",
          "md5": "03df36dae8f4c6015ddf6f02cdb6bab2"
        }
      ]
    }
  ]
}
