{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-neoforge",
    "version": "2.1.0-alpha.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.10+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1.jar",
          "size": 656500,
          "sha512": "0475b56fa843a5098d449b93a20b9c46d8a97d4961d66e7affd4c1a0d840ae8340db2ef6d470caea5537bb22b1b7c76f0dc424cf48ce6181276916fd69fdfa92",
          "sha256": "5fc2c33f065cd45eaee2448d955c7f8b64114798dc8ae4dce3bbbba14b77d964",
          "sha1": "f69d35a647af07611bf2d3868bcc406e27fa7379",
          "md5": "a06887097e5cdbac6de2be26eb656036"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-neoforge",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-neoforge",
          "version": {
            "requires": "2.1.0-alpha.10+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1.jar",
          "size": 656500,
          "sha512": "0475b56fa843a5098d449b93a20b9c46d8a97d4961d66e7affd4c1a0d840ae8340db2ef6d470caea5537bb22b1b7c76f0dc424cf48ce6181276916fd69fdfa92",
          "sha256": "5fc2c33f065cd45eaee2448d955c7f8b64114798dc8ae4dce3bbbba14b77d964",
          "sha1": "f69d35a647af07611bf2d3868bcc406e27fa7379",
          "md5": "a06887097e5cdbac6de2be26eb656036"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1-sources.jar",
          "url": "packed_packs-neoforge-2.1.0-alpha.10+1.21.1-sources.jar",
          "size": 178864,
          "sha512": "7e038f36306c756e6a79f4d71ba60be63a9bb9f883abe9d1e63da81ddbc62c5a196a8fd1c1e911844b09bc1aa7bc2b284cb93639d38df783fc31928ac3eb5e94",
          "sha256": "b10f87fd61fb71798b040b2c34306d0df17ea32757c56b1002587c75b87b84be",
          "sha1": "99164b387eed2d6b6db2b3ab268ffdadca009530",
          "md5": "2d2ac22376798f7c991ab9f339ea1f34"
        }
      ]
    }
  ]
}
