{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.3.0-beta.2+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+1.21.11.jar",
          "size": 32024,
          "sha512": "4fb22690bca5e45c3b9d4498c75b12ab5b3f062165f9070c55119199252869c30d6ca45c8e412ccb4c16bb693d517c27eea1f483c07c08eb459ed147f89c916c",
          "sha256": "010d18df79f152fc752dda0b287592d167398f71b547cbe94d9647bdf2fecb15",
          "sha1": "98d2678f74bce42ce50645212f37876dd747d52a",
          "md5": "22818668d9d6c58d05c4d2b0d652db24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+1.21.11.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+1.21.11.jar",
          "size": 32024,
          "sha512": "4fb22690bca5e45c3b9d4498c75b12ab5b3f062165f9070c55119199252869c30d6ca45c8e412ccb4c16bb693d517c27eea1f483c07c08eb459ed147f89c916c",
          "sha256": "010d18df79f152fc752dda0b287592d167398f71b547cbe94d9647bdf2fecb15",
          "sha1": "98d2678f74bce42ce50645212f37876dd747d52a",
          "md5": "22818668d9d6c58d05c4d2b0d652db24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.3.0-beta.2+1.21.11-sources.jar",
          "url": "packed_packs_api-common-2.3.0-beta.2+1.21.11-sources.jar",
          "size": 19104,
          "sha512": "177b8f9b04e1f3305e71a8b6bbb419a37ac9f93c5d390616f5ddbac988a925333e62380bc12233e0bb0c29599eed92973733b1d373c6e01811dc5cd3d4252561",
          "sha256": "e614be08669613b42a4c6bd8e8cd1c865119a7d7253063aeb8d8367328eb028f",
          "sha1": "3e7fe8e7604c706722ea783de0c0ed1120e374ce",
          "md5": "2002aa8b573920cb5b7461e160c85338"
        }
      ]
    }
  ]
}
