{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.12+1.21.1.jar",
          "size": 30395,
          "sha512": "601824e98a8cdb89f33bb05a1d581e05844713ed7195a395e80c2f06afaf80f01703d7516f48bac648dd7305e86f23398f4eef55e48f283b6b21160ca4828fff",
          "sha256": "c7c22c6604ae88952491376e0b71b366927f1fb37cc91538616925d5e3743397",
          "sha1": "495889857b4ef7017e56b98178810e95d2dd3cfe",
          "md5": "e5bc469bde6175c4fa7a2a307e7b80af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.12+1.21.1.jar",
          "size": 30395,
          "sha512": "601824e98a8cdb89f33bb05a1d581e05844713ed7195a395e80c2f06afaf80f01703d7516f48bac648dd7305e86f23398f4eef55e48f283b6b21160ca4828fff",
          "sha256": "c7c22c6604ae88952491376e0b71b366927f1fb37cc91538616925d5e3743397",
          "sha1": "495889857b4ef7017e56b98178810e95d2dd3cfe",
          "md5": "e5bc469bde6175c4fa7a2a307e7b80af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.12+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.12+1.21.1-sources.jar",
          "size": 18231,
          "sha512": "6792e83f866b7172fe33256f4acf7fb9e0fbb29f1878b6337073cdc514322bea8c8625bde3b162ef0cab8241cc722fa92bdcb4c153e1ac10b50243382021ecb3",
          "sha256": "3257e5f1538742edafe08847a4d74d4bade8a276be267a6a7314ee858170208b",
          "sha1": "822c210e1b6a09d3afd80fbc5079536f52bb4731",
          "md5": "5d47584d916841723155564bfba18d4c"
        }
      ]
    }
  ]
}
