{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "size": 26472,
          "sha512": "7726acc12ae2a87d4fa80a45c74d9919b100b604dc05fd4d54b4ad23e270f2956b7cc7efe8353d99a15367b774311e0783d9e7b0ab46bfa7dda416fc31e77f43",
          "sha256": "508ac1b387d9efc2cc5e19d55c8b095c07b60effe88b22ec82dd257e3e056525",
          "sha1": "b704229bb6d594fe2b4b00b0c3ff20da1ed554cb",
          "md5": "beb871c816016c6197aec27467fd7020"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1.jar",
          "size": 26472,
          "sha512": "7726acc12ae2a87d4fa80a45c74d9919b100b604dc05fd4d54b4ad23e270f2956b7cc7efe8353d99a15367b774311e0783d9e7b0ab46bfa7dda416fc31e77f43",
          "sha256": "508ac1b387d9efc2cc5e19d55c8b095c07b60effe88b22ec82dd257e3e056525",
          "sha1": "b704229bb6d594fe2b4b00b0c3ff20da1ed554cb",
          "md5": "beb871c816016c6197aec27467fd7020"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.9+1.21.1-sources.jar",
          "size": 15133,
          "sha512": "69426af48813aeb778147f0405e6e9f79d4c31b343b1f65e66c0bbbe0d9d00677d5cb099e92864b58fa9f76a512a903fd4446097c5117cda46c57889c4da96b0",
          "sha256": "b8fab31a6cdf88aab1a2d7412991c0b79fd4c51e4cc5c7d3a06a8d66f0c33126",
          "sha1": "d0b65b749486eb5bd77fbfea5f60a7da478e7415",
          "md5": "7fcb17e56e0513613682be4c2c74d462"
        }
      ]
    }
  ]
}
