{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz",
    "module": "minecraft-cursor-fabric",
    "version": "3.6.0+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.0+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.0+1.20.1.jar",
          "url": "minecraft-cursor-fabric-3.6.0+1.20.1.jar",
          "size": 185070,
          "sha512": "32ecd63110b874206079be7dfb306019ba285b0eec607ecd555f3cd8385f6200c9f283cc59a3b25c35b19cad4d989b95c95806749d57181bed655841cb88323b",
          "sha256": "1695e198f8d8ed9a06264ce759fb8d20a16d27499093f648285261e79ac00d6a",
          "sha1": "4c93e02585d524aa46e7fd2a22ba787577e64838",
          "md5": "715b534fd36a95a20de2014a2ddcfda7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz",
          "module": "minecraft-cursor-fabric-api",
          "version": {
            "requires": "3.6.0+1.20.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.9"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.3+1.20.1"
          }
        },
        {
          "group": "com.terraformersmc",
          "module": "modmenu",
          "version": {
            "requires": "7.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.0+1.20.1.jar",
          "url": "minecraft-cursor-fabric-3.6.0+1.20.1.jar",
          "size": 185070,
          "sha512": "32ecd63110b874206079be7dfb306019ba285b0eec607ecd555f3cd8385f6200c9f283cc59a3b25c35b19cad4d989b95c95806749d57181bed655841cb88323b",
          "sha256": "1695e198f8d8ed9a06264ce759fb8d20a16d27499093f648285261e79ac00d6a",
          "sha1": "4c93e02585d524aa46e7fd2a22ba787577e64838",
          "md5": "715b534fd36a95a20de2014a2ddcfda7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minecraft-cursor-fabric-3.6.0+1.20.1-sources.jar",
          "url": "minecraft-cursor-fabric-3.6.0+1.20.1-sources.jar",
          "size": 94601,
          "sha512": "32cff3ad2d94849ee753fda917cd9e68fc9f3679835dfb50f7925c9e1a98a7b3fbbf7307596d186998ed3512d7e548504fcaa6054ff940007d77479e0384324c",
          "sha256": "3ab0e6c05ec52bc681393ff0267e80869adcc276453a2ac35bc75fbd68097573",
          "sha1": "adf9debcfbe9a562d5a7b683ce90a56958e06794",
          "md5": "dfcb655274ea7a7bb7aff822bec47c1e"
        }
      ]
    }
  ]
}
