{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.10+1.21.1.jar",
          "size": 26149,
          "sha512": "eddc2ca6ff42f62f6d608733ef6156a7fc206f3d985b5ff5bfaad976dff71fe3344184618b5a2dce15535b62b889fa4d427165d357df11acc5e6e55965fdb9b6",
          "sha256": "7ecc1a87fb2ec4ba967018b40d4c1e342def2e9e6a8dd5da88cc5d5fc8469112",
          "sha1": "14945a3402d33addbe04f546fc1d9123e3107716",
          "md5": "d8f8f8dfc2bdd865ebbf6cf5ee689c7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.10+1.21.1.jar",
          "size": 26149,
          "sha512": "eddc2ca6ff42f62f6d608733ef6156a7fc206f3d985b5ff5bfaad976dff71fe3344184618b5a2dce15535b62b889fa4d427165d357df11acc5e6e55965fdb9b6",
          "sha256": "7ecc1a87fb2ec4ba967018b40d4c1e342def2e9e6a8dd5da88cc5d5fc8469112",
          "sha1": "14945a3402d33addbe04f546fc1d9123e3107716",
          "md5": "d8f8f8dfc2bdd865ebbf6cf5ee689c7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.10+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.10+1.21.1-sources.jar",
          "size": 14822,
          "sha512": "781c8f8244b1f430ccf042e8ed968a942a193253c513440db637e9168e630effd4396bf2142e40964d977fce716775f1584ac87138c7c6ddf047c4e3d483cc43",
          "sha256": "f9726b60009b69ab4b70bf1bf99d3aa22cc22a61b8797ba6dab1674cefb8dce0",
          "sha1": "4355b02eead84ee774e7ec55f1dbfe4c75a28152",
          "md5": "90a86b225213ea30e651744def2b1c22"
        }
      ]
    }
  ]
}
