{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.3.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.1+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.1+26.2.jar",
          "url": "packed_packs-fabric-2.3.1+26.2.jar",
          "size": 1002969,
          "sha512": "90d011f750e8ee1b25e898d65875681b183a0c496ce5fa365bc35ab66d5f8d4e339bee401a2aa35cfbc2dc791b194eca848338f39cfd1c5f48e09decc0c2321d",
          "sha256": "e39bbde0518dea307d9575f6fd420856b8a34cdcada755800f12769606fc80bc",
          "sha1": "4c184231ac6e6f0c1ff6638e1d01efa6d2622003",
          "md5": "f72f91e3da452d505deb52dac7bab5ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.156.0+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.3.1+26.2"
          }
        },
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.7.3+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.3.1+26.2.jar",
          "url": "packed_packs-fabric-2.3.1+26.2.jar",
          "size": 1002969,
          "sha512": "90d011f750e8ee1b25e898d65875681b183a0c496ce5fa365bc35ab66d5f8d4e339bee401a2aa35cfbc2dc791b194eca848338f39cfd1c5f48e09decc0c2321d",
          "sha256": "e39bbde0518dea307d9575f6fd420856b8a34cdcada755800f12769606fc80bc",
          "sha1": "4c184231ac6e6f0c1ff6638e1d01efa6d2622003",
          "md5": "f72f91e3da452d505deb52dac7bab5ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.3.1+26.2-sources.jar",
          "url": "packed_packs-fabric-2.3.1+26.2-sources.jar",
          "size": 204997,
          "sha512": "a7154ce8eb847bff559f759445e410a0441d7308add4f34976b38e1d4d4fef620d7f1ee606cec6e18c41d77d554d8fb2827c7f861e03b536ff799d33104ff267",
          "sha256": "f02ea6c4a937ff1f8e316131b58e26c62c39419da926fd925aa9e8474d945750",
          "sha1": "557270d143ed9a369ffa8aab22d6155eff61c026",
          "md5": "26f65b6f99a3f2e9e8832954eebba457"
        }
      ]
    }
  ]
}
