{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-common",
    "version": "2.2.4+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+1.21.11.jar",
          "url": "packed_packs_api-common-2.2.4+1.21.11.jar",
          "size": 31923,
          "sha512": "6c124942a6791c3541447a7d029b48b2e271ac26915161495a53c38640a4436807ebe19c68d04c8f79b2d6121d8890142935dc77bc719d186fdc4b3109d27a25",
          "sha256": "a7526dec8a8f7b0272e051881352c14e90101c2d45a0c513a4f366fedb62dab8",
          "sha1": "4ba87c43b382a4d447646fa1c4804b28a425a77e",
          "md5": "16849b257431687688f3341c31052db6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+1.21.11.jar",
          "url": "packed_packs_api-common-2.2.4+1.21.11.jar",
          "size": 31923,
          "sha512": "6c124942a6791c3541447a7d029b48b2e271ac26915161495a53c38640a4436807ebe19c68d04c8f79b2d6121d8890142935dc77bc719d186fdc4b3109d27a25",
          "sha256": "a7526dec8a8f7b0272e051881352c14e90101c2d45a0c513a4f366fedb62dab8",
          "sha1": "4ba87c43b382a4d447646fa1c4804b28a425a77e",
          "md5": "16849b257431687688f3341c31052db6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.2.4+1.21.11-sources.jar",
          "url": "packed_packs_api-common-2.2.4+1.21.11-sources.jar",
          "size": 19047,
          "sha512": "51f6fd6c73dd33a6ff813692ece9cd26bb57f6eb9b6370f5589645e1d34c7b896d230232e5a66feeaa288dc92bcc1dc169087d473a9c404f27df90c9d847bda5",
          "sha256": "e707ccd1a74a851945bcf6a4f96c2aa277f1cb9600ae4a342a430a0f6c345237",
          "sha1": "fe09f41b1aff36ee7c1e1bb7d4ff78bc7d285138",
          "md5": "2f7dbafec084158cc52af5c52334ec59"
        }
      ]
    }
  ]
}
