{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.5+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1.jar",
          "size": 26802,
          "sha512": "9dcb250edb0c2d899819b1c5208fc6415501e876494f26601e317d30479d451cc2ea738a3a939d12d5937b6818bc1e809674c6df4a6727692a62147334704cad",
          "sha256": "7bfe7d5c4abc5f5d3fc752bd53a289c6c4019de7117fdbdc0e433126e00879e7",
          "sha1": "a6abbce88cae92465aac815ca187ec1a40d949d6",
          "md5": "f9771bd67825bb29d9de8cf4928323f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1.jar",
          "size": 26802,
          "sha512": "9dcb250edb0c2d899819b1c5208fc6415501e876494f26601e317d30479d451cc2ea738a3a939d12d5937b6818bc1e809674c6df4a6727692a62147334704cad",
          "sha256": "7bfe7d5c4abc5f5d3fc752bd53a289c6c4019de7117fdbdc0e433126e00879e7",
          "sha1": "a6abbce88cae92465aac815ca187ec1a40d949d6",
          "md5": "f9771bd67825bb29d9de8cf4928323f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.5+1.21.1-sources.jar",
          "size": 15181,
          "sha512": "d3763cf1d88402fc8769f30524f88372f509938003b8ad372398bced38b1ddfef90967a02ed2107afcbc5a55fc4f44abcd3b101abbf9b45d29ed181893b24256",
          "sha256": "bc8685031d7e26d06e69f822d889e630d0d9a6e677f1ec511e92dfa254a44592",
          "sha1": "9156ca76ef50af27aa2d32d9e2864f4d2b106e88",
          "md5": "52575d4328fbeee81af132d2f540627b"
        }
      ]
    }
  ]
}
