{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0-beta.2+26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.1.jar",
          "size": 32408,
          "sha512": "7e7179bdffb6446a8997f075f18edf4955a057f42c593f2c6f889f95c7d0ec41ed8699c4f1836a57209e3b6ae5b6c64fb7f738cc00de9057a862ef7a0e554306",
          "sha256": "70cf1176a052495777e6e3fa4f189a8e7e9677736e575cc36b8f32e80d461c45",
          "sha1": "dc3d347f3a1804aabd72898cfc1f8a6756a02a63",
          "md5": "37b8f727737a2471cb552765b9601132"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.1.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.1.jar",
          "size": 32408,
          "sha512": "7e7179bdffb6446a8997f075f18edf4955a057f42c593f2c6f889f95c7d0ec41ed8699c4f1836a57209e3b6ae5b6c64fb7f738cc00de9057a862ef7a0e554306",
          "sha256": "70cf1176a052495777e6e3fa4f189a8e7e9677736e575cc36b8f32e80d461c45",
          "sha1": "dc3d347f3a1804aabd72898cfc1f8a6756a02a63",
          "md5": "37b8f727737a2471cb552765b9601132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.1-sources.jar",
          "size": 19466,
          "sha512": "a166af16de1fb11d616a169e915dc3ea7c2f7f2a0fd9f7ea36a59067dbec6de087abc6032e985975f6002fceab673d7a88e3a9fcfc69412dc8998c84599245ed",
          "sha256": "c50ac8ab33ad664b81ec5a8edd7a5c122322e494ed1dad2c30661ae6df99a6c8",
          "sha1": "9eeefdeef79d733aa86129700ccdb6ce481e1cef",
          "md5": "cf35879e748902d2b85cbadb3c27d038"
        }
      ]
    }
  ]
}
