{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs_api",
    "module": "packed_packs_api-common",
    "version": "2.1.0-alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.4+1.21.1.jar",
          "size": 26479,
          "sha512": "b5865c11ef38b59a40beacb9513d32fe4d4ac3bf2db88fbc74ef78c025bbb06a035b22913de39bb2193696d727fe49c479c7a8bba78a62e5a49226f0768f077d",
          "sha256": "9aa2bab4e822d13d1846a41dcdb6a03def273bcdc0b4e1a9f78bea197563f5ed",
          "sha1": "a8c6f2920777c4a583c530ae6e7ca6355c01cb5f",
          "md5": "4818d0d7fbda0630a35c8c29e6191dec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.4+1.21.1.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.4+1.21.1.jar",
          "size": 26479,
          "sha512": "b5865c11ef38b59a40beacb9513d32fe4d4ac3bf2db88fbc74ef78c025bbb06a035b22913de39bb2193696d727fe49c479c7a8bba78a62e5a49226f0768f077d",
          "sha256": "9aa2bab4e822d13d1846a41dcdb6a03def273bcdc0b4e1a9f78bea197563f5ed",
          "sha1": "a8c6f2920777c4a583c530ae6e7ca6355c01cb5f",
          "md5": "4818d0d7fbda0630a35c8c29e6191dec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-common-2.1.0-alpha.4+1.21.1-sources.jar",
          "url": "packed_packs_api-common-2.1.0-alpha.4+1.21.1-sources.jar",
          "size": 14870,
          "sha512": "5e2534eeb0793ffe61bccda192b3a3c07e9783f730481eeef583443940a7d407ef2703b50f9faa9886ac1b0fa768e3b0e13c6b6a160c2e2e570fdd186c2d2fd0",
          "sha256": "0e555eb3ce66811cc810597c94fc42aa0f4a24498d0a6c4603a38809dc057206",
          "sha1": "f05daf83b00701ed50af5ac9822aecfd07d69011",
          "md5": "cf487df8ece04d9780214da16adb2b1a"
        }
      ]
    }
  ]
}
