{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.4+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.12+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.12+1.21.1.jar",
          "size": 472351,
          "sha512": "617b705bfa1843fa86acbe7ca0a9fabc23b4ae914809351adc32cb18a1b2b59a2f998e0ce5480ee1b6fb8fdc0006e140dd31b530f74327de0cbac974481c73a0",
          "sha256": "8e55adcaff4f1f01171e9b962b4955906634b49bf60dbe78d8cc3282b1843e77",
          "sha1": "dfcb80e83d4d60c7767d65ba43462f0e5cdd7fa4",
          "md5": "f7bcaf58397c93a22a09000117a7b4a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.12+1.21.1.jar",
          "size": 472351,
          "sha512": "617b705bfa1843fa86acbe7ca0a9fabc23b4ae914809351adc32cb18a1b2b59a2f998e0ce5480ee1b6fb8fdc0006e140dd31b530f74327de0cbac974481c73a0",
          "sha256": "8e55adcaff4f1f01171e9b962b4955906634b49bf60dbe78d8cc3282b1843e77",
          "sha1": "dfcb80e83d4d60c7767d65ba43462f0e5cdd7fa4",
          "md5": "f7bcaf58397c93a22a09000117a7b4a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.12+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.12+1.21.1-sources.jar",
          "size": 178411,
          "sha512": "3ca6e3df6fbcfa71c3506be39078e3d347ccd2df23b17b49e398b7cf3bb3cb196847653754bc5f543e1529a2033505d4b058bd87f46578fb5d35af141b892a37",
          "sha256": "4373fb7d09a48bf7d6a2ce8cbe42608c383b58cc13f84503cf1d9f519f076f82",
          "sha1": "f8400a1f3b44ea5b0241f5e1a9cd505e129803f1",
          "md5": "ba75cd2e4ea11ba60ce44e014a0607e1"
        }
      ]
    }
  ]
}
