{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.5.0-beta.6+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.6+1.21.1.jar",
          "url": "fidgetz-common-0.5.0-beta.6+1.21.1.jar",
          "size": 313199,
          "sha512": "2737e88fb8dcd17e77d9c03d530407bc5cf9fc174acc2d432ecd4d620b34690f7c9a2c6669a7782d302a73a6c5cf1adb5e7afd10e8515c4d8a2380585d406df4",
          "sha256": "fe8ee9eea5968bc7c14d99a5c740bc5f2ab11ba030e900a9c33d4ca4d99396a6",
          "sha1": "c541fbaf651b2b7eb7e78fe8818415596b1c7ee8",
          "md5": "311aba16c0d67b58a2183901336a21f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.6+1.21.1.jar",
          "url": "fidgetz-common-0.5.0-beta.6+1.21.1.jar",
          "size": 313199,
          "sha512": "2737e88fb8dcd17e77d9c03d530407bc5cf9fc174acc2d432ecd4d620b34690f7c9a2c6669a7782d302a73a6c5cf1adb5e7afd10e8515c4d8a2380585d406df4",
          "sha256": "fe8ee9eea5968bc7c14d99a5c740bc5f2ab11ba030e900a9c33d4ca4d99396a6",
          "sha1": "c541fbaf651b2b7eb7e78fe8818415596b1c7ee8",
          "md5": "311aba16c0d67b58a2183901336a21f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.5.0-beta.6+1.21.1-sources.jar",
          "url": "fidgetz-common-0.5.0-beta.6+1.21.1-sources.jar",
          "size": 121102,
          "sha512": "63a9b1b2a7988a6e0546ca1131b33d33eee8797d6ef2997d9879d0095f32552cf87c795f46160ded35ff76f97125b11452f6aa41cec850fc607aa9d3ec3d56d3",
          "sha256": "e7874607e24a25aba7876f15512634d9adcee5ade1c4626989577a0d7da93108",
          "sha1": "c6dd2b7a14b1c61e52b6f3947d865ad9b82010c4",
          "md5": "88cc1af25b213c6546fcddd8bd85ecad"
        }
      ]
    }
  ]
}
