{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.9+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.9+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.9+1.21.1.jar",
          "size": 467343,
          "sha512": "bf89f9be6468ed070d96ed486898c98733dcb4e7834e6119ed1c76c03c25e3eff61f301c85dc9d44a50e08b7526504d7134d591363a3dd605ae045b293ab5fb1",
          "sha256": "f1dbad5556bacba1c8cc16f00407f3555d6cfb50924f543463372f054142bfb7",
          "sha1": "58083d9e9a94605207bc4731078a9c62073a4ab9",
          "md5": "8b4a960aeaf670d78d4d7f3d05bbc6fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.9+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.9+1.21.1.jar",
          "size": 467343,
          "sha512": "bf89f9be6468ed070d96ed486898c98733dcb4e7834e6119ed1c76c03c25e3eff61f301c85dc9d44a50e08b7526504d7134d591363a3dd605ae045b293ab5fb1",
          "sha256": "f1dbad5556bacba1c8cc16f00407f3555d6cfb50924f543463372f054142bfb7",
          "sha1": "58083d9e9a94605207bc4731078a9c62073a4ab9",
          "md5": "8b4a960aeaf670d78d4d7f3d05bbc6fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.9+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.9+1.21.1-sources.jar",
          "size": 175539,
          "sha512": "5ed21e9bff10ef6bb9441b718ae7138c168798d8294c4069c97dce7cd9c5798858931bb7f5309be6ebfd80e9884d8116c16d1c1e2ba76e5a2416a48044cdc314",
          "sha256": "37bf8bd7cd5530730811db85edd9541f3a449fd7d7113df7e125a9857b2d4fe7",
          "sha1": "f07956c2c52871c3e91695d8f5b8b8ba1b1b5921",
          "md5": "bec39bafb8baa668909797fa9c99c969"
        }
      ]
    }
  ]
}
