{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.1.0-alpha.8+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1.jar",
          "size": 26472,
          "sha512": "93c21c506550203ef9694af5f99736dd64f4009570ff90e307477d77b777f30de804d432272faaded35b68e143d39b1b910841e8b3d8844a1547f39bc9310fa6",
          "sha256": "4d65574bc4dd91d5d7faf4c273736ba5ee19dfbdc12e9c4c442b2d74c96d6aed",
          "sha1": "e1122775998a7fb6292a725ac82cf65f748f47fa",
          "md5": "8460078032b3b588a5562f64560d77ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1.jar",
          "size": 26472,
          "sha512": "93c21c506550203ef9694af5f99736dd64f4009570ff90e307477d77b777f30de804d432272faaded35b68e143d39b1b910841e8b3d8844a1547f39bc9310fa6",
          "sha256": "4d65574bc4dd91d5d7faf4c273736ba5ee19dfbdc12e9c4c442b2d74c96d6aed",
          "sha1": "e1122775998a7fb6292a725ac82cf65f748f47fa",
          "md5": "8460078032b3b588a5562f64560d77ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1-sources.jar",
          "url": "packed_packs_api-neoforge-2.1.0-alpha.8+1.21.1-sources.jar",
          "size": 15133,
          "sha512": "90d0c164c39afc6980e31047c5eaca634991a2493c986e9b7e0f20dd80718e880d6ada08ddebd65b20a68747dbd3495ffcb00f45a26573aef45aa0c9aea189ef",
          "sha256": "68f614424fbf51621b7b64e6d46c0a52db32da1e035270e2df7611788e8816d7",
          "sha1": "08ec20475a1cbf5bdcd06f72943971c708e9ff1d",
          "md5": "0c24a73ebbfda0b27f2b014294a4728a"
        }
      ]
    }
  ]
}
