{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.2.0+1.21.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.0+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.2.0+1.21.11.jar",
          "size": 33203,
          "sha512": "5ac7ffe8bcafc801e57490b841287069e5170de8b374cb0c57db8fd62caaf9bb482aef0edf728f099d995f35565409fe48f6fe49357df7ea6e94e536685c8756",
          "sha256": "f7c56649f1b7a25fb6179f53a70ea0d8caab5934f782036b087f23b188724e75",
          "sha1": "576cd7cb75f4adc817150ca536f9377437f84d3e",
          "md5": "e752910e2e86c56b7e186783120cc4d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.0+1.21.11.jar",
          "url": "packed_packs_api-fabric-2.2.0+1.21.11.jar",
          "size": 33203,
          "sha512": "5ac7ffe8bcafc801e57490b841287069e5170de8b374cb0c57db8fd62caaf9bb482aef0edf728f099d995f35565409fe48f6fe49357df7ea6e94e536685c8756",
          "sha256": "f7c56649f1b7a25fb6179f53a70ea0d8caab5934f782036b087f23b188724e75",
          "sha1": "576cd7cb75f4adc817150ca536f9377437f84d3e",
          "md5": "e752910e2e86c56b7e186783120cc4d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.2.0+1.21.11-sources.jar",
          "url": "packed_packs_api-fabric-2.2.0+1.21.11-sources.jar",
          "size": 19886,
          "sha512": "e6e9c261a50b1d12e87c109593eabd7fba0c68a2a45603906496792257cfdba46e9e76c6a3a17c4eb3f6c2f67330bbfcbd29fac7ed0029780f1f3b5767a174ba",
          "sha256": "936f3e5ca16a65857350a31ce351d195681415da387b9f8adf3314d9a8be738e",
          "sha1": "2144c41405753282484908ade133d77d931ab1eb",
          "md5": "b1c54ab2d9b5150435bde161243ea1f2"
        }
      ]
    }
  ]
}
