{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.2.5+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.2.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.2.jar",
          "size": 32301,
          "sha512": "4319c0aa3bf5b71890f94b054ce547fe07273060e01f5d214f83c06182d4b5242093e7a9d8876f8ef7eaf610f80e30c69cfe54813613bf6ebdf3d8cd5130506e",
          "sha256": "795726a21eade86a04d164de70133928f0fff7b23f09f1430cb4933d32f0d0bc",
          "sha1": "cbae3b49552f113fc184655f99a68584c6a424fd",
          "md5": "266fe06f10a79e519f55eac11d89d267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.2.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.2.jar",
          "size": 32301,
          "sha512": "4319c0aa3bf5b71890f94b054ce547fe07273060e01f5d214f83c06182d4b5242093e7a9d8876f8ef7eaf610f80e30c69cfe54813613bf6ebdf3d8cd5130506e",
          "sha256": "795726a21eade86a04d164de70133928f0fff7b23f09f1430cb4933d32f0d0bc",
          "sha1": "cbae3b49552f113fc184655f99a68584c6a424fd",
          "md5": "266fe06f10a79e519f55eac11d89d267"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.2.5+26.2-sources.jar",
          "url": "packed_packs_api-neoforge-2.2.5+26.2-sources.jar",
          "size": 19409,
          "sha512": "60ed68477ed949acbae023f3f11645f4a7172e446b5e21125e7300bface228a513f8721ffe0de03d29e78f0d41aab7c8ec75fae2d4d30c19acc86a85f8f1121a",
          "sha256": "fc6f2f585cb6ea016a716e140aef724c0815c09045900b5a4bca0a732505bd55",
          "sha1": "dbe989060c0ff10cfa281c06ff7ec8beee3e914c",
          "md5": "bbf8164ab88d1331681e156183adf8b9"
        }
      ]
    }
  ]
}
