{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-neoforge",
    "version": "0.7.3+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.1.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.1.jar",
          "size": 450894,
          "sha512": "4788f1e931b0f581dd46bcee56a2929225e6dd248c4782d3b36cd20c3d1092c7cfebe5e6aa49b9d51b8dc0cddae29be4ccc5cb1c78d77a83268baac9f1d31101",
          "sha256": "bdf780ccf95bec8e3c237f767984dfdd352c7f3575557ea1660b4dcc61776c46",
          "sha1": "255bdfb047bcb06102e9ec348c6fd7c41b26e25e",
          "md5": "f52d943038c579c11da6a7b1277e64c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.1.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.1.jar",
          "size": 450894,
          "sha512": "4788f1e931b0f581dd46bcee56a2929225e6dd248c4782d3b36cd20c3d1092c7cfebe5e6aa49b9d51b8dc0cddae29be4ccc5cb1c78d77a83268baac9f1d31101",
          "sha256": "bdf780ccf95bec8e3c237f767984dfdd352c7f3575557ea1660b4dcc61776c46",
          "sha1": "255bdfb047bcb06102e9ec348c6fd7c41b26e25e",
          "md5": "f52d943038c579c11da6a7b1277e64c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-neoforge-0.7.3+1.21.1-sources.jar",
          "url": "fidgetz-neoforge-0.7.3+1.21.1-sources.jar",
          "size": 169087,
          "sha512": "436047ddc7ad73d393357b7ed44c775930b8ad9347e1ef8a4a976be075a9afff6259510d205065c7677cc3663e41a629cb534103ad5d0f86fcc1e7e0145f905c",
          "sha256": "3720ff13615ad6d93b9dfb61c1d642f936be5528450f7a2a8be3b42fe40a345d",
          "sha1": "6ef9b6c309b079723f94eadcbf8c96adf94d6270",
          "md5": "52e8905ea54a048aaca9247cc005bc5b"
        }
      ]
    }
  ]
}
