{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-fabric",
    "version": "2.1.0-alpha.12+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1.jar",
          "size": 31627,
          "sha512": "6aa9b209741fa999f69634f0fcad443876daf800956d33e42fa7c7f48be6fd87dc98c440d4bef8df525b9cbdf1513b9711dde8226545bf4907a4e06bf6c2a6db",
          "sha256": "110e8a8061e12722adce8137164075278fc94fcc1f4f1dee59c2491ff81e59e1",
          "sha1": "35082addf3aaa3930413d5462608279ce356b704",
          "md5": "32280ed903834d01f1c25430f8f46a3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1.jar",
          "size": 31627,
          "sha512": "6aa9b209741fa999f69634f0fcad443876daf800956d33e42fa7c7f48be6fd87dc98c440d4bef8df525b9cbdf1513b9711dde8226545bf4907a4e06bf6c2a6db",
          "sha256": "110e8a8061e12722adce8137164075278fc94fcc1f4f1dee59c2491ff81e59e1",
          "sha1": "35082addf3aaa3930413d5462608279ce356b704",
          "md5": "32280ed903834d01f1c25430f8f46a3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1-sources.jar",
          "url": "packed_packs_api-fabric-2.1.0-alpha.12+1.21.1-sources.jar",
          "size": 21236,
          "sha512": "40a947c04c431113eb7ada8f94ad50e7288a495e6d1611de523a8f517f17cd0ef03928c461a5c670810f99789e16b1e2724270a61872b525ea8b6f539741c220",
          "sha256": "ec8ec42fffa199e97ada84dd499b4043212ababae32b4558d38ea7ddc63493ad",
          "sha1": "8fa6e37fd47b33e7ccff61e7042293381d5734b3",
          "md5": "0941f4f2c01bbc6462f7e18b8fb05c81"
        }
      ]
    }
  ]
}
