{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-common",
    "version": "2.1.0-alpha.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-common",
          "version": {
            "requires": "0.2.0.alpha.2+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs_api",
          "module": "packed_packs_api-common",
          "version": {
            "requires": "2.1.0-alpha.2+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.2+1.21.1.jar",
          "size": 467086,
          "sha512": "75a6137e5ccd1462bb59da39eb05398288b1893827b6891fe4ab2e37d23d86fbfbedee54e61dedf2de12511d2ac948d426c7ab9a18332c63ffd447f0b8c0b6d4",
          "sha256": "484c7ce01c15e791ec1c0b67cbc2d2dc42342114124fa176d11ffd269d57b2d3",
          "sha1": "d35e38a4c3e8d4e17aa3c63796c1d25ae5497fb1",
          "md5": "b21a6226e3c703b68d37310a9c26b492"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.2+1.21.1.jar",
          "url": "packed_packs-common-2.1.0-alpha.2+1.21.1.jar",
          "size": 467086,
          "sha512": "75a6137e5ccd1462bb59da39eb05398288b1893827b6891fe4ab2e37d23d86fbfbedee54e61dedf2de12511d2ac948d426c7ab9a18332c63ffd447f0b8c0b6d4",
          "sha256": "484c7ce01c15e791ec1c0b67cbc2d2dc42342114124fa176d11ffd269d57b2d3",
          "sha1": "d35e38a4c3e8d4e17aa3c63796c1d25ae5497fb1",
          "md5": "b21a6226e3c703b68d37310a9c26b492"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-common-2.1.0-alpha.2+1.21.1-sources.jar",
          "url": "packed_packs-common-2.1.0-alpha.2+1.21.1-sources.jar",
          "size": 175460,
          "sha512": "594ccb4d823491c7095fca8e7332c49a285c08fe4212c1443c7fb5d935ad27a60e50079a308ea03774551f354a198861b1e093e92a200a816cead58da96c54ea",
          "sha256": "dd0e42de1898c988b54135f1a6c04587eae3fe3f344f456eb18a4c2db430f258",
          "sha1": "c8c728eb7af51c4a1e398ffd4b10c7af7d6ccfef",
          "md5": "f9935d20727a046d9da5725f44694ddd"
        }
      ]
    }
  ]
}
