{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.fidgetz",
    "module": "fidgetz-common",
    "version": "0.2.0.alpha.4+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.4+1.21.1.jar",
          "size": 178613,
          "sha512": "109e3612b543c24342b729a4b0f7e9c2a99832799db6112aff37938b54d43ebadd170ed0cbbd68222bf6f935ea6d4e3f5ac19e5d6ffa8fce6dee5b6612868874",
          "sha256": "17ef7655e9f985e86d6beccaaa1d132f1a050cb7dc26782d330114b7c4ed293e",
          "sha1": "ec827f5e9e77957cee3197cffe37b717ba6a1531",
          "md5": "b514ef08aca2438f1ffed90ad14169be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.4+1.21.1.jar",
          "url": "fidgetz-common-0.2.0.alpha.4+1.21.1.jar",
          "size": 178613,
          "sha512": "109e3612b543c24342b729a4b0f7e9c2a99832799db6112aff37938b54d43ebadd170ed0cbbd68222bf6f935ea6d4e3f5ac19e5d6ffa8fce6dee5b6612868874",
          "sha256": "17ef7655e9f985e86d6beccaaa1d132f1a050cb7dc26782d330114b7c4ed293e",
          "sha1": "ec827f5e9e77957cee3197cffe37b717ba6a1531",
          "md5": "b514ef08aca2438f1ffed90ad14169be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fidgetz-common-0.2.0.alpha.4+1.21.1-sources.jar",
          "url": "fidgetz-common-0.2.0.alpha.4+1.21.1-sources.jar",
          "size": 73034,
          "sha512": "d1c4654a28364e4f26bb5fb6471ee1f09c383880f4d36d6f804c75dbc28caeb74f5fb02da26b8c9d0ee279334e009f83b1fc4b3f798b99e7d29b24edaec74eca",
          "sha256": "572ac3f08d41456ae2f02cdbf04d75028ee93261de7275369305cf184622763e",
          "sha1": "8ed5fbc98c674df492b4abf58f63caced5ef97f3",
          "md5": "620dd109e88a31b37732b90e424103b4"
        }
      ]
    }
  ]
}
