{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs",
    "module": "packed_packs-fabric",
    "version": "2.1.0-alpha.10+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.10+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.10+1.21.1.jar",
          "size": 677686,
          "sha512": "cddc77e018b6afffa4303a188b39d90c9f4e32121ea46b869c903e3435fbd3d8a987837ed31f8ff66278783b478d5110b60ef59a45662b7047f456334e79455c",
          "sha256": "323bc3a299c5dfecfc128220270ca814e978bc543304f1de9728f22edf22afa0",
          "sha1": "1aa05ed840609e14769bfaa9381075d3e6e828dc",
          "md5": "995df5fae9ff774f77bb80a01a017041"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.fishstiz.fidgetz",
          "module": "fidgetz-fabric",
          "version": {
            "requires": "0.2.0.alpha.3+1.21.1"
          }
        },
        {
          "group": "io.github.fishstiz.packed_packs.api",
          "module": "packed_packs_api-fabric",
          "version": {
            "requires": "2.1.0-alpha.10+1.21.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.115.1+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.10+1.21.1.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.10+1.21.1.jar",
          "size": 677686,
          "sha512": "cddc77e018b6afffa4303a188b39d90c9f4e32121ea46b869c903e3435fbd3d8a987837ed31f8ff66278783b478d5110b60ef59a45662b7047f456334e79455c",
          "sha256": "323bc3a299c5dfecfc128220270ca814e978bc543304f1de9728f22edf22afa0",
          "sha1": "1aa05ed840609e14769bfaa9381075d3e6e828dc",
          "md5": "995df5fae9ff774f77bb80a01a017041"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs-fabric-2.1.0-alpha.10+1.21.1-sources.jar",
          "url": "packed_packs-fabric-2.1.0-alpha.10+1.21.1-sources.jar",
          "size": 203264,
          "sha512": "750a3a605483b98b0cfefc70870f528128003aa98c1c209408fc72bcbfd62575df2e7d59adc1eb276e5f9d31fc3c6f8c66baa7e3e8a13263b8d295886cb66b77",
          "sha256": "ee5c46baea1b72df63e731e8315dfabd3c9cfc5e90601757d9bd41008557682c",
          "sha1": "d8ea43e9dfb70ca618e1efaacbc5257a473451ad",
          "md5": "00cc7964daca83b00d4d492836343791"
        }
      ]
    }
  ]
}
