{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fishstiz.packed_packs.api",
    "module": "packed_packs_api-neoforge",
    "version": "2.3.0-beta.2+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.3.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.3.jar",
          "size": 32423,
          "sha512": "fbfba9dfbc785264a964e0feb7d08eeaad91fcec1ea1febdbb256a44ff4a7abd7ed0260ec3750ee239eafaafa21450842d6b322cd932d41e28cca940c97fb6a3",
          "sha256": "225a18f7f7fcc914c38f45bf7039dfbf5d27cdbbf9263e0951587bb6cbdbed0f",
          "sha1": "5090bbd5511788f41d58ef93c3febdc35d7bdaf8",
          "md5": "f2b9cc4a6228c12a4c41644f0ccf1e30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.3.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.3.jar",
          "size": 32423,
          "sha512": "fbfba9dfbc785264a964e0feb7d08eeaad91fcec1ea1febdbb256a44ff4a7abd7ed0260ec3750ee239eafaafa21450842d6b322cd932d41e28cca940c97fb6a3",
          "sha256": "225a18f7f7fcc914c38f45bf7039dfbf5d27cdbbf9263e0951587bb6cbdbed0f",
          "sha1": "5090bbd5511788f41d58ef93c3febdc35d7bdaf8",
          "md5": "f2b9cc4a6228c12a4c41644f0ccf1e30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "packed_packs_api-neoforge-2.3.0-beta.2+26.3-sources.jar",
          "url": "packed_packs_api-neoforge-2.3.0-beta.2+26.3-sources.jar",
          "size": 19486,
          "sha512": "226bb27c951a6fe28e2b6d88ea665641f12c350b82775a341916c2d5dd10baf916620a355ea598788f0e9a7cc7dd21fd3529eeb18b77a5ded0fab1dff7e776c7",
          "sha256": "ce05b1f753469cffb8fad01bc78a205d9fb53f45bd91eaeca28c94b7a68c9f81",
          "sha1": "5d30123b29f78dad51b532dd925a776ee3e6d670",
          "md5": "64d79d97577d736a5fd6c448f6f2906d"
        }
      ]
    }
  ]
}
